### ISSUE TITLE
Can avifRawData.data be changed to "const uint8_t*"?

### ISSUE THREAD

**Issue by dalecurtis** [AOMediaCodec/libavif#10]
https://github.com/AOMediaCodec/libavif/blob/b30daa175bc6bfe1bf2658e01031ce5b3599b219/include/avif/avif.h#L101

This would allow us to avoid some copies along the way and provides some compiler guarantee that input data won't be modified.

**Comment by dalecurtis** [comment]
Changing it generates a fair number of compilation issues, though it's unclear if they are trivially resolvable at a glance.

**Comment by joedrago** [comment]
v0.3.9 (just committed) splits avifRawData and avifStream into RO and RW parts, which makes most all of the read path const in the ways you're suggesting (I hope). It should be a minor API change on your side (avifRawData -> avifROData).
