### ISSUE TITLE
Conversion of comparison results to avifBool

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#104]
libavif uses the ternary operator ? : to convert a comparison result to avifBool. Here is an example in src/avif.c:

avifBool avifImageUsesU16(avifImage * image)
{
    return (image->depth > 8) ? AVIF_TRUE : AVIF_FALSE;
}

In C, the result of a comparison expression has the type 'int' and is equal to 1 or 0. Since avifBool is a type alias for 'int' and the AVIF_TRUE and AVIF_FALSE macros are defined as 1 and 0, the use of the ternary operator is not necessary. The example above could be written more concisely as follows:

avifBool avifImageUsesU16(avifImage * image)
{
    return image->depth > 8;
}

So far I have been following this style in the pull requests I wrote, but I have been wondering if there is a reason to write it this way.

Note: I believe that compilers will optimize away the ternary operator, so this issue is just a coding style issue.

**Comment by joedrago** [comment]
Yeah, I think it is just a habit from an antiquated notion that see might return all bits set on a comparison instead of just 1 on some compilers, which would cause somebody checking against AVIF_TRUE to fail, but in practice nobody really does that anyway, so I agree with you. 

I will remove them before I make my next release.

**Comment by wantehchang** [comment]
Thank you for the quick fix!

Some code uses an if statement for the conversion. Here is an example in src/codec_dav1d.c:

static avifBool dav1dCodecAlphaLimitedRange(avifCodec * codec)
{
    if (codec->decodeInput->alpha && codec->internal->hasPicture && (codec->internal->colorRange == AVIF_RANGE_LIMITED)) {
        return AVIF_TRUE;
    }
    return AVIF_FALSE;
}

It's not easy to find such code with grep.

**Comment by joedrago** [comment]
That function doesn't exist anymore. I killed it today.
