### ISSUE TITLE
Problem with compilation AOM & AVIF

### ISSUE THREAD

**Issue by Jamaika1** [AOMediaCodec/libavif#1073]
I don't know how to compile AOM SIMD from AVIF. GCC 11.3.1 2022.04.16
I had questions why it doesn't compile in SIMD. 
I downloaded the latest config from google.
AOM has CONFIG_REALTIME_ONLY problem. Is this function deleted and replaced with another?
Can AOM be produced just by AVX? Probably so,since it worked a month ago
A month ago libavif converter without SIMD worked.
When I create libavif from SIMD I get error messages about color planes.

Version: 0.10.1 (aom [enc]:3.4.0-bca4db8, svt [enc]:1.2.0-14c38dc) nosimd
```
Encoding with AV1 codec 'aom' speed [5], color QP [0 (Lossless) <-> 0 (Lossless)], alpha QP [0 (Lossless) <-> 0 (Lossless)], tileRowsLog2 [0], tileColsLog2 [0], 4 worker thread(s), please wait...
Encoded successfully.
 * Color AV1 total size: 17937018 bytes
 * Alpha AV1 total size: 0 bytes
Wrote AVIF: image_21447_24bita.avif
```
Version: 0.10.1 (aom [enc]:3.4.0-03af789, svt [enc]:1.2.1-6e24fb7)
```
Encoding with AV1 codec 'aom' speed [5], color QP [0 (Lossless) <-> 0 (Lossless)], alpha QP [0 (Lossless) <-> 0 (Lossless)], tileRowsLog2 [0], tileColsLog2 [0], 4 worker thread(s), please wait...
ERROR: Failed to encode image: Encoding of color planes failed
Diagnostics:
 * aom_codec_enc_config_default() failed: Invalid parameter
```
Added opensource
https://www.sendspace.com/file/ntuhb7

Edit:
I managed to clarify something. CONFIG_REALTIME_ONLY should not be defined in rtcd files and should be zero.
In GCC 11.3.1 20220429 the AOM noSIMD converter works.
In GCC 11.3.1 20220429 the AOM SIMD AVX converter doesn't work.
In GCC 12.2.0 20220816 the AOM noSIMD converter doesn't work.
In GCC 11.3.1 20220429 the SVT noSIMD converter works.
In GCC 12.2.0 20220816 the SVT noSIMD converter works.

**Comment by wantehchang** [comment]
Hi Jamaika1,

Don't build libaom with `-DCONFIG_REALTIME_ONLY=1`. It is only suitable if all you need to use is `AOM_USAGE_REALTIME`. libavif also needs `AOM_USAGE_ALL_INTRA` and `AOM_USAGE_GOOD_QUALITY`. This is why libavif's `aom_codec_enc_config_default()` call failed when you built libaom with `-DCONFIG_REALTIME_ONLY=1`.

I recommend you build libaom using libavif/ext/aom.cmd. libaom uses SIMD by default. Pass `-DAOM_TARGET_CPU=generic` to turn off SIMD assembly code and intrinsics in libaom.

**Comment by Jamaika1** [comment]
Everything seems simple, but I will describe what does not work for me.
Compatibility of libavif/aom/svt with gcc.
First, I'm using gcc 11.3.1 with `-march=x86-64 -ftree-vectorize -g0 -O3 -fPIC` for default SSE2 noSIMD
I add -DCONFIG_REALTIME_ONLY=0 and have these results:
avifenc.exe -c aom -l -d 8 -y 444 -r full -s 5 -j 4 image_21447_24bit.png image_21447_24bita.avif
`Encoded successfully.`
` * Color AV1 total size: 17937018 bytes`
` * Alpha AV1 total size: 0 bytes`
`Wrote AVIF: image_21447_24bita.avif`
avifenc.exe -c aom -l -d 8 -y 444 -r full -s 8 -j 4 image_21447_24bit.png image_21447_24bita.avif
`Svt[info]: -------------------------------------------`
`Svt[info]: SVT [version]:       SVT-AV1 Encoder Lib 1.2.1-a9e1af5`
`Svt[info]: SVT [build]  :       GCC 11.3.1 20220429      64 bit`
`Svt[info]: LIB Build date: Aug 29 2022 08:25:52`
`Svt[info]: -------------------------------------------`
`Encoded successfully.`
` * Color AV1 total size: 511511 bytes`
` * Alpha AV1 total size: 0 bytes`
`Wrote AVIF: image_21447_24bita_svt.avif`
`SvtMalloc[info]: you have no memory leak`
