### ISSUE TITLE
avifdec writing PNG returns error

### ISSUE THREAD

**Issue by FrankGalligan** [AOMediaCodec/libavif#1086]
Steps to reproduce:
1. ./avifenc input.png output.avif
2. ./avifdec output.avif new.png

I get error:
libpng error: profile 'libavif': 49002h: length does not match profile

If I comment out this line:
https://github.com/AOMediaCodec/libavif/blob/main/apps/shared/avifpng.c#L421

Then I do not see the error.

**Comment by wantehchang** [comment]
Frank: I can't reproduce this bug. Could you provide a sample PNG file? You can email it to me and Yannis. Thanks.

**Comment by wantehchang** [comment]
Yannis: Good job tracking this bug down. This kind of memory error is a serious problem. We should take the opportunity to review the relevant code carefully. Do you know why the Exif and XMP metadata are not affected by this bug? It seems that they avoid this bug by either reading the data early or storing the offset (in the `avifExtent` struct), the same approach you used to fix the bug.

**Comment by y-guyon** [comment]
I sent https://github.com/AOMediaCodec/libavif/pull/1114 as an attempt to catch this kind of issue, when called by a fuzz target for example. A local run of an internal fuzz target did not report anything. Maybe the CI continuous fuzzing will.

**Comment by wantehchang** [comment]
Fixed by https://github.com/AOMediaCodec/libavif/pull/1103.
