### ISSUE TITLE
test library libweb2/libavif/aom SIMD

### ISSUE THREAD

**Issue by Jamaika1** [AOMediaCodec/libavif#1142]
The topic may not be interesting because everything can be downloaded ffmpeg. However, something interests me.

I couldn't create SIMD libraries because aom codec didn't work for me.
Recent fixes to the aom and libavif codec made it only work with gcc 11.3.0.
I also found that for _WIN32_WINNT = 0x0602 and <windows.h> I had to delete NOMINMAX everywhere. The cpuinfo exception.
I had a problem with AOM_USAGE_GOOD_QUALITY. I replaced it with AOM_USAGE_ALL_INTRA in libwebp2.

Test:
echo test AVIF image
avifenc.exe -c aom -l -d 8 -y 444 -r full -s 8 -j 4 image_21447_24bit.png image_21447_24bita1.avif
avifenc.exe -c aom -l -d 8 -y 444 -r full -j 4 image_21447_24bit.png image_21447_24bita2.avif
avifenc.exe -c aom -l -d 8 -y 444 -r full -s 5 -j 4 image_21447_24bit.png image_21447_24bita3.avif
avifenc.exe -c aom -d 8 -y 420 -r limited -s 5 -j 4 image_21447_24bit.jpg image_21447_24bita_jpg.avif
avifenc.exe -c aom -d 8 -y 420 -r limited -s 5 -j 4 image_21447_24bit.y4m image_21447_24bita_y4m.avif
avifenc.exe -c svt -d 8 -y 420 -r limited -s 5 -j 4 image_21447_24bit.jpg image_21447_24bita_svt.avif

echo test AVIF SIMD image
avifenc_avx.exe -c aom -l -d 8 -y 444 -r full -s 8 -j 4 image_21447_24bit.png image_21447_24bita1_avx.avif
avifenc_avx.exe -c aom -l -d 8 -y 444 -r full -j 4 image_21447_24bit.png image_21447_24bita2_avx.avif
avifenc_avx.exe -c aom -l -d 8 -y 444 -r full -s 5 -j 4 image_21447_24bit.png image_21447_24bita3_avx.avif
avifenc_avx.exe -c aom -d 8 -y 420 -r limited -s 5 -j 4 image_21447_24bit.jpg image_21447_24bita_jpg_avx.avif
avifenc_avx.exe -c aom -d 8 -y 420 -r limited -s 5 -j 4 image_21447_24bit.y4m image_21447_24bita_y4m_avx.avif
avifenc_avx.exe -c svt -d 8 -y 420 -r limited -s 5 -j 4 image_21447_24bit.jpg image_21447_24bita_svt_avx.avif

Inquiries:
Why is libavif not working with aom when adding JPG and Y4M files for SIMD?
How to create codecs in GCC 12.2.0 and above? What new features have been added?
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106962
https://www.sendspace.com/file/p7hv05

**Comment by jzern** [comment]
Thanks for the report. There seem to be a couple issues here:
1) Windows compilation, maybe some defines are missing
2) Issues with SIMD builds.

Are you seeing a crash with binaries built with gcc 12.2.0 in libaom or libavif? Are you building with an msys2 environment or something else?

**Comment by Jamaika1** [comment]
I don't see anything disturbing. The libavif SIMD library is created.
Libjpeg-turbo SIMD works with svt-av1 SIMD AVX. I know the svt-av1 codec has SIMD support only for SSE2, AVX2. So only SSE2 is displayed for me. I added the codecs above. AVX2 will not test.
In libheif 
I'm wondering about defined INLINE for libjpeg-turbo and aom. I made a joint for STATIC otherwise there is redefinition.
`#define INLINE inline __attribute__ ((always_inline))`

**Comment by jzern** [comment]
> I don't see anything disturbing. The libavif SIMD library is created.

Most, if not all, of those warnings should be fixed in the latest libaom.

> I added the codecs above. AVX2 will not test.

Do you mean you see a crash or other test failures with AVX2 enabled? Can you give a sample command line?

> I'm wondering about defined INLINE for libjpeg-turbo and aom. I made a joint for STATIC otherwise there is redefinition.
> `#define INLINE inline __attribute__ ((always_inline))`

Everything in libaom should be marked `static INLINE`. Do you have an example of the redefinition errors you were seeing?

**Comment by Jamaika1** [comment]
I have sandybridge processor.
I added the latest libjpeg-turbo fixes and the bugs are gone. I split the inline definitions for aom and libjpeg-turbo.
I created in gcc 11.3.0 codecs again. Unfortunately no improvement. My knowledge ends here.

**Comment by jzern** [comment]
> I have sandybridge processor.
> I added the latest libjpeg-turbo fixes and the bugs are gone.

Do you have a pointer to those? Was that just changing things to force inline?

> I split the inline definitions for aom and libjpeg-turbo.
> I created in gcc 11.3.0 codecs again. Unfortunately no improvement. My knowledge ends here.
> 

So you're seeing a crash in libaom on this platform? Do you have an example command line?

> I have question about the ssim.o file in aom. Why is it possible to make codec without this file? I do add it but gcc treats it as an addon.

The functions in ssim.c are only used in the encoder when CONFIG_INTERNAL_STATS is defined. Otherwise only some tests use these functions. It might be possible to rework the dependency in libaom's cmake to avoid this.

**Comment by jzern** [comment]
Does using cmake and the .cmd files included in the project produce a working build?

I had some earlier questions about the encode command line and what behavior you were seeing, a crash? Does the windows report indicate it was due to an illegal instruction?

**Comment by Jamaika1** [comment]
I don't know what illegal instruction means.
I know you can use cmake. I am surprised that libjpeg-turbo, dav1d, libgav1, x265, libde265, openexr, svt-av1, openhtj2k, openjph work, while aom doesn't work in SIMD.
What am I doing wrong or what other functions does aom have in gcc?
For PNG
avifenc_avx.exe -c aom -l -d 8 -y 444 -r full -s 5 -j 4 image_21447_24bit.png image_21447_24bita.avif
```
Successfully loaded: image_21447_24bit.png
AVIF to be written: (Lossless)
 * Resolution     : 4000x3000
 * Bit Depth      : 8
 * Format         : YUV444
 * Alpha          : Not premultiplied
 * Range          : Full
 * Color Primaries: 1
 * Transfer Char. : 13
 * Matrix Coeffs. : 0
 * ICC Profile    : Absent
 * XMP Metadata   : Absent
 * Exif Metadata  : Absent
 * Transformations: None
 * Progressive    : Unavailable
Encoding with AV1 codec 'aom' speed [5], color QP [0 (Lossless) <-> 0 (Lossless)], alpha QP [0 (Lossless) <-> 0 (Lossless)], tileRowsLog2 [0], tileColsLog2 [0], 4 worker thread(s), please wait...
Encoded successfully.
 * Color AV1 total size: 17937018 bytes
 * Alpha AV1 total size: 0 bytes
Wrote AVIF: image_21447_24bita.avif
```
For JPEG
avifenc_avx.exe -c aom -d 8 -y 420 -r limited -s 5 -j 4 image_21447_24bit.jpg image_21447_24bita_jpg.avif
```
Successfully loaded: image_21447_24bit.jpg
AVIF to be written: (Lossy)
 * Resolution     : 4000x3000
 * Bit Depth      : 8
 * Format         : YUV420
 * Chroma Sam. Pos: 0
 * Alpha          : Absent
 * Range          : Limited
 * Color Primaries: 1
 * Transfer Char. : 13
 * Matrix Coeffs. : 6
 * ICC Profile    : Absent
 * XMP Metadata   : Absent
 * Exif Metadata  : Absent
 * Transformations: None
 * Progressive    : Unavailable
Encoding with AV1 codec 'aom' speed [5], color QP [24 (Medium) <-> 26 (Medium)], alpha QP [0 (Lossless) <-> 0 (Lossless)], tileRowsLog2 [0], tileColsLog2 [0], 4 worker thread(s), please wait...
```
Here is DOS. No error messages are available.

**Comment by jzern** [comment]
> I define CONFIG_INTERNAL_STATS equal 0. Does it mean? Codec doesn't have tune simm.

No, they aren't related. CONFIG_INTERNAL_STATS is meant for use during codec development.

> Here is DOS. No error messages are available.

There's no pop up or anything? I would start by removing some of the compiler flags you're using for libaom and trying the build using aom.cmd to see if it makes any difference. The instructions you're enabling should be available for SandyBridge, but starting with the defaults will give us an idea of where to look next.

**Comment by Jamaika1** [comment]
https://forum.doom9.org/showthread.php?p=1978264#post1978264
