### ISSUE TITLE
Static build of libavif and position-independent code

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#116]
I create a library (libqavif.so) which is a QT imageformats plug-in.
I want to make the libqavif.so stand-alone, without dynamic linking to libavif.so
I can do it when I compile everything as position independent code.
libaom has option to enable it: `-DCONFIG_PIC=1`
I can build libavif as PIC by running:
`CFLAGS="-fPIC" cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DAVIF_CODEC_AOM=ON -DAVIF_LOCAL_AOM=ON ..`
`-fPIC` is for gcc. llc uses `-relocation-model=pic`

I think **CONFIG_PIC** option would be useful for libavif too.

**Comment by vrabaud** [comment]
Thx for reporting, sorry for not keeping up: I believe this has been fixed in https://github.com/AOMediaCodec/libavif/pull/1556
