### ISSUE TITLE
Provide key frame list.

### ISSUE THREAD

**Issue by dalecurtis** [AOMediaCodec/libavif#12]
To save memory, some clients will want to evict things that are not part of the currently displayed set of frames. So having a list of which frames are required to decode a frame at index i is helpful.

Keyframe status can be found in stss, trun, or the OBU header.

**Comment by joedrago** [comment]
I'm adding stss parsing now (it works locally), but what kind of API are you looking for here? 

Possibilities:

* avifDecoderIsKeyframe(decoder, frameIndex) // 0-based
* avifDecoderGetNearestKeyframe(decoder, frameIndex) // 0-based
* exposing the internal syncSample table

With this new keyframe data, I'm experimenting now with an avifDecoderGetNthImage(decoder, frameIndex) which will flush the codec, find the nearest keyframe, and decode up to it. If you had that, would knowing which are keyframes be less interesting?

**Comment by dalecurtis** [comment]
I think both are required for our use case. The first or last API would be best since the Blink decoded image cache tries to be smart about what it can evict and what it doesn't need to decode using knowledge of which frames depend on what.

Later when it tries to refill some of the cache, the GetNthImage you propose would be useful to avoid spinning all the way from the beginning in the worst case (or over several keyframes in the average case).

**Comment by joedrago** [comment]
Alright, I'll add all 3 calls hinted at above and see that goes.

**Comment by joedrago** [comment]
Alright, v0.3.10 should have all of the goodies.

**Comment by dalecurtis** [comment]
Thanks!
