### ISSUE TITLE
AVIF color grid without alpha grid looses alpha when decoded

### ISSUE THREAD

**Issue by y-guyon** [AOMediaCodec/libavif#1203]
This is an image encoded with `avifenc --grid 1x2` (at cd03eef10a7cc6081ee98e3911e21d977a2bf17b using `ext/aom`):

![colorgrid_alphagrid avif](https://user-images.githubusercontent.com/51164219/201102557-104c8b31-5f51-48aa-8016-584b058cd5af.jpg)
(extension is .jpg but it is an actual AVIF file)

The pattern is the following:

```
[primary item grid]
   ^       ^     ^
   |dimg   |dimg |
   |       |     |auxl
[color] [color]  |
                 |
   [alpha aux grid]
      ^       ^
      |dimg   |dimg
      |       |
   [alpha] [alpha]
```

Here is the same image manually edited to match the following pattern:

![colorgrid_alpha_alpha avif](https://user-images.githubusercontent.com/51164219/201103527-92f8fc57-16b4-411f-9df2-d4934474fc27.jpg)

```
[primary item grid]
   ^       ^
   |dimg   |dimg
   |       |
[color] [color]
   ^       ^
   |auxl   |auxl
   |       |
[alpha] [alpha]
```

I did not find anything in ISOBMFF, HEIF and MIAF specifications regarding the invalidity of this pattern. [Compliance Warden](https://gpac.github.io/ComplianceWarden-wasm/avif.html) does not report more errors than for the image generated only with `avifenc` (even fewer errors actually because there is one less grid to complain about `construction_method=-1 on a derived image item`).

`avifdec` (at cd03eef10a7cc6081ee98e3911e21d977a2bf17b using `ext/aom`) leads to the wrongly opaque following PNG:

![colorgrid_alpha_alpha_libavif](https://user-images.githubusercontent.com/51164219/201104722-5379fa5c-ba81-419c-be14-1de368d50561.png)

There is the same issue with libheif: https://github.com/strukturag/libheif/issues/708

**Comment by y-guyon** [comment]
[WD of ISO/IEC 23008-12 4th edition Image file format](https://www.mpeg.org/wp-content/uploads/mpeg_meetings/154_SantaEularia/w26186.zip) says:

> **6.3 Derivation of an output image of an image item**
>
> Auxiliary image item associations are **not** carried over from the input image items to the derived image item.
>
> _NOTE 1 Some implementations forward auxiliary image items associated with input items to the derived image item as an alpha channel. This behaviour is not guaranteed and not mandated. If the intention is for the derived image item to have alpha, the alpha auxiliary image item should explicitly be associated with the derived image item instead._
>
> `EDITORIAL NOTE — New: Do we need language that explains what happens to “native” alpha as well?`

So we may want to remove support for such a pattern from libavif. Thoughts?

**Comment by wantehchang** [comment]
I remember this pattern requires creating fake items. If we remove support for this pattern, we can delete that code. But the code was added three years ago, so the context for the code may have changed and we will need to delete the code carefully. In any case, we should wait until the working draft becomes a final standard.

**Comment by vigneshvg** [comment]
I am fine with removing the code too once the draft is finalized. These files are largely theoretical and i don't think any tool produces such files.
