### ISSUE TITLE
undefined reference to «avifImageCreate»

### ISSUE THREAD

**Issue by PrefectSol** [AOMediaCodec/libavif#1256]
I am trying to use libavif in my code, but when compiling I get the error:

```
 /usr/bin/ld: CMakeFiles/AvifCompressor.dir/src/main.o: in the "main" function:
main.cpp :(.text+0x1d): undefined reference to "avifImageCreate"
collect2: error: execution ld ended with a return code of 1
make[2]: *** [CMakeFiles/Avicompressor.dir/build.make:97: AvifCompressor] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/Avicompressor.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

libavif is located in <proj_dir>/include/

Code:

```
#include "avif/avif.h"

int main() {
    avifImage * image = avifImageCreate(128, 128, 8, AVIF_PIXEL_FORMAT_YUV444); 

    return 0;
}
```

Cmake:

```
project( AvifCompressor )

find_package( libavif REQUIRED )

include_directories( ${libavif_INCLUDE_DIRS} )
include_directories( ./include ./src )

add_executable( AvifCompressor src/main.cpp) 

target_link_libraries( AvifCompressor ${libavif_LIBS} )
```

build project:

```
cd <proj_dir>/include/
git clone https://github.com/AOMediaCodec/libavif.git
cd libavif/ext
./aom.cmd && ./dav1d.cmd && ./libgav1.cmd && ./zlibpng.cmd
cd ..
mkdir build && cd build
cmake ..
sudo make install
```

**Comment by wantehchang** [comment]
Hi Maxim,

I believe the problem is in the CMake file. But I am not familiar with the find_package() function of CMake. The `libavif_LIBS` variable seems wrong. You can try changing `libavif_LIBS` to `libavif_LIBRARIES` or `libavif_LIBRARY`.

**Comment by PrefectSol** [comment]
> Hi Maxim,
> 
> I believe the problem is in the CMake file. But I am not familiar with the find_package() function of CMake. The `libavif_LIBS` variable seems wrong. You can try changing `libavif_LIBS` to `libavif_LIBRARIES` or `libavif_LIBRARY`.

Hi.
Yes, thanks it worked

**Comment by PrefectSol** [comment]
# No, I was wrong. The problem has not been solved.
I change cmake, but that didn't solve my problem either:

```
cmake_minimum_required(VERSION 3.25)

project( AvifCompressor )

find_package(libavif REQUIRED)

find_library( libavif NAMES AVIF_CODEC_RAV1E AVIF_CODEC_LIBGAV1 AVIF_CODEC_DAV1D AVIF_CODEC_AOM )

include_directories( ${libavif_INCLUDE_DIRS} ./include/libavif/)
include_directories( ./include ./src )

add_executable( AvifCompressor src/main.cpp) 

target_link_libraries( AvifCompressor ${libavif_LIBRARY} )
```

And i turn of the cmake options:

-  ``` AVIF_CODEC_AOM```
-  ``` AVIF_CODEC_DAV1D```
-  ```AVIF_CODEC_LIBGAV1```
-  ```AVIF_CODEC_RAV1E```

**Comment by PrefectSol** [comment]
I fixed problem

Just replace ```${libavif_LIBRARY}``` to ```-lavif```
