### ISSUE TITLE
Provide Windows binaries for releases

### ISSUE THREAD

**Issue by thelordofcorruption** [AOMediaCodec/libavif#1270]
Would be nice if Windows binaries could be provided in this project's releases page to make it easier to convert files to AVIF. I know https://ci.appveyor.com/project/louquillio/libavif exists but it only provides builds for the latest commits up to a certain time which are not the release (I assume also more stable) builds.

To clarify when I mean releases I mean this:
![image](https://user-images.githubusercontent.com/111158601/213950444-ac53e7fc-7eb8-4fb5-90f1-5fea48bf7062.png)

**Comment by wantehchang** [comment]
Yannis: I believe you fixed this.

**Comment by y-guyon** [comment]
Indeed, since https://github.com/AOMediaCodec/libavif/pull/1926.
