### ISSUE TITLE
Support image compression up to N bytes

### ISSUE THREAD

**Issue by PrefectSol** [AOMediaCodec/libavif#1271]
I want to compress the image to N bytes, the image parameters are changeable, so I can't just pick up encoder->quality. I want to find out if there is any parameter or function with which I could compress to the size I need?

**Comment by jzern** [comment]
libwebp offers this, but I don't believe libavif currently does.

https://developers.google.com/speed/webp/docs/api#advanced_encoding_api
https://developers.google.com/speed/webp/docs/cwebp#lossy_options

**Comment by y-guyon** [comment]
I tried implementing the `--target-size` flag in https://github.com/AOMediaCodec/libavif/pull/1274 but it required more changes than I anticipated. I do not know if we should move forward with it.

Regarding the original question, wrapping your `avifEncode()` call into a binary search similar to the one in https://github.com/AOMediaCodec/libavif/pull/1274 would work, at the expense of encoding time.

**Comment by PrefectSol** [comment]
> I tried implementing the `--target-size` flag in #1274 but it required more changes than I anticipated. I do not know if we should move forward with it.
> 
> Regarding the original question, wrapping your `avifEncode()` call into a binary search similar to the one in #1274 would work, at the expense of encoding time.

I like this solution,but unfortunately, as you have already said, at a sufficiently low speed, binary search will work quite slowly. I am working on a utility that compressed images to fairly small sizes (800, 900, 1000 bytes), while the image quality in the face area should be higher. Just like you, I thought about binary search and implemented it, but my solution was too slow (6.3 seconds), but after reviewing your solution, I realized how to optimize it. Thank you

**Comment by AKL55** [comment]
I also want this feature,extremely useful for converting an entire comic&Manga library.a target size of 300kb for each page can maintain a good quality,Having to manually change the quality settings for different resolutions to achieve a size of 300kb is a pain.
