### ISSUE TITLE
Warnings in avifjpeg.c

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#128]
```
ninja
[2/28] Building C object CMakeFiles/avifenc.dir/apps/shared/avifjpeg.c.o
FAILED: CMakeFiles/avifenc.dir/apps/shared/avifjpeg.c.o 
/usr/bin/cc  -I../apps/shared -I../include -O2 -pipe -march=native   -std=gnu99 -Werror -Wall -Wextra -pthread -MD -MT CMakeFiles/avifenc.dir/apps/shared/avifjpeg.c.o -MF CMakeFiles/avifenc.dir/apps/shared/avifjpeg.c.o.d -o CMakeFiles/avifenc.dir/apps/shared/avifjpeg.c.o   -c ../apps/shared/avifjpeg.c
../apps/shared/avifjpeg.c: In function ‘avifJPEGRead’:
../apps/shared/avifjpeg.c:32:14: error: variable ‘ret’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
   32 |     avifBool ret = AVIF_FALSE;
      |              ^~~
../apps/shared/avifjpeg.c:34:15: error: variable ‘iccData’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
   34 |     uint8_t * iccData = NULL;
      |               ^~~~~~~
cc1: all warnings being treated as errors
[7/28] Building C object CMakeFiles/avifenc.dir/apps/avifenc.c.o
ninja: build stopped: subcommand failed.
```

My gentoo ebuild script is building libavif in this way, it was OK with libavif 0.6.3
Configure command used to reproduce:
`CFLAGS="-O2 -pipe -march=native" cmake -G Ninja -DAVIF_CODEC_AOM=ON -DAVIF_BUILD_APPS=ON .`.

**Comment by joedrago** [comment]
Ah, good ol' `-Werror=clobbered`. My favorite!

This should fix it:

https://github.com/AOMediaCodec/libavif/commit/b76d06ff34e503a7c60bd32dc3294753e54193ce

I'm going to be adding some new code this week and likely bumping the version afterwards, so if you don't like building from master, expect a proper version tag with this fix in the next couple of days.

**Comment by novomesk** [comment]
Similar favorite one here:
```
../apps/shared/avifpng.c: In function ‘avifPNGWrite’:
../apps/shared/avifpng.c:143:14: error: variable ‘writeResult’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
  143 |     avifBool writeResult = AVIF_FALSE;
      |              ^~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by joedrago** [comment]
Fixed. 

https://github.com/AOMediaCodec/libavif/commit/0e9a4b4c2a1491cf2238eaef10d4219fda02c1b9

**Comment by marchLex** [comment]
> Similar favorite one here:
> 
> ```
> ../apps/shared/avifpng.c: In function ‘avifPNGWrite’:
> ../apps/shared/avifpng.c:143:14: error: variable ‘writeResult’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
>   143 |     avifBool writeResult = AVIF_FALSE;
>       |              ^~~~~~~~~~~
> cc1: all warnings being treated as errors
> ```

same here, fix please ;)

**Comment by y-guyon** [comment]
> almost same here, fix please ;)

Is https://github.com/AOMediaCodec/libavif/pull/1151 enough?

**Comment by marchLex** [comment]
> > almost same here, fix please ;)
> 
> Is #1151 enough?

Thanks! I'd like to believe that it is, but I have no idea how to deal with C language :) so would you mind posting a full example of code I should add to avifpng.c?

**Comment by y-guyon** [comment]
> would you mind posting a full example of code I should add to avifpng.c?

Try replacing the content of your `avifpng.c` file by [this](https://raw.githubusercontent.com/AOMediaCodec/libavif/318dce86cf8f6c75d44eb9c9adf7193fbbba427d/apps/shared/avifpng.c).

**Comment by marchLex** [comment]
> > would you mind posting a full example of code I should add to avifpng.c?
> 
> Try replacing the content of your `avifpng.c` file by [this](https://raw.githubusercontent.com/AOMediaCodec/libavif/318dce86cf8f6c75d44eb9c9adf7193fbbba427d/apps/shared/avifpng.c).

wow! thanks a lot! it works!
