### ISSUE TITLE
Build V0.11 for Android? 

### ISSUE THREAD

**Issue by WizzXu** [AOMediaCodec/libavif#1293]
I could not find V0.11.x version ,on maven central repository,
https://central.sonatype.com/artifact/org.aomedia.avif.android/avif/0.10.1.2e8fe11/versions

Could you please build V0.11 for Android?

**Comment by vigneshvg** [comment]
Done.

0.11 release can be found here: https://repo1.maven.org/maven2/org/aomedia/avif/android/avif/0.11.1.647c3c2/

gradle import string: `org.aomedia.avif.android:avif:0.11.1.647c3c2`

**Comment by WizzXu** [comment]
> 完成。
> 
> 0.11版本可以在这里找到：https://repo1.maven.org/maven2/org/aomedia/avif/android/avif/0.11.1.647c3c2/
> 
> 梯度导入字串：`org.aomedia.avif.android:avif:0.11.1.647c3c2`

Thank you，I find `org.aomedia.avif.android:avif:0.11.1.647c3c2` minSdkVersion="14" ，but project source code `minSdk 21` , here is link https://github.com/AOMediaCodec/libavif/blob/main/android_jni/avifandroidjni/build.gradle . How can I build aar ` minSdkVersion="14" by myself？

**Comment by vigneshvg** [comment]
> How can I build aar ` minSdkVersion="14" by myself？

You can follow the instructions in [the android specific README](https://github.com/AOMediaCodec/libavif/tree/main/android_jni#readme) to build the AAR manually. Note that the maven hosted version of libavif uses dav1d decoder while the instructions on the readme are for libgav1.

**Comment by WizzXu** [comment]
> > How can I build aar ` minSdkVersion="14" by myself？
> 
> You can follow the instructions in [the android specific README](https://github.com/AOMediaCodec/libavif/tree/main/android_jni#readme) to build the AAR manually. Note that the maven hosted version of libavif uses dav1d decoder while the instructions on the readme are for libgav1.

I would like to know  why the maven hosted version of libavif uses dav1d decoder, and readme is libgav1 ? what's the difference?

**Comment by vigneshvg** [comment]
> I would like to know why the maven hosted version of libavif uses dav1d decoder, and readme is libgav1 ? what's the difference?

dav1d is generally faster than libgav1. since the maven hotsed version is intended for production use, it uses the faster decoder.

**Comment by WizzXu** [comment]
> > I would like to know why the maven hosted version of libavif uses dav1d decoder, and readme is libgav1 ? what's the difference?
> 
> dav1d is generally faster than libgav1. since the maven hotsed version is intended for production use, it uses the faster decoder.

Which version does dav1d used?

**Comment by vigneshvg** [comment]
> > > I would like to know why the maven hosted version of libavif uses dav1d decoder, and readme is libgav1 ? what's the difference?
> > 
> > 
> > dav1d is generally faster than libgav1. since the maven hotsed version is intended for production use, it uses the faster decoder.
> 
> Which version does dav1d used?

dav1d from git hash `a3a55b18494f5dd1e34f289298f78ffa4f32a25d` is used in `0.11.1.647c3c2`
