### ISSUE TITLE
My compiled Android version has poor performance

### ISSUE THREAD

**Issue by 6a209** [AOMediaCodec/libavif#1295]
The performance of the main branch I compiled myself is significantly different from that of version  ”org.aomedia.avif.android:avif:0.9.3.a319893“. I followed the steps in the Android readme and used the libgav1 decoder。

Are there any special performance optimization compilation configurations for version 0.9.3.a319893?

**Comment by vigneshvg** [comment]
> The performance of the main branch I compiled myself is significantly different from that of version ”org.aomedia.avif.android:avif:0.9.3.a319893“. I followed the steps in the Android readme and used the libgav1 decoder。
> 
> Are there any special performance optimization compilation configurations for version 0.9.3.a319893?

The maven hosted version of libavif uses the dav1d decoder (not libgav1). That is likely why it is much faster than the one compiled manually with libgav1.

**Comment by vigneshvg** [comment]
> I tested all of your release versions and found that the performance of versions 0.10.1.2e8fe11 and 0.11.1.647c3c2 is significantly worse. Is it possible that some optimization configurations were not enabled?

can you provide some more information on this? which devices did you test on and what images?

**Comment by 6a209** [comment]
Here is my test data use version **0.11.1.647c3c2**

test device： xiaomi 8， cpu ：Qualcomm Snapdragon 845

threads = 0

| Resolution | Count | Average Time (ms) | Minimum Time (ms) | Maximum Time (ms) |
|------------|----------|------------------|--------------------|-------------------|
| 2560x1600  | 200      | 157              | 91                 | 270              |
| 1920x1080  | 500      | 87               | 27                 | 205              |
| 1024x768   | 100      | 56               | 23                 | 88               |
| 1280x720   | 500      | 42               | 11                 | 118              |
| 832x480    | 500      | 39               | 11                 | 89               |
| 416x240    | 400      | 18               | 4                  | 43               |
| Total      | 2200     | 58               |                    |                   |

threads = 1 

| Resolution | Count | Average Time (ms) | Minimum Time (ms) | Maximum Time (ms) |
|------------|----------|------------------|--------------------|-------------------|
| 2560x1600  | 200      | 99               | 95                 | 106              |
| 1920x1080  | 500      | 47               | 29                 | 68               |
| 1024x768   | 100      | 21               | 20                 | 36               |
| 1280x720   | 500      | 19               | 8                  | 35               |
| 832x480    | 500      | 13               | 11                 | 21               |
| 416x240    | 400      | 3                | 2                  | 10               |
| Total      | 2200     | 28               |                    |                   |

So, does this prove that multithreaded decoding will degrade performance?

**Comment by vigneshvg** [comment]
Can you please share the files used in this test?

Multi-threading is faster only if the files are using AV1 tiles.

**Comment by 6a209** [comment]
https://lzd-img-global.slatic.net/g/tps/imgextra/i1/1123208764/O1CN01ZA4dGa2EbxmRVPMqu_!!1123208764.jpg_760x760q80.avif

**Comment by 6a209** [comment]
I asked my colleague in charge of encoding, and they confirmed that no AV1 tiles were used in testing the images. So it's recommended to use single thread if we're not using this feature, right?

**Comment by vigneshvg** [comment]
> I asked my colleague in charge of encoding, and they confirmed that no AV1 tiles were used in testing the images. So it's recommended to use single thread if we're not using this feature, right?

Yes that is correct. The only way that dav1d speeds up AVIF decoding is by using AV1 tiles. Otherwise, all the threading overhead will be a waste. That is probably why you are seeing worse performance with multiple threads.

For large images like 1920x1080 and 2560x1600, you are likely to get much faster performance (both encoding and decoding) if you enable AV1 tiles.
