### ISSUE TITLE
the Decode method return false

### ISSUE THREAD

**Issue by Buxiaohui** [AOMediaCodec/libavif#1316]
I am Android developer，and i think maybe a boolean value is not enough to resolve bug，we need  more information about the decode action。if the decode method  return a String which contain the error msg should be very helpful。

**Comment by Buxiaohui** [comment]
I am Android developer

**Comment by y-guyon** [comment]
I assume you are talking about the Java wrapper API:

https://github.com/AOMediaCodec/libavif/blob/7c5f07d1b06434a5f5f165d3ac1c594ef108216c/android_jni/avifandroidjni/src/main/java/org/aomedia/avif/android/AvifDecoder.java#L76-L80

which does not expose the error as `avifDecoder` from the C API does:

https://github.com/AOMediaCodec/libavif/blob/7c5f07d1b06434a5f5f165d3ac1c594ef108216c/include/avif/avif.h#L979-L980

**Comment by wantehchang** [comment]
Vignesh: Could you take a look? Thanks.

**Comment by vigneshvg** [comment]
> Yes, that's it

Hi, unfortunately, the JNI API only returns a boolean value as of now. It does however log the JNI error in the native code. So if you have access to the logcat at the time of failure, you will able to see the error message there: https://github.com/AOMediaCodec/libavif/blob/d48836b9e6d34a6a090e49eb3490fdf69eee90a6/android_jni/avifandroidjni/src/main/jni/libavif_jni.cc#L75

**Comment by wantehchang** [comment]
Vignesh: Could you also log the diagnostic message? This is the wrapper function I used in Chrome to handle the empty string case:

```
const char* AvifDecoderErrorMessage(const avifDecoder* decoder) {
  // decoder->diag.error is a char array that stores a null-terminated C string.
  return *decoder->diag.error != '\0' ? decoder->diag.error
                                      : "(no error message)";
}
```

You can handle an empty diagnostic message in a different way.

**Comment by vigneshvg** [comment]
> Vignesh: Could you also log the diagnostic message? This is the wrapper function I used in Chrome to handle the empty string case:
> 
> ```
> const char* AvifDecoderErrorMessage(const avifDecoder* decoder) {
>   // decoder->diag.error is a char array that stores a null-terminated C string.
>   return *decoder->diag.error != '\0' ? decoder->diag.error
>                                       : "(no error message)";
> }
> ```
> 
> You can handle an empty diagnostic message in a different way.

Yes, will do.
