### ISSUE TITLE
Add read-only permissions to GitHub workflows

### ISSUE THREAD

**Issue by pnacht** [AOMediaCodec/libavif#1328]
By default, GitHub workflows run with write-all permissions. This makes repositories vulnerable to supply-chain attacks.

As far as I can tell, libavif's workflows are all for testing. As such, they only need read-access to the source code.

I'd like to help the project close this vulnerability. This can be done in two ways:

- We can add top-level read-only permissions to all the workflows; and/or
- You can change the repository settings to change the default permissions from write-all to read-only.

I'll send a PR along with this issue setting the top-level permissions on the workflows. If you'd rather change the repository's default settings:

1. Open the repo settings
2. Go to [Actions > General](https://github.com/AOMediaCodec/libavif/settings/actions)
3. Under "Workflow permissions", set them to "Read repository contents and packages permissions"

---

**Disclosure:** My name is Pedro and I work with Google and the [Open Source Security Foundation (OpenSSF)](https://www.openssf.org/) to improve the supply-chain security of the open-source ecosystem.

**Comment by wantehchang** [comment]
Hi Pedro,

Thank you very mucy for reporting this issue. I have changed our repository's default settings as you suggested. Now our "Workflow permissions" is "Read repository contents and packages permissions".

**Comment by wantehchang** [comment]
@joedrago @jzern @y-guyon Joe, James, Yannis: FYI.

I have changed the default workflow permissions because it's good to be "secure by default".
