### ISSUE TITLE
enum avifNclxMatrixCoefficients is missing an enumerator of value 8 for MC_SMPTE_YCGCO

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#135]
Please refer to the matrix_coefficients  table on page 118 of the AV1 spec, Version 1.0.0 with Errata 1.

matrix_coefficients of value 8 is MC_SMPTE_YCGCO, with the description "YCgCo". This is missing in enum avifNclxMatrixCoefficients.

I have two other questions in this area:

1. In enum avifNclxTransferCharacteristics, the names GAMMA22 (of value 4) and GAMMA28 (of value 5) are used instead of the names TC_BT_470_M and TC_BT_470_B_G used in the AV1 spec. I just wanted to make sure they are the same. It would be good to add a comment to assure the reader that they are the same as the names used in the AV1 spec.

2. In enum avifNclxColourPrimaries and enum avifNclxMatrixCoefficients, two entries BT601_7_625 (of value 5) and BT601_7_525 (of value 6) are used for BT.601, whereas the AV1 spec uses only one entry for BT.601 (CP_BT_601 and MC_BT_601, both of value 6). This is very confusing to someone like me who is unfamiliar with these standards. It would be good to add comments to clarify the correspondence with the AV1 spec.

Thanks!

**Comment by joedrago** [comment]
I can add the missing enum for YCGCO (despite not being fully supported in the YUV conversion layer yet), and I can add alias enums for the two gamma entries to make it clearer.

The existence of 5 and 6 aren't AV1 specific; they're simply a part of the CICP standard:

https://www.itu.int/rec/T-REC-H.273-201612-I/en

I believe one of the BT601 is for PAL, and the other is for NTSC. They are functionally the same (they use the same coefficients). I agree with you that it is confusing, but I'm simply trying to expose the values in the standard as best I can. Perhaps @cconcolato can shed some light on those.

**Comment by joedrago** [comment]
The more I looked at the enums, the more arbitrary they felt, so I decided to redo them to correspond much more closely with the naming conventions from dav1d and libaom. I've made the changes here:

https://github.com/AOMediaCodec/libavif/commit/7ecf41815810d1d89a80fd7b25d8d78b6f4fd277

It is a breaking change (sorry!), but I don't think many early adopters other than Chromium are even paying attention to the color profiles much, so it should be pretty harmless to just overhaul it now.
