### ISSUE TITLE
Could you please add libdav1d_android.sh

### ISSUE THREAD

**Issue by WizzXu** [AOMediaCodec/libavif#1360]
Could you please add libdav1d_android.sh to build libavif?

**Comment by vigneshvg** [comment]
last time i checked dav1d did not have configurations for one of the android x86 targets. i will check again.

**Comment by WizzXu** [comment]
> 上次我检查 dav1d 没有针对其中一个 android x86 目标的配置。我会再检查一次。

Thank you very much

**Comment by vigneshvg** [comment]
> last time i checked dav1d did not have configurations for one of the android x86 targets. i will check again.

dav1d is still missing meson cross compilation configuration files for x86 and x86_64 android targets. i have created a merge request with the dav1d project here: https://code.videolan.org/videolan/dav1d/-/merge_requests/1514

If and when that is merged, i can add the build scripts and update libavif with instructions on how to use dav1d with the android builds.

**Comment by vigneshvg** [comment]
The scripts for enabling `dav1d` for the Android JNI bindings are now available.

**Comment by WizzXu** [comment]
> `dav1d`用于启用Android JNI 绑定的脚本现已可用。

Thank you very match
