### ISSUE TITLE
Image fails to decode via dav1d

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#1374]
Hello,
One user complained in https://bugs.kde.org/show_bug.cgi?id=468884 that KDE apps are unable to open following file:
[lake.zip](https://github.com/AOMediaCodec/libavif/files/11360743/lake.zip)

The file fails to decode when default `dav1d` decoder is used, but when `aom` is used, decoding works.

```
 avifdec -i -c dav1d lake.avif 
Image decoded: lake.avif
 * Resolution     : 7380x4928
 * Bit Depth      : 8
 * Format         : YUV444
 * Alpha          : Absent
 * Range          : Full
 * Color Primaries: 2
 * Transfer Char. : 2
 * Matrix Coeffs. : 6
 * ICC Profile    : Present (476 bytes)
 * XMP Metadata   : Absent
 * Exif Metadata  : Absent
 * Transformations: None
 * Progressive    : Unavailable
 * 1 timescales per second, 1.00 seconds (1 timescales), 1 frame
 * Frame:
ERROR: Failed to decode frame: Decoding of color planes failed
Diagnostics:
 * tile->codec->getNextImage() failed
```

```
avifdec -i -c aom lake.avif 
Image decoded: lake.avif
 * Resolution     : 7380x4928
 * Bit Depth      : 8
 * Format         : YUV444
 * Alpha          : Absent
 * Range          : Full
 * Color Primaries: 2
 * Transfer Char. : 2
 * Matrix Coeffs. : 6
 * ICC Profile    : Present (476 bytes)
 * XMP Metadata   : Absent
 * Exif Metadata  : Absent
 * Transformations: None
 * Progressive    : Unavailable
 * 1 timescales per second, 1.00 seconds (1 timescales), 1 frame
 * Frame:
   * Decoded frame [0] [pts 0.00 (0 timescales)] [duration 1.00 (1 timescales)] [7380x4928]
```

**Comment by jzern** [comment]
Thanks for the report. This file fails on the av1-normative branch and seems to be related to the addition of level 7.x and 8.x support to the encoder. If libaom 3.6.0 created the file then it may be producing streams that aren't a part of the official spec (yet).

```
c038618f6ca1891bde348418d669be4a181fde19 is the first new commit
commit c038618f6ca1891bde348418d669be4a181fde19
Author: Bohan Li <bohanli@google.com>
Date:   Tue Oct 11 09:56:16 2022 -0700

    Implement new level definitions from CWG-C013
    
    Added support for levels 7.x and 8.x.
    
    To ensure compatibility, bitstreams of SEQ_LEVEL_MAX still use the
    original max tile size.
    
    Bug: aomedia:3184
    Bug: aomedia:2871
    Bug: oss-fuzz:50620
    Change-Id: I1b43a3780c6564181e2e9dea8593adc613e0395e
```

**Comment by jzern** [comment]
This stream reports level 7.0 which currently has a [normative change](https://aomedia-review.googlesource.com/c/aom/+/164441/7/av1/common/tile_common.h#58) in the decoding process. libaom should be updated to avoid producing these streams by default.

**Comment by wantehchang** [comment]
@vigneshvg Vignesh: FYI.

James and I tested how all three AV1 decoders (aom v3.5.0, dav1d, and libgav1) handle the lake.avif file. An older version (3.5.0) of aom was used because it doesn't support the newly proposed level 7.0. The `is_valid_seq_level_idx()` function in av1/common/av1_common_int.h needs to be patched to allow SEQ_LEVEL_7_0. We found that aom and dav1d detected the symbol reader overread and reported the bitstream as corrupted or invalid. libgav1 did not check for symbol reader overread and produced invalid output. I filed a libgav1 issue (b/280358508).

**Comment by wantehchang** [comment]
Update: We consider this a serious bug and will create a [libaom v3.6.1 patch release](https://crbug.com/aomedia/3437) to address it. I have just announced [libaom v3.6.1 release candidate 1](https://groups.google.com/a/aomedia.org/g/av1-discuss/c/LAdh3pziIjE). Your testing will be greatly appreciated.

**Comment by novomesk** [comment]
I tried encoding large image with libaom 3.6.1-rc1 and the result was decodable with other software.
Thanks.

**Comment by wantehchang** [comment]
Daniel: Thank you very much for testing libaom 3.6.1-rc1.

I just announced [libaom v3.6.1 release candidate 2](https://groups.google.com/a/aomedia.org/g/av1-discuss/c/JhDk3w77oNo). Compared with release candidate 1, it has just one extra cherry-pick. So you don't really need to repeat your testing.

**Comment by wantehchang** [comment]
[libaom v3.6.1](https://groups.google.com/a/aomedia.org/g/av1-discuss/c/giBE6Kya0aI) has been released.
