### ISSUE TITLE
avifDecoderParse does not set any info on whether alpha is used

### ISSUE THREAD

**Issue by vrabaud** [AOMediaCodec/libavif#1384]
If we want to pre-allocate an output buffer with the right number of channels, we need to get the number of channels with `avifDecoderParse`.  We know whether we use grayscale or not by looking at avifPixelFormat in `decoder.image` but we have no information on alpha.

Should a field be added to avifImage or maybe have an overloaded avifDecoderParse that fills a struct with image info (like done in libavifinfo) ?

**Comment by wantehchang** [comment]
Vincent: This information is in the `alphaPresent` member of the `avifDecoder` struct after `avifDecoderParse()` returns `AVIF_RESULT_OK`.

**Comment by wantehchang** [comment]
Most of the image info is available in the `image` member of the `avifDecoder` struct after `avifDecoderParse()` returns `AVIF_RESULT_OK`. I believe `alphaPresent`, `imageCount`, `progressiveState` are the only exceptions.

**Comment by vrabaud** [comment]
Ah thx, I totally missed that. Thx.
