### ISSUE TITLE
Possible leak when use dav1d and call `avifDecoderNthImage` ?

### ISSUE THREAD

**Issue by dreampiggy** [AOMediaCodec/libavif#1397]
Hi.

### Enviornment
I'm deploy libavif (version 0.11.1) with dav1d codeoc (1.1.0) on arm64 M1 Mac

When testing with animated AVIFS to play ainmation, I use the following code (actually, open-sourced, see [SDWebImageAVIFCoder](https://github.com/SDWebImage/SDWebImageAVIFCoder/blob/0.10.0/SDWebImageAVIFCoder/Classes/SDImageAVIFCoder.m#L408-L417))

### Demo

```objective-c++
    if (_decoder->imageIndex != index) {
        avifResult decodeResult = avifDecoderNthImage(_decoder, (uint32_t)index);
        if (decodeResult != AVIF_RESULT_OK) {
            SD_UNLOCK(_lock);
            return nil;
        }
    }
    width = _decoder->image->width;
    height = _decoder->image->height;
    CGImageRef originImageRef = SDCreateCGImageFromAVIF(_decoder->image);

// Then put this CGImage to NSImageView to display
```

However, when running Xcode (The IDE in Apple's platform)'s leak detection, I found strange leak here:

![image](https://github.com/AOMediaCodec/libavif/assets/6919743/24d976e4-f61b-4a56-ae1d-e54a40fac2ec)

### Full allocation stacktrace

```
posix_memalign		
dav1d_alloc_aligned	/path/to/SDWebImageAVIFCoder/Example/Pods/libdav1d/dav1d/src/mem.h:66	
dav1d_default_picture_alloc	/path/to/SDWebImageAVIFCoder/Example/Pods/libdav1d/dav1d/src/picture.c:71	
picture_alloc_with_edges	/path/to/SDWebImageAVIFCoder/Example/Pods/libdav1d/dav1d/src/picture.c:122	
dav1d_thread_picture_alloc	/path/to/SDWebImageAVIFCoder/Example/Pods/libdav1d/dav1d/src/picture.c:182	
dav1d_submit_frame	/path/to/SDWebImageAVIFCoder/Example/Pods/libdav1d/dav1d/src/decode.c:3670	
dav1d_parse_obus	/path/to/SDWebImageAVIFCoder/Example/Pods/libdav1d/dav1d/src/obu.c:1232	
gen_picture	/path/to/SDWebImageAVIFCoder/Example/Pods/libdav1d/dav1d/src/lib.c:466	
dav1d_send_data	/path/to/SDWebImageAVIFCoder/Example/Pods/libdav1d/dav1d/src/lib.c:496	
dav1dCodecGetNextImage	/path/to/SDWebImageAVIFCoder/Example/Pods/libavif/src/codec_dav1d.c:77	
avifDecoderDecodeTiles	/path/to/SDWebImageAVIFCoder/Example/Pods/libavif/src/read.c:3853	
avifDecoderNextImage	/path/to/SDWebImageAVIFCoder/Example/Pods/libavif/src/read.c:3937	
-[SDImageAVIFCoder animatedImageFrameAtIndex:]	/path/to/SDWebImageAVIFCoder/SDWebImageAVIFCoder/Classes/SDImageAVIFCoder.m:410	
-[SDAnimatedImage animatedImageFrameAtIndex:]	/path/to/SDWebImageAVIFCoder/Example/Pods/SDWebImage/SDWebImage/Core/SDAnimatedImage.m:255	
__67-[SDAnimatedImagePlayer prefetchFrameAtIndex:nextIndex:bufferFull:]_block_invoke	/path/to/SDWebImageAVIFCoder/Example/Pods/SDWebImage/SDWebImage/Core/SDAnimatedImagePlayer.m:363	
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__		
-[NSBlockOperation main]		
__NSOPERATION_IS_INVOKING_MAIN__		
-[NSOperation start]		
__NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__		
__NSOQSchedule_f		
_dispatch_block_async_invoke2		
_dispatch_client_callout		
_dispatch_continuation_pop		
_dispatch_async_redirect_invoke		
_dispatch_root_queue_drain		
_dispatch_worker_thread2		
_pthread_wqthread		
start_wqthread		
```

It shows that dav1d plugin (from `dav1dCodecGetNextImage`), call `dav1d_send_data` and will leak the internal `Dav1dMemPoolBuffer` for each frame.

### Extra
Firstly I just try to switch back to aom codec and use the exact same code above without any modification, then Xcode report no leak at all.

However, I'm not familiar with dav1d's source code. Is this issue inside the libavif or dav1d ? 

### Attachment

Note: The full report can be downloaded here and opened in Xcode.

[Untitled.trace.zip](https://github.com/AOMediaCodec/libavif/files/11497268/Untitled.trace.zip)

**Comment by dreampiggy** [comment]
As a caller, do I need to call anything cleanup before `avifDecoderNthImage` ? Or am I miss something special to dav1d ?

**Comment by dreampiggy** [comment]
Update: I use the `decoder->codecChoice = AVIF_CODEC_CHOICE_AOM`, and new leak in aom detected...

I think there may be some mistake in my caller code, or the libavif's coder plugin impl :(

![image](https://github.com/AOMediaCodec/libavif/assets/6919743/0c75bd9b-d9c3-47e0-852f-7017e248735d)

**Comment by wantehchang** [comment]
Hi DreamPiggy,

Thank you for the bug report. Please verify that `avifDecoderDestroy` is called.

You need to call `avifDecoderParse` before calling `avifDecoderNthImage`.

You can find example code in the libavif/examples/ directory. The avifdec program (libavif/apps/avifdec.c) can also be used as example code.

I am going to use the same environment (libavif version 0.11.1 with dav1d version 1.1.0 on arm64 M1 Mac) and see if I can reproduce the bug using avifdec and the examples. (I will modify them to use `avifDecoderNthImage`.)

**Comment by wantehchang** [comment]
Hi DreamPiggy,

I couldn't figure out how to build dav1d and libpng on a MacBook Pro M1, so I did my debugging on Linux x86_64. I used libavif version 0.11.1 with libaom version 3.5.0 and dav1d version 1.1.0.

I changed avifdec to use `avifDecoderNthImage`:

```
diff --git a/apps/avifdec.c b/apps/avifdec.c
index a0a0251..47b724e 100644
--- a/apps/avifdec.c
+++ b/apps/avifdec.c
@@ -259,7 +259,7 @@ int main(int argc, char * argv[])
             }
 
             int currIndex = 0;
-            while ((result = avifDecoderNextImage(decoder)) == AVIF_RESULT_OK) {
+            while ((result = avifDecoderNthImage(decoder, currIndex)) == AVIF_RESULT_OK) {
                 printf("   * Decoded frame [%d] [pts %2.2f (%" PRIu64 " timescales)] [duration %2.2f (%" PRIu64 " timescales)] [%ux%u]\n",
                        currIndex,
                        decoder->imageTiming.pts,
```

Then I ran these two commands:

```
avifdec --info star-12bpc-with-alpha.avifs
avifdec -c aom --info star-12bpc-with-alpha.avifs
```

AddressSanitizer (with its LeakSanitizer enabled) and Valgrind did not report any memory leaks. If I commented out the `avifDecoderDestroy` call at line 284 of libavif/apps/avifdec.c, then Valgrind reported the memory leak you reported. (AddressSanitizer reported a memory leak when libaom was used but reported no memory leaks when dav1d was used. I don't know why.)

So most likely there is some mistake in your caller code. If I have to guess, I would guess `avifDecoderDestroy` is not being called.

You can look at how libavif/apps/avifdec.c call `avifDecoderParse`, `avifDecoderNextImage` (which I changed to `avifDecoderNthImage`), and `avifDecoderDestroy` from line 242 to line 284.

**Comment by dreampiggy** [comment]
That `avifDecoderDestroy` is called the when the decoder instance dealloc. However, during my example, the decoder is always rendering the animated image in loop, so it should not been dealloc...

I'll try to modify the example to make that implicit dealloc and test again

**Comment by dreampiggy** [comment]
Seems the Leak Detection tools's bug ? When I make the animated decoder dealloc, the leak disappear.

![image](https://github.com/AOMediaCodec/libavif/assets/6919743/49329d0d-6b06-41a5-a04e-ff7b7eaffcba)


The strange is why only this codec lib has this wrong detection (I tested libwebp, libheif, libapng, libbpg... all others no report) 😂

**Comment by dreampiggy** [comment]
Close for now, once I have more confidence about the leak detection result for this

**Comment by wantehchang** [comment]
Hi DreamPiggy,

I have only limited experience with Objective-C, so I won't be able to help you figure out why the AVIF decoder instance is not deallocated implicitly.

Are the decoder instances for the other formats (libwebp, libheif, libapng, libbpg) deallocated implicitly?

Note: libheif doesn't support animated images (called "image sequences" in HEIF), so SDImageHEIFCoder doesn't have methods for animated images.
