### ISSUE TITLE
A PNG image that cannot be converted correctly

### ISSUE THREAD

**Issue by DeepTulip** [AOMediaCodec/libavif#1423]
I have converted a lot of images to avif and only encountered this one wrong png image even though I used the "-l" lossless parameter.
It converts properly to jxl.

win-10 64
avifenc.exe version:
Version: 0.11.1 (dav1d [dec]:1.2.0-0-g676a864, aom [enc/dec]:3.6.1)

libyuv : available (1864)

command line:
C:\test\avifenc.exe -l C:\test\test.png C:\test\out-2.avif

[test.zip](https://github.com/AOMediaCodec/libavif/files/11638697/test.zip)

**Comment by vrabaud** [comment]
Can you please copy/paste the command line or piece of code you used? Thx.
