### ISSUE TITLE
Add OpenSSF Scorecard workflow

### ISSUE THREAD

**Issue by pnacht** [AOMediaCodec/libavif#1433]
Hey, it's Pedro (see #1329 and #1342) and I've got another security suggestion for libavif!

I'd like to suggest that the project add the [OpenSSF Scorecard Action](https://github.com/ossf/scorecard-action). The OpenSSF Scorecard runs a sort of "meta-analysis" of the project's security posture, and the Action then populates the project's [Security Panel](https://github.com/AOMediaCodec/libavif/security) with possible improvements to its security posture.

In fact, I used Scorecard to detect the issues fixed in #1329 and #1342. The Action would simply do the same thing, letting you know if there's anything you can do to improve libavif's security.

This data is fetched via GitHub's public API, and the project's current score can already be seen [here](https://deps.dev/project/github/aomediacodec%2Flibavif). It's currently a 7.0/10, which puts libavif at the top 10% of relevant projects.

If you're interested, let me know and I'll send a PR!

**Comment by jzern** [comment]
Thanks Pedro. Please feel free to send any changes that help improve the project's security posture.
