### ISSUE TITLE
Recognize extensions with capital letters / capslock (.JPG i.e.)

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/libavif#144]
Some programs and cameras export their images with capital extensions. They shouldn't, but they still do. It would be nice if the sample applications could recognize and encode/decode those.

For example, currently an error like `Unrecognized file extension: JPG` is displayed when trying to encode a jpg file with an `.JPG` extension.

**Comment by joedrago** [comment]
I liked this idea, so I just added it in. Thanks!
