### ISSUE TITLE
Error while using  avifImageYUVToRGB

### ISSUE THREAD

**Issue by cparkhi16** [AOMediaCodec/libavif#1451]
I am using libavif to decode my avif image and create a bitmap from its pixel data so that I can encode it in any other format. 
I am following the example for decoding a avif image from examples directory (avif_example_decode_file.c).
I am able to decode my avif image and able to get the height , width and depth of the image . But my next goal is to create a bitmap from the pixel data of avif image. And I think to do it, I will need to convert Avif image from YUV format to RGB format and then I can get pixel data from avifRGBImage. 
But when I am trying to use avifImageYUVToRGB , it is throwing a error (Reformat failed). 
I also checked that my avif image after successful decoding is in YUV420 format. Can anyone let me know what might be the issue here?

**Comment by y-guyon** [comment]
Thank you for reporting the issue.  
Could you provide sample code (for example a modified `avif_example_decode_file.c`) and an image to reproduce the issue? The error is rather generic.

**Comment by cparkhi16** [comment]
Thank you for replying.
Here is the sample code, I am trying to decode my avif image and then trying to get pixel data from the image by converting YUV format to RGB format using avifImageYUVToRGB :

 
![image](https://github.com/AOMediaCodec/libavif/assets/60289255/a7b2051c-543e-437f-b82b-3a1f75783013)

Since my avif image is not animated I am not using avifDecoderNextImage as mentioned in the examples directory of libavif (src/examples/avif_example_decode_file.c). 

Here is the sample image :

[avifimage.zip](https://github.com/AOMediaCodec/libavif/files/11864339/avifimage.zip)

**Comment by y-guyon** [comment]
The issue is that `avifDecoderNextImage()` was never called.  
`avifDecoderParse()` extracts information from the container (dimensions etc.) but does not actually decode the pixels.

I suggest the following instead:

```cpp
avifImage * image = avifImageCreateEmpty();
avifDecoder * decoder = avifDecoderCreate();
if (image == nullptr || decoder == nullptr) { /* handle error */ }
avifResult result = avifDecoderReadFile(decoder, image, path);
if (result != AVIF_RESULT_OK) { /* handle error */ }

avifRGBImage rgb;
avifRGBImageSetDefaults(&rgb, image);
result = avifRGBImageAllocatePixels();
if (result != AVIF_RESULT_OK) { /* handle error */ }
result = avifImageYUVToRGB(image, &rgb);
if (result != AVIF_RESULT_OK) { /* handle error */ }

avifImageDestroy(image);
avifDecoderDestroy(decoder);

// Copy pixels from rgb to your pixelData.
// std::copy()...

avifRGBImageFreePixels(&rgb);
```

Remember to release the allocated memory by calling `avifImageDestroy()` etc.  
Alternatively use `std::unique_ptr` to avoid forgetting it.

**Comment by cparkhi16** [comment]
Thank you for helping , surely will try this !

**Comment by cparkhi16** [comment]
Hey I tried using above approach for decoding the avif file but my program seems crashing when we call `avifImageYUVToRGB`

**Comment by y-guyon** [comment]
Could you try debugging to see why it is crashing and where in libavif?

---

How are you compiling libavif? The following works for me on Linux:

```sh
git clone https://github.com/AOMediaCodec/libavif.git
cd libavif
git checkout 7caa161
cd ext
./aom.cmd
cd ..
mkdir build
cd build
cmake .. -DAVIF_BUILD_EXAMPLES=ON -DAVIF_CODEC_AOM=ON -DAVIF_LOCAL_AOM=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_COMPILER=clang
make
./avif_example_decode_file ~/Downloads/flowers.avif && echo "Success"
```

With https://github.com/AOMediaCodec/libavif/issues/1451#issuecomment-1606903425 replacing the `main` body in `avif_example_decode_file.c` of course.

**Comment by cparkhi16** [comment]
Sure will try building libavif using above steps. Currently I am working on a Chromium CEF project which builds libavif by itself , so I am able to call the functions directly without building libavif myself.

**Comment by cparkhi16** [comment]
Hey thanks for your input, I am now able to get pixel data from my avif image and convert it to the required format using above build configuration !
