### ISSUE TITLE
AVIF encoder totally broken

### ISSUE THREAD

**Issue by RyanHakurei** [AOMediaCodec/libavif#1462]
Anytime I try to encode an image in avif, this is the output:
![image](https://github.com/AOMediaCodec/libavif/assets/5086636/8346c609-ac5b-4183-968f-82825db39e4e)

This is the source image, in this case a RAW/dng exported from Darktable:
![image](https://github.com/AOMediaCodec/libavif/assets/5086636/8e36b5f7-c193-4e55-918e-4a38aeac1ec8)

The output is always a garbled whateverthefuck regardless of the input image or the program used to write the avif image. Imagemagick, Darktable, and [plasma5-wallpapers-dynamic](https://github.com/zzag/plasma5-wallpapers-dynamic), no matter what this is the type of result I've come to expect every time I attempt to encode an image into avif.

**OS:** Archlinux (rolling)
**Libavif version:** 0.11.1-1

**Comment by kmilos** [comment]
> As for the specific Imagemagick command I'm just leaving every flag stock `convert input.ext output.avif` and I would assume since I'm not setting any flags it's using the libaom backend?

AFAIK, IM is using libaom, but via libheif, not libavif. Darktable is using libavif.

**Comment by jzern** [comment]
I tried to reproduce this on x86-64 using `docker run -it archlinux`, but the resulting file using ImageMagick [1] didn't show any corruption.
What version of ImageMagick do you have installed? Are you running on x86-64 or another architecture? If you can, try out the docker image to see if the results are consistent.

[1]
```
Version: ImageMagick 7.1.1-12 Q16-HDRI x86_64 21239 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zip zlib
Compiler: gcc (13.1)
```

**Comment by jzern** [comment]
> Also is there a docker image for Imagemagick or are you talking about running a generic Arch docker image and attempting a conversion?

The second one. I used the docker image referenced by https://archlinux.org/download/.

**Comment by jzern** [comment]
> > Also is there a docker image for Imagemagick or are you talking about running a generic Arch docker image and attempting a conversion?
> 
> The second one. I used the docker image referenced by https://archlinux.org/download/.

On that instance I installed `imagemagick 7.1.1.12-2` and ran convert. I extracted the image and viewed the result using Chrome 114.0.5735.198.
