### ISSUE TITLE
"GBR" in comment in include/avif/avif.h

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#151]
include/avif/avif.h has this comment:

  AVIF_REFORMAT_MODE_IDENTITY              // Pack GBR directly into YUV planes

Should "GBR" read "RGB" or "BGR"?

**Comment by joedrago** [comment]
The ordering "GBR" is on purpose here; it matches the order in which the channels correspond to / replace the YUV channels.

From Page 12 of this doc: https://www.itu.int/rec/T-REC-H.273-201612-I/en

    The identity matrix.
    Typically used for GBR (often referred to as RGB); however, may also be used for
    YZX (often referred to as XYZ);
    IEC 61966-2-1 sRGB
    SMPTE ST 428-1

I agree that the ordering "GBR" catches the eye though, as it is so uncommon if not for this channel correspondence in this very specific case.
