### ISSUE TITLE
avifenc: Change the default value of --jobs to "all"

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#1522]
The default value of the --jobs option for avifenc is 1 (single threaded). It would be good to change the default to "all" (use all available cores).

**Comment by vrabaud** [comment]
That can be dangerous as it could hog ressources no? And maybe -j 100 would be counter-productive on CPUs with many cores. How about maxing to 4 or 8, and to all-1?

**Comment by FrankGalligan** [comment]
My guess is the default --jobs all is fine. 

First. I'm not sure setting jobs to "all" will hog the resources so everything else is unusable. But we should be able to test this.

Second, Lets look at some use cases where avifenc may be used with --jobs set to all:
1. User encoding one file at a time. 12MP will be done in less than a second with all the defaults. So the user would not have time to switch to something else.
2. User profiling encode time. This is their main purpose, so the fastest encode is the best.
3. User encoding many photos. This is their only current task then "all" is fine.
4. User encoding many photos. They want to perform multiple tasks, then "all" may hog resources from their other task. This user may also be more likely to set their own --jobs flag.
5. Encoding service with many users. This is an advanced usage and I would assume they would set the advanced settings tailored to their use case.

So IMO the only use case that setting default to "all" may be detrimental is 4. But my guess percentage wise both 3 & 4 will be much lower compared to other use cases. Also I think 4 would be more likely to set the jobs parameter based on what they are doing on their machine.

That being said, if we set the default to "all", we can watch the issue tracker to see if we need to change this decision in the future as well.

**Comment by y-guyon** [comment]
There could also be a warning displayed when running `avifenc` to remind users to explicitly set `--jobs`. Not saying we should do that but it may help.
