### ISSUE TITLE
libavif-1.0.0 FTBFS with `-DAVIF_BUILD_GDK_PIXBUF=ON`

### ISSUE THREAD

**Issue by xry111** [AOMediaCodec/libavif#1526]
In 676aded3501ff453c88a6d9ed1e5b4f33b458f3e `imir.mode` is renamed to `imir.axis`, but `contrib/gdk-pixbuf/loader.c` still refers to `imir.mode`.

**Comment by wantehchang** [comment]
Thank you for the bug report. I am sorry about the compilation error.

Fixed by commit 26224fe476ec660e44c816ca5b95d6ed08d1ad06.

**Comment by wantehchang** [comment]
We will create a libavif 1.0.1 release to address this issue.
