### ISSUE TITLE
The "don't subsample GBR" comment in avifenc is incorrect or confusing

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#158]
In libavif v0.7.3, the following code and comment was added to avifenc.c:

        } else if (!strcmp(arg, "-l") || !strcmp(arg, "--lossless")) {
            lossless = AVIF_TRUE;

            // Set defaults, and warn later on if anything looks incorrect
            requestedFormat = AVIF_PIXEL_FORMAT_YUV444;  // don't subsample GBR
            ...

At first glance, I thought the "don't sample GBR" comment has a typo and should read "don't subsample chroma". On close inspection, I suspect the comment is applicable only when sourceWasRGB is true, in which case the comment is correct but quite confusing without that context.

It would be good to fix or clarify this comment.

**Comment by joedrago** [comment]
In my recent CICP refactor pass, I happened to reword this (probably remembering this issue) to this:

    requestedFormat = AVIF_PIXEL_FORMAT_YUV444;  // don't subsample when using AVIF_MATRIX_COEFFICIENTS_IDENTITY

I hope that is clearer.

**Comment by wantehchang** [comment]
Yes, the new comment is clear. Thanks!
