### ISSUE TITLE
building under MSYS2 on Windows

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#162]
There is following code in CMakeLists.txt
```
    if(AVIF_LOCAL_AOM)
        if(WIN32)
            set(LIB_FILENAME "${CMAKE_CURRENT_SOURCE_DIR}/ext/aom/build.libavif/aom.lib")
        else()
            set(LIB_FILENAME "${CMAKE_CURRENT_SOURCE_DIR}/ext/aom/build.libavif/libaom.a")
        endif()
```
When I am building libavif on Windows under MSYS2, I encounter problem here. cmake complains about missing **aom.lib**, but there is actually **libaom.a**

Of course I am able to patch the filename in order to build libavif successfully but if someone knows how to make proper MSYS2 autodetection in cmake, it would be welcomed.

**Comment by joedrago** [comment]
Perhaps we can bolster that conditional? Does something like:

`if(WIN32 AND NOT CYGWIN)`

work?

**Comment by 1480c1** [comment]
`CYGWIN` is not defined under msys2's cmake nor mingw-w64 cmake

**Comment by joedrago** [comment]
I'm just not too familiar with msys or cygwin. How about:

`if(WIN32 AND NOT MINGW)`

? Let me know if you can come up with a working conditional, please.

**Comment by joedrago** [comment]
The normal path use `find_package`, and I completely agree, you should use that path when possible. @novomesk is trying to use `AVIF_LOCAL_*`, which is explicitly asking for some local static hacks to be enabled.

If you want to use typical Unix style shared library setup and discovery, don't disable `ENABLE_SHARED_LIBS`, and don't enable any `AVIF_LOCAL_*` defines. Asking for those is explicitly opting into the embedded hacks I've put in which try to help out unfriendly build envs.

**Comment by 1480c1** [comment]
Simplest fix would be

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 969c6a3..12a9434 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -244,7 +244,7 @@ if(AVIF_CODEC_AOM)
         src/codec_aom.c
     )
     if(AVIF_LOCAL_AOM)
-        if(WIN32)
+        if(MSVC)
             set(LIB_FILENAME "${CMAKE_CURRENT_SOURCE_DIR}/ext/aom/build.libavif/aom.lib")
         else()
             set(LIB_FILENAME "${CMAKE_CURRENT_SOURCE_DIR}/ext/aom/build.libavif/libaom.a")
```

since assuming the person built aom with the same cmake, generator, and toolchain, the only time it will produce that file would be if it's using MSVC.

An alternative one would be doing something similar to what is currently being done with librav1e which is
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 969c6a3..6313ac5 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -244,9 +244,8 @@ if(AVIF_CODEC_AOM)
         src/codec_aom.c
     )
     if(AVIF_LOCAL_AOM)
-        if(WIN32)
-            set(LIB_FILENAME "${CMAKE_CURRENT_SOURCE_DIR}/ext/aom/build.libavif/aom.lib")
-        else()
+        set(LIB_FILENAME "${CMAKE_CURRENT_SOURCE_DIR}/ext/aom/build.libavif/aom.lib")
+        if(NOT EXISTS "${LIB_FILENAME}")
             set(LIB_FILENAME "${CMAKE_CURRENT_SOURCE_DIR}/ext/aom/build.libavif/libaom.a")
         endif()
         if(NOT EXISTS "${LIB_FILENAME}")
```

**Comment by 1480c1** [comment]
Also, @novomesk MSYS2 provides `mingw64/mingw-w64-x86_64-aom`, `mingw64/mingw-w64-x86_64-pkg-config`, and `mingw64/mingw-w64-x86_64-dav1d` packages you can install through `pacman -S` that the `Find*.cmake` file can look for


```none
-- Checking for module 'dav1d'
--   Found dav1d, version 0.6.0
-- Found dav1d: D:/msys64/mingw64/lib/libdav1d.dll.a (found version "0.6.0")
-- libavif: Codec enabled: aom (encode/decode)
-- Checking for module 'aom'
--   Found aom, version 1.0.0
-- Found aom: D:/msys64/mingw64/lib/libaom.a (found version "1.0.0")
```

If you don't want to use the `dll.a` file, you can "hide" it by moving it temporarily or delete it if you don't need it
