### ISSUE TITLE
Need to Identify libavif Version with libavif.15.dylib

### ISSUE THREAD

**Issue by Ssionn** [AOMediaCodec/libavif#1628]
Hello,

I'm currently facing an issue with the libgd library, which is expecting libavif.15.dylib. However, I have a newer version of libavif installed, and I'm unable to determine which release/version of libavif contains the required libavif.15.dylib.

I have looked through the releases but couldn't pinpoint the exact version that houses this specific library file. Would you be able to guide me on which release or version of libavif I should be looking at to obtain libavif.15.dylib?

Your help would be greatly appreciated, and it will assist in resolving my library dependency issue.

Thank you in advance for your time and assistance!

**Comment by Ssionn** [comment]
Thank you, the issue I was experiencing has been resolved.

This issue can be closed 👍🏼

**Comment by wantehchang** [comment]
Yannis: Your suggestion is a good idea. We can also retroactively add this info to the changelog for a few recent releases.

Casper: libavif.15.dylib is libavif v0.11.0 or v0.11.1 as Yannis said. libavif.16.dylib is libavif v1.0.0, v1.0.1, or all future v1.x.y releases.
