### ISSUE TITLE
mingw-w64: legacy_stdio_definitions.lib does not exist

### ISSUE THREAD

**Issue by 1480c1** [AOMediaCodec/libavif#1647]
this library doesn't exist with mingw-w64 as far as I can tell, and causes a linking error:

```bash
/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -llegacy_stdio_definitions: No such file or directory
```

**Comment by wantehchang** [comment]
@fdintino @vrabaud Could you take a look at this?

The reference to legacy_stdio_definitions.lib comes from https://github.com/AOMediaCodec/libavif/pull/1579.

**Comment by fdintino** [comment]
It looks like rustc default links to all of those libraries, so I was wrong to pull it from the pkgconfig file. I'll reconfirm the symbols in the windows build of rav1e.

**Comment by fdintino** [comment]
And actually it looks like legacy_stdio_definitions.lib was removed recently, in rust-lang/libc#3226. So at the very least we can safely remove it from this list, notwithstanding the other libraries.
