### ISSUE TITLE
Expose chroma_sample_position in the avifImage struct

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#165]
The AV1 sequence header OBU has a chroma_sample_position syntax element. This should be exposed in the avifImage struct. It is useful to the YUV to RGB conversion when chroma is subsampled.

In dav1d, this is available in dav1dImage->seq_hdr->chr.

Note: the possible values of chrome_sample_position in AV1 do not include "centered":

>   0 CSP_UNKNOWN Unknown (in this case the source video transfer function must be
> signaled outside the AV1 bitstream)
>   1 CSP_VERTICAL Horizontally co-located with (0, 0) luma sample, vertical position in
> the middle between two luma samples
>   2 CSP_COLOCATED co-located with (0, 0) luma sample
>   3 CSP_RESERVED

I don't know why. The diagram from ffmpeg/libavutil/pixfmt.h before the definition of enum AVChromaLocation is very clear.

**Comment by silverbacknet** [comment]
HEVC and AV1 both dropped JPEG-style centered chroma, and HEIF is defined in terms of HEVC, which ONLY supports the equivalent of CSP_VERTICAL, and AVIF doesn't extend that. Unless there's something in MIAF that I don't know about, which is always the big wildcard, I don't think any chroma format but CSP_VERTICAL is allowed.

**Comment by joedrago** [comment]
This is done (see `avifImage`'s `yuvChromaSamplePosition`)
