### ISSUE TITLE
Add support for the SVT-AV1 encoder

### ISSUE THREAD

**Issue by brad0** [AOMediaCodec/libavif#167]
Please add support for the SVT-AV1 encoder.

**Comment by 1480c1** [comment]
https://github.com/OpenVisualCloud/SVT-AV1/issues/12

I think the current resolution limitations will be a hindrance to adding SVT-AV1 to libavif

**Comment by novomesk** [comment]
I think image grid will be used in future to encode extremely large images.

**Comment by 1480c1** [comment]
I think this can be closed

**Comment by brad0** [comment]
It looks like that is the case.
