### ISSUE TITLE
Failure to build libavif, GCC 8.3.0, sparc64

### ISSUE THREAD

**Issue by brad0** [AOMediaCodec/libavif#168]
Trying to build libavif 0.7.1 on sparc64 with GCC 8.3.0 fails like so..

/usr/obj/ports/libavif-0.7.1/libavif-0.7.1/apps/shared/avifjpeg.c: In function 'avifJPEGRead':
/usr/obj/ports/libavif-0.7.1/libavif-0.7.1/apps/shared/avifjpeg.c:32:14: error: variable 'ret' might be clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]
     avifBool ret = AVIF_FALSE;
              ^~~
/usr/obj/ports/libavif-0.7.1/libavif-0.7.1/apps/shared/avifjpeg.c:34:15: error: variable 'iccData' might be clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]
     uint8_t * iccData = NULL;
               ^~~~~~~
cc1: all warnings being treated as errors

**Comment by novomesk** [comment]
This was fixed in newer versions. Try 0.7.2 or 0.7.3

**Comment by brad0** [comment]
Oh, ok. Thanks. 0.7.3 was just commited so I'll see about the build host trying that with the next round.
