### ISSUE TITLE
Add support to write AVIF without encoding

### ISSUE THREAD

**Issue by ePirat** [AOMediaCodec/libavif#170]
When decoding existing AVIF data, for some applications like an Image Viewer, it would be useful to be able to save that back into an AVIF buffer without re-encoding (so just use the already encoded content of the existing AVIF), so that metadata can be modified and does not require re-encode to write them.

**Comment by joedrago** [comment]
This is a tricky one, as it is solving a different problem than libavif is built to solve. I recognize the request and the use case, but libavif isn't trying to retain the entire parsed BMFF tree from the file, which would be required for any kind of true tweaking of data without changing anything else. I could maybe see surfacing the AV1 payloads in an avifDecoder so that you could pass them to the avifEncoder (and thus avoid the re-encode), but this might just be the wrong approach entirely.

If your goal is to take a valid AVIF and just tune some minor metadata (leaving everything else intact), you are probably much better served by a generic BMFF parsing library, and tweaking a box here or there. Properly supporting this would effectively be a rewrite.

**Comment by ePirat** [comment]
Hi, thanks a lot for the answer!

I understand that preserving the whole BMFF tree might be too complex to do.
I'm not really asking for that, for my use-case just being able to write a "new" AVIF but with existing encoded data would be enough. I just want to avoid the possible quality penalty of re-encoding over and over again.

On another note, what exactly is the goal of the library / problem this library tries to solve? As when I would do the muxing myself, is there any reason left for using libavif vs just calling the encoder/decoder myself?

**Comment by joedrago** [comment]
The goal of libavif is to provide an image library in the same vein as libpng, libjpeg, libwebp, etc. It has a means to easily get you from an AVIF binary payload to interleaved RGBA with metadata, and a separate means to get you from interleaved RGBA with metadata back to a legal AVIF payload.

AVIF (based on HEIF) is a pretty wide format, as far as feature sets go; Even libavif doesn't fully support all of the various features yet. But to be precise about your question, libavif provides the following for decoding:

* Parsing the BMFF and validating it as a legal AVIF
* Detecting "primary items" vs "tracks"
* Associating the auxiliary alpha plane (in a separate AV1 payload) with the primary payload
* Converting two YUV planar payloads (of arbitrary depth, range, and subsampling) to a single interleaved RGB(A) buffer (of arbitrary depth, full range)
* Offering timing information from the sample table (if an image sequence)
* Surfacing all discovered metadata (ICC, CICP, transforms, EXIF, XMP)

None of these are impossible tasks to implement yourself, and I'm the first in line to hope that there are multiple implementations of the AVIF standard out in the wild. That said, properly interpreting "items" is a bit of a pain, and the correct conversion from the internal YUV+A formats to RGB+A ends up being quite a bit of work. If you want to take a shot at it, I'm available to answer any questions you have.

**Comment by ePirat** [comment]
So from reading that list it seems that BMFF handling is exactly what I would like to avoid doing, as its complex and I would probably get it wrong in some areas.

So a way to at least be able to write what libavif was able to read, without needing to re-encode seems like it would be quite useful even if its technically destructive for additional stuff in the container. Especially for the encoding case where there is no other container data than what was written by libavif this might to useful to easily be able to tweak some minor metadata things after the encode happened.

But I can understand if thats too complex to add to the current API.
