### ISSUE TITLE
"undefined reference to gzdopen" when GAIN_MAP is ON

### ISSUE THREAD

**Issue by y-guyon** [AOMediaCodec/libavif#1728]
To reproduce:

```sh
git clone https://github.com/AOMediaCodec/libavif.git && \
mkdir libavif/build && cd libavif/build && \
cmake .. \
-DAVIF_BUILD_APPS=ON \
-DBUILD_SHARED_LIBS=OFF \
-DAVIF_ENABLE_EXPERIMENTAL_GAIN_MAP=ON && \
make
```

I get:

> /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libxml2.a(xmlIO.o): in function 'xmlGzfileOpenW':
> (.text+0x2a9): undefined reference to 'gzdopen'
> ...

The building step succeeds when changing any of the three given definitions.

**Comment by maryla-uc** [comment]
https://github.com/AOMediaCodec/libavif/pull/1708 addresses this

**Comment by vrabaud** [comment]
This does not happen at head anymore
