### ISSUE TITLE
avifenc/-dec: Support folder and wildcard input

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/libavif#174]
It would be amazing if the avifenc and avifdec sample applications supported multiple inputs, including wildcard and directory inputs.

For example:

- Multiple input files (`“001.jpg 002.jpg 001.png”`)
- Wildcard input (`*.jpg` or `image*.*`)
- Directory/folder input (`path/to/Folder1`)

For output, have the option to keep the original file name with a changed extension, or rename to a number series.

**Comment by joedrago** [comment]
Sorry, I think this is out of scope for these tools. This is much better served with a script or frontend tool.
