### ISSUE TITLE
Build for Win with local libyuv fails

### ISSUE THREAD

**Issue by eddiezato** [AOMediaCodec/libavif#1765]
```
CMake Error at CMakeLists.txt:140 (message):
  libavif(AVIF_LOCAL_LIBYUV):
  D:/msys2/home/Gautama/libavif/ext/libyuv/build/libyuv.dll is missing,
  bailing out
```
I fix this in my scripts by manually setting `LIB_FILENAME` to `libyuv.a`.

**Comment by vrabaud** [comment]
Thx for reporting. Which compiler are you using ? MSVC/MINGW ? Can you please provide your command line? Thx!

**Comment by kmilos** [comment]
That's stange, as according to this:

https://github.com/AOMediaCodec/libavif/blob/b70106643236e3e59cb4cad73469336885e309ab/CMakeLists.txt#L184

and this

https://gitlab.kitware.com/cmake/cmake/-/blob/572f3105c1a011854c29d7764d5c89312c0c8932/Modules/Platform/Windows-GNU.cmake#L41

it should already be looking for `libyuv.a`?

**Comment by eddiezato** [comment]
Compiler: Clang
Environment: MSYS2 / Clang64 and UCRT64

There is a workaround for dav1d c947c7d.

**Comment by eddiezato** [comment]
@kmilos for v1.0.1
https://github.com/AOMediaCodec/libavif/blob/d1c26facaf5a8a97919ceee06814d05d10e25622/CMakeLists.txt#L138
I guess this has been fixed afterward.

**Comment by eddiezato** [comment]
Sorry, I should've checked in main. 😅
