### ISSUE TITLE
Is it possible to provide the bit depth before decoding the image?

### ISSUE THREAD

**Issue by dalecurtis** [AOMediaCodec/libavif#18]
stsd would have this information, it would also be present in the obu if one is provided for a still image. Possibly elsewhere? I'm unsure after looking over the avif spec.

This would allow us to properly configure the pipeline for half float decoding during the metadata retrieval step instead of having to decode the first frame proactively.

**Comment by joedrago** [comment]
Hmmm, the (item property) `av1C` box provides flags that would indicate this (high_bitdepth = 10bpc, twelve_bit = 12bpc), but I am currently not surfacing that up from a decode. I'll see what I can do.

**Comment by joedrago** [comment]
Alright, I took a shot at it and added `containerDepth` to the decoder. I don't return failure if I fail to find an av1C box anywhere in the BMFF, but it might be reasonable (if not really strict) to simply refuse to parse the file if `containerDepth==0`.

Note that this doesn't guarantee that this will be the depth of the first image, but you could also just fail to decode if it doesn't match the container expectations.

https://github.com/AOMediaCodec/libavif/commit/6500fd6f970ac4d0a7b27f1b9269d126b2c7aa76
