### ISSUE TITLE
AppVeyor build

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#180]
In results of AppVeyor build https://ci.appveyor.com/project/louquillio/libavif/build/artifacts I see libavif_vs2019_x64_9f2b87b6_Release.zip - archive with avif_x64_Release.lib , includes and example source.
ZIP archive has 77 KB
I don't understand why aom.lib and static libs from other dependencies (at least dav1d) aren't included.
They are needed to link final executables.
@EwoutH - What is your opinion?

**Comment by wantehchang** [comment]
Yannis: I think you removed the AppVeyor build. If so, please close this issue as obsolete. Thanks.

**Comment by y-guyon** [comment]
AppVeyor was not removed but limited to the v1.0.x branch in https://github.com/AOMediaCodec/libavif/pull/1921.  
It is planned to be replaced by GitHub release artifacts anyway.
