### ISSUE TITLE
Need avifDecoder to expose more info from the container after avifDecoderParse() returns

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#181]
I am adding AVIF decoding support to the Chromium web browser. I need avifDecoder to expose more info from the container after avifDecoderParse() returns. In the following, the variable 'decoder' points to an avifDecoder struct:

avifDecoder * decoder;

1. ICC profile. This is already available in decoder->image->icc. But it's not clear if decoder->image can be used when decoder->imageIndex is invalid (-1).

2. CICP color description, from either the colr box or the AV1 Sequence Header OBU.

3. whether the image is monochrome.

4. yuvFormat. (Or equivalently, chromaShiftX and chromaShiftY.)

5. whether the image has an alpha channel.

6. chroma_sample_position. (In issue 165 I requested that chroma_sample_position be exposed in avifImage. Now I also need it exposed after avifDecoderParse() returns.)

7. EXIF metadata.

Thank you!

**Comment by joedrago** [comment]
I've just made a commit to the `future` branch (which will be in master once rav1e v0.4 ships) which should address all of these. I've added comments to `avif.h` which make it clear which values are valid after a call to `avifDecoderParse()`, and I've added `containerChromaSamplePosition` to `avifDecoder`. To recap from your list, this is where to find the requested information after a successful call to `avifDecoderParse()` (in the following list, `decoder` is of type `avifDecoder`):

1. `decoder->image->icc`

2. `decoder->image->colorPrimaries`, `decoder->image->transferCharacteristics`, `decoder->image->matrixCoefficients`

3. `decoder->containerMonochrome`

4. `decoder->containerChromaSubsamplingX`, `decoder->containerChromaSubsamplingY`

5. `decoder->containerAlphaPresent`

6. `'decoder->containerChromaSamplePosition'`

7. `decoder->image->exif`

Check out the new comments in `avif.h` (in the `future` branch) and let me know if they make this information clear.
