### ISSUE TITLE
CMakeLists.txt: potentially confusing error message on Windows if libaom static library is missing

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#184]
In CMakeLists.txt, we have

    if(AVIF_LOCAL_AOM)
        set(LIB_FILENAME "${CMAKE_CURRENT_SOURCE_DIR}/ext/aom/build.libavif/aom.lib")
        if(NOT EXISTS "${LIB_FILENAME}")
            set(LIB_FILENAME "${CMAKE_CURRENT_SOURCE_DIR}/ext/aom/build.libavif/libaom.a")
            if(NOT EXISTS "${LIB_FILENAME}")
                message(FATAL_ERROR "libavif: ${LIB_FILENAME} is missing, bailing out")
            endif()
        endif()

The ${LIB_FILENAME} used in the error message is the last filename we tried, which is always libaom.a. So that error message will be confusing if we build libavif on Windows.

Therefore I think the original code is better:

    if(AVIF_LOCAL_AOM)
        if(WIN32)
            set(LIB_FILENAME "${CMAKE_CURRENT_SOURCE_DIR}/ext/aom/build.libavif/aom.lib")
        else()
            set(LIB_FILENAME "${CMAKE_CURRENT_SOURCE_DIR}/ext/aom/build.libavif/libaom.a")
        endif()
        if(NOT EXISTS "${LIB_FILENAME}")
            message(FATAL_ERROR "libavif: ${LIB_FILENAME} is missing, bailing out")
        endif()

It seems that we could build libaom's LIB_FILENAME from CMAKE_STATIC_LIBRARY_PREFIX and CMAKE_STATIC_LIBRARY_SUFFIX.

**Comment by wantehchang** [comment]
I will write a CL to use CMAKE_STATIC_LIBRARY_PREFIX and CMAKE_STATIC_LIBRARY_SUFFIX.

**Comment by joedrago** [comment]
If I remember correctly, I switched to this pattern because `if(WIN32)` was roping in Cygwin/MinGW in bad ways, and we were getting false positives. I'd rather change the message to not cite LIB_FILENAME and instead simply say it cannot find a locally compiled libaom library.
