### ISSUE TITLE
avifs samples with repeat count

### ISSUE THREAD

**Issue by vtorri** [AOMediaCodec/libavif#1872]
Hello

i would like to know if there are some samples of avifs images with a repeat count

thank you

**Comment by wantehchang** [comment]
Vignesh: Could you answer this question? There should be such samples in the libavif or Chrome source tree.

**Comment by novomesk** [comment]
[repetition3.zip](https://github.com/AOMediaCodec/libavif/files/13683143/repetition3.zip)

**Comment by vtorri** [comment]
@novomesk thank you

**Comment by vtorri** [comment]
@novomesk thank you
