### ISSUE TITLE
Improve YUV -> RGB Conversion

### ISSUE THREAD

**Issue by joedrago** [AOMediaCodec/libavif#189]
This is a high level tracker issue to improve conversion from YUV, in both visual quality (for subsampled images) and performance.

**Comment by vtorri** [comment]
https://chromium.googlesource.com/libyuv/libyuv/

**Comment by joedrago** [comment]
Heh, I'm quite familiar with libyuv.

I would love to switch to it, but it cannot do all of the combinations of conversion required, unfortunately. All RGB(A) paths in libyuv are only 8bpc. Maybe someday!

**Comment by tdaede** [comment]
It also only does box upsampling for chroma, which is a problem I'm trying to fix in Firefox.

**Comment by KevinJW** [comment]
There are other libraries available for such conversions e.g. https://github.com/sekrit-twc/zimg that maybe appropriate to consider, depending on the requirements

**Comment by wantehchang** [comment]
Hi Joe,

I think we can close this issue now because you have added a libyuv-based implementation and also chroma upsampling with bilinear interpolation. Further improvements probably should be contributed to libyuv.
