### ISSUE TITLE
Set lossless mode on alpha channel when encoding rav1e, when supported

### ISSUE THREAD

**Issue by joedrago** [AOMediaCodec/libavif#19]
It doesn't appear rav1e has a lossless flag on encode:

https://github.com/xiph/rav1e/issues/151

When this is added, hook up alpha encoding to always use it, and enable it when QP[0,0] is passed in for color as well.

**Comment by cryptomilk** [comment]
Well, what could be done, is that you add a codec flag SUPPORTS_LOSSLESS. And based on that flag you select the available codec if you want to use lossless.

**Comment by novomesk** [comment]
I understand that libavif always use highest quality (~lossless) for alpha channel.
However one of our users observed that HEIC uses various levels of quality also for the alpha channel, so in some circumstances HEIC achieves smaller files (lower alpha quality):
https://www.reddit.com/r/AV1/comments/fccpge/avif_alpha_compression/
Some people might believe that HEIC compress significantly better.
What do you think, would it be good to have separate Quantizer settings for the alpha channel?

**Comment by joedrago** [comment]
libavif spends 0 bytes on alpha for a fully opaque alpha channel, and I think the alpha payload on a uniform lossless alpha channel is maybe 50 bytes (top-of-head). 

My opinion is any other alpha channel (masks, gradients, vignettes, etc) are a huge mistake to encode lossy as you will see the artifacts of it in the oddest ways, but as long as the alpha QP defaults are lossless, I don't mind exposing an option to users.

**Comment by novomesk** [comment]
I agree, the default for alpha must remain lossless.
How it is going to look like?
`int maxAlphaQuantizer;`
in avifEncoder?

**Comment by joedrago** [comment]
It will probably be minQuantizerAlpha/maxQuantizerAlpha, with a big warning
of a comment above them.

**Comment by joedrago** [comment]
I added these today.

https://github.com/AOMediaCodec/libavif/commit/56fa2bc19630343fc29554afaa21b7973fe792de

**Comment by joedrago** [comment]
I decided to not leave a big comment in that the default is lossless for both color and alpha anyway, and people can decide for themselves which artifacts they want to live with.
