### ISSUE TITLE
Make test_cmd.sh run the UTF-8 tests by default

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#1903]
Vincent,

I know I asked you to switch to AVIF_TEST_UTF8=0 to skip the UTF-8 tests in test_cmd.sh. When I tried to run the test_cmd.sh script directly rather than through the ctest command, I found that this is a bad idea. Sorry!

The reason is that by default the AVIF_TEST_UTF8 environment variable is not set. So this fails our test in test_cmd.sh:

```
    if [[ "${AVIF_TEST_UTF8}" == "1" ]]; then
```

and the UTF-8 tests are not run.

I guess we should go back to what you had originally, `AVIF_TEST_NO_UTF8`. Thanks.

Note: I wonder if it would be good to rename it `AVIF_SKIP_UTF8_TESTS` to avoid double negative in the conditional expression:

```
    if [[ -z "${AVIF_TEST_NO_UTF8}" ]]; then
```

**Comment by wantehchang** [comment]
Vincent: My experiments in https://github.com/AOMediaCodec/libavif/pull/1900 showed that it is possible to support all variants of MinGW and get rid of the environment variable AVIF_TEST_UTF8. Perhaps we should try to do that?

**Comment by vrabaud** [comment]
You are right, your experiment seems to be the best solution, let's go for it!
