### ISSUE TITLE
install avifdump

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#192]
avifdump is built but not installed.
Is it possible to add it here?
https://github.com/AOMediaCodec/libavif/blob/63ad371949121cd8b3f8c5a1982637cb47923625/CMakeLists.txt#L348

**Comment by joedrago** [comment]
Hmm, I would like to offer the functionality in an installed tool, but `avifdump` is too specialized. I'm more of a mind to make something like this work:

`avifdec --dump image.avif`

... and it simply behaves as avidump does now. Thoughts?

**Comment by novomesk** [comment]
For me it is OK to have the functionality in avifdec for example.

**Comment by joedrago** [comment]
This is done. The new syntax will be:

`avifdec --info image.avif`
or 
`avifdec -i image.avif`

https://github.com/AOMediaCodec/libavif/commit/a0bc05380acf2b6da2787827e40d6d719114502f

**Comment by 1480c1** [comment]
@joedrago as a small tip for future commits, in the case a specific commit is aimed at fixing or closing a certain issue or pr, you can add `Closes #192` or `Fixes #192` to your commit message (`git commit -am "main message" -m "Closes #192"`) and github will autoclose the related issue for you when you push the commit to the default branch. This can help link both the commit and the issue between each other and can help give context on the motivation for a commit

**Comment by joedrago** [comment]
Yeah, I'm familiar with the "Fixes: " one, and I'll make an effort to use it more. I typically think of it right after I hit enter on `git push`. :-)

**Comment by 1480c1** [comment]
Yeah, I sometimes forget I made a commit to address something. If I'm lucky, I remember in time to control+c a git push and amend the commit, sometimes, I just say oh well.

Nice to know you are in the :-) camp as well :-)
