### ISSUE TITLE
Image grid decoding

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#194]
Summer_in_Tomsk_720p_5x4_grid.avif testfile stopped working.
```
avifdec -i Summer_in_Tomsk_720p_5x4_grid.avif 
ERROR: Failed to decode image: BMFF parsing failed
```

**Comment by joedrago** [comment]
Oh, interesting. This is because the "grid" item doesn't have an `av1C` property. I'll fix it.
