### ISSUE TITLE
build error with `comparison of unsigned expression < 0 is always false`

### ISSUE THREAD

**Issue by sezero** [AOMediaCodec/libavif#1943]
I hit this error when building both 1.0.x and the main branches using gcc-4.4.7.

Here's the output from a 1.0.x build:

```
cc1: warnings being treated as errors
src/avif.c: In function ‘avifImageCreate’:
src/avif.c:144: error: comparison of unsigned expression < 0 is always false

cc1: warnings being treated as errors
src/reformat.c: In function ‘avifPrepareReformatState’:
src/reformat.c:52: error: comparison of unsigned expression < 0 is always false
```

**Comment by y-guyon** [comment]
Is https://github.com/AOMediaCodec/libavif/pull/1944 enough?

What is your compiling environment?

Also feel free to set `-DAVIF_ENABLE_WERROR=OFF` when using CMake.

**Comment by sezero** [comment]
> Is #1944 enough?

That just transforms errors into `comparison of unsigned expression >= 0 is always true`

> What is your compiling environment?

gcc-4.4.7, as I had mentioned, on CentOS 6.10 (yes, EOL, I know.)
 
> Also feel free to set `-DAVIF_ENABLE_WERROR=OFF` when using CMake.

That is the workaround I am currently using

**Comment by y-guyon** [comment]
> That just transforms errors into `comparison of unsigned expression >= 0 is always true`

What about https://github.com/AOMediaCodec/libavif/pull/1945?

**Comment by sezero** [comment]
> What about #1945?

Yes, the `(int)` cast does the trick (#1925 is still in the way for me to build main branch, but the int cast solution for this particular issue works.)
