### ISSUE TITLE
`-Wignored-attributes` error with old clang

### ISSUE THREAD

**Issue by sezero** [AOMediaCodec/libavif#1947]
With clang 3.4.2, I got the following error:

```
In file included from /tmp/libavif/src/alpha.c:4:
In file included from /tmp/libavif/include/avif/internal.h:7:
/tmp/libavif/include/avif/avif.h:157:14: error: 'warn_unused_result' attribute only applies to functions, methods, and classes [-Werror,-Wignored-attributes]
typedef enum AVIF_NODISCARD avifResult
             ^
/tmp/libavif/include/avif/avif.h:57:39: note: expanded from macro 'AVIF_NODISCARD'
#define AVIF_NODISCARD __attribute__((warn_unused_result))
                                      ^
1 error generated.
```

Seems to be after https://github.com/AOMediaCodec/libavif/pull/1655

Removing `AVIF_NODISCARD` from `avifResult` enum makes the build to succeed.

**Comment by y-guyon** [comment]
Thanks for the report.

Does setting `-DAVIF_ENABLE_WERROR=OFF` solve the issue?

**Comment by sezero** [comment]
Yes, it does for build of libavif itself. (The thing is though, the public header is the offender.)

**Comment by vrabaud** [comment]
Using godbolt, I could figure out clang 3.9.0 was the first one to introduce the behavior for enums.
