### ISSUE TITLE
QQ about the test releases

### ISSUE THREAD

**Issue by chenrui333** [AOMediaCodec/libavif#2011]
👋 just found that there are test releases for the artifact generation tests, my question is are there going to be removed shortly? Thanks! 🙏 

<img width="958" alt="image" src="https://github.com/AOMediaCodec/libavif/assets/1580956/9dfea2e5-540b-4143-8f96-93a8c56e6d53">

**Comment by y-guyon** [comment]
I deleted the three temporary release placeholders, sorry about the noise.  
You can now download `avifenc.exe` and `avifdec.exe` directly from the [v1.0.4 release page](https://github.com/AOMediaCodec/libavif/releases/tag/v1.0.4). The [libavif-v1.0.4-avifenc-avifdec-windows.zip](https://github.com/AOMediaCodec/libavif/releases/download/v1.0.4/libavif-v1.0.4-avifenc-avifdec-windows.zip) archive should not be removed soon.

**Comment by chenrui333** [comment]
@y-guyon thanks for answering my concern. If all possible, can you also delete the tags as well? Cheers!

<img width="425" alt="image" src="https://github.com/AOMediaCodec/libavif/assets/1580956/4fdb39ab-ffc8-4c5a-b09c-d6270d4f46a2">

**Comment by y-guyon** [comment]
> If all possible, can you also delete the tags as well? Cheers!

Good catch, I thought deleting a release would delete the associated tag. Done, thanks!
