### ISSUE TITLE
ci-windows failure "unknown file: error: SEH exception with code 0xc000001d thrown in the test body"

### ISSUE THREAD

**Issue by y-guyon** [AOMediaCodec/libavif#2033]
Note that [ci-windows](https://github.com/y-guyon/libavif/actions/workflows/ci-windows.yml) has been failing since https://github.com/AOMediaCodec/libavif/pull/2032.

It may be unrelated to that PR because the [previous passing test](https://github.com/AOMediaCodec/libavif/actions/runs/8007780983/job/21872700753) used the cache while this PR used a [full workflow](https://github.com/AOMediaCodec/libavif/actions/runs/8007654445/job/21872284438), so it may be cache-related instead.

The errors seem consistent across across the forks of this repository:
```
unknown file: error: SEH exception with code 0xc000001d thrown in the test body.

The following tests FAILED:
	 11 - avifchangesettingtest (Failed)
	 17 - avifgainmaptest (Failed)
	 24 - aviflosslesstest (Failed)
	 39 - avify4mtest (Failed)
	 46 - test_cmd_progressive (Failed)
```

**Comment by y-guyon** [comment]
A possibly unrelated log entry is

```
Error: Svt[error]: deinit called without sending EOS!
```

**Comment by jzern** [comment]
I think that's a code for illegal instruction. Visual Studio 2022 has an issue starting at 17.8.0 which might cause AVX-512 instructions to be emitted in non-AVX-512 code. This was [labeled fixed in 17.10 Preview 1](https://developercommunity.visualstudio.com/t/Illegal-Instruction-AVX512/10511452).

**Comment by wantehchang** [comment]
Thanks for filing this bug report.

We can consider compiling libaom with clang-cl until this Visual Studio 2022 bug is fixed. I will write a pull request to try that. (I remember I wrote an experimental pull request to do this before.)

**Comment by wantehchang** [comment]
I found my experimental pull request: https://github.com/AOMediaCodec/libavif/pull/1933. It was for AppVeyor.
