### ISSUE TITLE
Question about the comment "RGB coordinate (1,2,3,4,*) in a 2x2 grid" in src/reformat.c

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#208]
Joe:

In src/reformat.c, function avifImageYUVAnyToRGBAnySlow(), we have the following comment:

                    // Upsample to 444:
                    //
                    // *   *   *   *
                    //   A       B
                    // *   1   2   *
                    //
                    // *   3   4   *
                    //   C       D
                    // *   *   *   *
                    //
                    // When converting from YUV420 to RGB, for any given "high-resolution" RGB
                    // coordinate (1,2,3,4,*) in a 2x2 grid, there are up to four "low-resolution"

I asked you about the asterisk '*' in this comment before, but when I read it again I still find it confusing. The reason is that "a 2x2 grid" implies four points, but "(1,2,3,4,*)" refers to not only 1, 2, 3, 4 but also all the asterisks '*', so there are more than four points.

**Comment by joedrago** [comment]
I'm suggesting that this is just some subsection of a larger image, in which every asterisk in this ASCII art _also_ represents a "high-resolution" coordinate. Do you have any better way of conveying that?

**Comment by wantehchang** [comment]
Thanks for the reply. In that case, the source of my misunderstanding is the "2x2 grid" in the comment. When I read that comment, I thought the "2x2 grid" refers to the four points labeled 1, 2, 3, 4.

It seems that we can eliminate this potential confusion by simply removing "in a 2x2 grid".

**Comment by joedrago** [comment]
Ah, sure. I'm on board with removing that snippet.

**Comment by joedrago** [comment]
https://github.com/AOMediaCodec/libavif/commit/277e986d1e7d80bc11d59e3406e0e46224176b03

**Comment by wantehchang** [comment]
Thank you, Joe!
