### ISSUE TITLE
Add Homebrew install instructions and avifdec/avifenc examples to README

### ISSUE THREAD

**Issue by yattoni** [AOMediaCodec/libavif#2081]
Add Homebrew install instructions and avifdec/avifenc examples to README

I had to look in the closed issues to see that this can be installed with Homebrew and find those commands just by looking through the repo.

Also, the man pages look to be disabled (not enabled) for the Homebrew install.

**Comment by wantehchang** [comment]
Austin: Thanks for the suggestion. You also reported a bug in the Homebrew install: the man pages look to be disabled (not enabled). Do you know how to report that bug to Homebrew? If you know where the Homebrew build script (recipe?) is, we can take a look. It needs to pass the `-DAVIF_BUILD_MAN_PAGES=ON` option to cmake.

**Comment by yattoni** [comment]
I believe this is it https://github.com/Homebrew/homebrew-core/blob/399309bcf5f2f93c26ef1eca1fa93bea05fd0f26/Formula/lib/libavif.rb#L27-L32

based on the link from https://formulae.brew.sh/formula/libavif#default

**Comment by wantehchang** [comment]
Austin: Thank you for the link. The formula does not pass the `-DAVIF_BUILD_MAN_PAGES=ON` option to cmake. To do that, the formula needs to depend on the pandoc package.

The formula is also not using dav1d as the AV1 decoder. It should depend on the dav1d package and pass the `-DAVIF_CODEC_DAV1D=ON` option to cmake. It can further pass the `-DAVIF_CODEC_AOM_DECODE=OFF` option to cmake to not use libaom as the AV1 decoder.

**Comment by wantehchang** [comment]
Austin: Do you know if Homebrew has a libyuv package?

**Comment by yattoni** [comment]
I don't, sorry

**Comment by kmilos** [comment]
> Do you know if Homebrew has a libyuv package?

@wantehchang Repology is your friend again 😉 https://repology.org/project/libyuv/versions

It doesn't look like it has.
