### ISSUE TITLE
autoconf etc.

### ISSUE THREAD

**Issue by themaddoctor** [AOMediaCodec/libavif#2082]
Hi,

Could you please make it possible to compile aom and libavif without cmake?
Or, alternatively, could you tell me how to build libarchive so that it passes its tests, and how to get cmake to recognize the system libuv, and any other errors that come up trying to upgrade cmake?

Thank you.

**Comment by y-guyon** [comment]
Thank you for your interest in libavif.

> Could you please make it possible to compile aom and libavif without cmake?

I will only speak about libavif here, as aom is another project.  
We believe CMake is a widespread enough build system and maintaining multiple build systems is not one of our priorities for the moment.  
Could you share more details about your use case where you cannot use CMake please?

> could you tell me how to build libarchive so that it passes its tests

Sure, here is how to build libavif:  
https://github.com/AOMediaCodec/libavif#command-lines

See the part about building all tests too:  
https://github.com/AOMediaCodec/libavif#tests

The Continuous Integration tests run by GitHub workflows also contain bash command lines. Feel free to take a look:  
https://github.com/AOMediaCodec/libavif/blob/fa5e70fabbf5a5e00106103c87a567e683aaac0f/.github/workflows/ci-unix-static.yml#L95-L116

> how to get cmake to recognize the system libuv

(assuming you are talking about building libavif and linking to the system-installed `libyuv`)  
This should be the default behavior, corresponding to the CMake flag `-DAVIF_LIBYUV=SYSTEM`. What is your build environment (OS etc.)?

> any other errors that come up trying to upgrade cmake

Not sure what you meant here.
