### ISSUE TITLE
src/reformat.c: in avifImageYUVAnyToRGBAnySlow(), the conditions for duplicating the sample are not exact

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#209]
In src/reformat.c, function avifImageYUVAnyToRGBAnySlow(), we have the following code:

                    int uAdjCol, vAdjCol, uAdjRow, vAdjRow;
                    if ((uvI == 0) || (uvI == uvIMax)) {
                        uAdjCol = 0;
                        vAdjCol = 0;
                    } else {
                        if ((i % 2) != 0) {
                            uAdjCol = yuvChannelBytes;
                            vAdjCol = yuvChannelBytes;
                        } else {
                            uAdjCol = -1 * yuvChannelBytes;
                            vAdjCol = -1 * yuvChannelBytes;
                        }
                    }

The condition under which we set uAdjCol and vAdjCol to 0 is not exact. For example, uvI == 0 is equivalent to i == 0 || i == 1. But if image->width > 2, i == 1 has an adjacent column and therefore we do not need to duplicate the sample. The condition uvI == uvIMax has a similar problem, although it is more complicated to analyze.

I think the fix is something like this:

                    if ((i == 0) || (i == image->width - 1 && (i % 2) != 0)) {
                        uAdjCol = 0;
                        vAdjCol = 0;
                    } else {
                        ...
                    }

The following code for setting uAdjRow and vAdjRow has the same problem:

                    if ((uvJ == 0) || (uvJ == uvJMax) || (image->yuvFormat == AVIF_PIXEL_FORMAT_YUV422)) {
                        uAdjRow = 0;
                        vAdjRow = 0;
                    } else {
                        if ((j % 2) != 0) {
                            uAdjRow = (int)uRowBytes;
                            vAdjRow = (int)vRowBytes;
                        } else {
                            uAdjRow = -1 * (int)uRowBytes;
                            vAdjRow = -1 * (int)vRowBytes;
                        }
                    }

**Comment by joedrago** [comment]
Hmm, I think you're right, and your suggested conditional might be right. Let me think about it.

**Comment by joedrago** [comment]
I don't think the modulus check is necessary. It might just be as simple as replacing the uvI/uvJ bounds checks for i/j full image bounds checks.

**Comment by wantehchang** [comment]
If image->width is an odd number, then a pixel on the right border (i == image->width - 1) has the adjacent-col sample to its left, which is within the image's bounds (see note below). This is only problematic if image->width is an even number, hence the modulus check of 'i'.

NOTE: A special case is image->width is 1. Then i == 0 is on both the left and right borders, and its adjacent-col sample is ambiguous. However, we know AdjCol should be 0 in this case, so the change I proposed handles this case correctly.
