### ISSUE TITLE
[rav1e] Expose the speed setting

### ISSUE THREAD

**Issue by AurelC2G** [AOMediaCodec/libavif#21]
The rav1e encoder has a speed setting (an integer between 0 and 10, defaults to 6) that significantly impacts encoding speed and quality. Right now there is no way to set this when using rav1e via libavif, it just uses the default value. We should expose a new speed parameter (similar to how we expose the `maxThreads`).

**Comment by joedrago** [comment]
It looks like that 0-10 speed is shorthand for these settings:

https://github.com/xiph/rav1e/blob/master/src/api/config.rs#L334

I don't want to prematurely just jam in a 0-10 "speed" dial on avifEncoder that only works on rav1e, if there is a better way to expose these features, or if there is a way to simulate these same 0-10 values in libaom (and/or SVT in the future, etc). 

I'm on board with such a feature, I just want to make sure the values in avifEncoder make sense to more than one codec, if I can help it.

**Comment by AurelC2G** [comment]
Makes sense, though it may be tough to generalize these settings, as different encoders may implement different sets of optimizations. How about having a simple proxy for this in `avifEncoder`, for example a `speed` integer between 0 and N, and then map that setting in different ways for different encoders?

For example, for rav1e we would just map `avifEncoder->speed` (in [0-N]) to rav1e's speed setting (in [0-10]), while for other encoders we could use a different strategy (enabling or disabling some features based on the `speed` value).

This is pretty much already what we do for `quantizer`: we have a quantizer setting in libavif in the range [0-63], which then gets mapped differently depending on the codec (for instance, we map that to [0-255] for rav1e).

**Comment by joedrago** [comment]
Alright, I talked with the libaom team, and this is pretty close to how it'll operate in the next version:

https://github.com/AOMediaCodec/libavif/commit/4bf0187b317ac27483d2623bb4b6f43277c3a304

I might tweak the libaom speed implementation next week at some point, but this API is pretty friendly and reasonable. Thanks for the suggestion; I think it is a winner.
