### ISSUE TITLE
[Function Request] avifenc supports svt and rav1e encoder options key-value

### ISSUE THREAD

**Issue by sommio** [AOMediaCodec/libavif#2108]
Right now `avifenc` only supports aom's encoder options, and I'm hoping that the faster encoding svt and rav1e will be able to use it as well. Thanks!

**Comment by vrabaud** [comment]
Hi, indeed, it was not added. It seems easy for SVT through `svt_av1_enc_set_parameter` ( https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Source/API/EbSvtAv1Enc.h?ref_type=heads#L973) and `rav1e_config_parse_int` for rav1e. I'll look into it.
BTW, we are always looking for benchmark data, where di you find those speed results? Thx!

**Comment by sommio** [comment]
benchmark: https://www.reddit.com/r/AV1/comments/i4xdv6/av1_encoders_comparison/
