### ISSUE TITLE
Static build issues on MSYS2

### ISSUE THREAD

**Issue by JacobDev1** [AOMediaCodec/libavif#2125]
Is it possible to statically compile `libavif` on MSYS2? The resulting EXEs return `libwinpthread-1.dll` error when I run them. 
![avifenc_dll_error](https://github.com/AOMediaCodec/libavif/assets/65915437/6fb446e7-ed6b-43f1-9f02-caf333abf0ba)

Could you please write a comprehensive guide on compiling this library? It took me many hours just to get this far (cmake issues).

I used MSYS2 MINGW64 on Windows 10

```bash
pacman -Sy
pacman -Su
pacman -S mingw-w64-x86_64-ninja mingw-w64-x86_64-cmake mingw-w64-x86_64-toolchain git make nasm

git clone -b v1.0.4 --depth 1 https://github.com/AOMediaCodec/libavif.git
cd libavif/ext

./aom.cmd
./libyuv.cmd
./libsharpyuv.cmd
./libjpeg.cmd
./zlibpng.cmd

cd ..
mkdir build
cd build
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=0 -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DAVIF_BUILD_APPS=1 -DAVIF_LOCAL_LIBYUV=1 -DAVIF_LOCAL_LIBSHARPYUV=1 -DAVIF_LOCAL_JPEG=1 -DAVIF_LOCAL_ZLIBPNG=1 ..
make
```

Note: MSYS2 CLANG64 and UCRT64 fail during build. I only got it partially working in MINGW64.

Thanks in advance for your time.

**Comment by jzern** [comment]
Your current build should work if you copy the dll (and any others that are listed as missing) from /mingw64/bin to the directory containing avifenc.exe. Another option is to add the path to the directory containing the dll to your PATH environment variable, though this can cause some unexpected behavior depending on the tools you normally use.

Getting a static build together should be possible, but will be more work.

**Comment by JacobDev1** [comment]
Thank you for the answer.

Appending the DLL files should suffice for my use case. However, If you know how to build a fully static EXE, I'd love to hear about it.

**Comment by jzern** [comment]
> However, If you know how to build a fully static EXE, I'd love to hear about it.

It usually involves working `-static`, `-static-libgcc` and possibly `-static-libstdc++` into the build and link flags using `-DCMAKE_C_FLAGS` and related.

Mostly static builds can also be achieved with `-Wl,-static <libs to link statically> -Wl,-Bdynamic`.

**Comment by kmilos** [comment]
> MSYS2 CLANG64 and UCRT64 fail during build.

There is no problem building these: https://packages.msys2.org/base/mingw-w64-libavif

However, the MSYS2 packages are not using the bundled dependences, but shared MSYS2 ones.
