### ISSUE TITLE
sharpyuv conversion failed

### ISSUE THREAD

**Issue by sommio** [AOMediaCodec/libavif#2128]
- Arch Linux
- [libavif-git 1.0.0.r474.gca071c4d-1 (via AUR)](https://aur.archlinux.org/packages/libavif-git)

```
❯ avifenc -y 420 -d 10 --sharpyuv -c svt 101481975_p0.png out.avif
Conversion to YUV failed: 101481975_p0.png
Cannot read input file: 101481975_p0.png
```
Many thanks to Vrabaud for recently adding exciting svt/rav1e encoder option support.
Since `svt` only supports `yuv420` I wanted the best possible chroma subsampling, but unfortunately `--sharpyuv` is now unavailable.

Sample FIle:
![my-waifu](https://github.com/AOMediaCodec/libavif/assets/64189793/35176424-4b35-489c-82e8-a956d0e934e0)

**Comment by jzern** [comment]
I think this is an issue with the package in Arch Linux. It looks to be dated and doesn't have a dependency on libsharpyuv.

Building avifenc from source using `-DAVIF_CODEC_SVT=LOCAL -DAVIF_LIBYUV=LOCAL -DAVIF_LIBSHARPYUV=LOCAL -DAVIF_JPEG=LOCAL -DAVIF_ZLIBPNG=LOCAL -DAVIF_BUILD_APPS=ON` should work.

**Comment by sommio** [comment]
Works for me, thanks.
