### ISSUE TITLE
Add -tune option

### ISSUE THREAD

**Issue by Uch1haOb1to** [AOMediaCodec/libavif#217]
Visually, `-tune ssim` in libaom gives better quality than the default. I compared the frame received in libaom with the frame from
libavif, they are approximately the same with equal size, but if you use `-tune ssim` in libaom, then the quality is noticeably better.

**Comment by joedrago** [comment]
@wantehchang and I were recently discussing codec specific options, and how to offer them in my API. I will bring it up with him again tomorrow and see if I can find a good way to do this.

**Comment by Uch1haOb1to** [comment]
I’ll also add that for noisy photos it would be nice to have a noise filter like in libaom, which removes noise and then generates it.
Noisy photos, for example, from a Google camera with noise reduction turned off.
I compressed the photo 4 times, also compressed the same in Photoshop and I would not say that ssim is a big win in favor of avif.
orig [https://drive.google.com/file/d/1ffA7KeEt_1NPPE99pJIX-BcgqVD0rL5a/view?usp=sharing](url)
jpeg [https://drive.google.com/file/d/1Xh34LIwIT_6_XBE4E5flNZ5mkrkKAIj-/view?usp=sharing](url)
avif [https://drive.google.com/file/d/1D0GzwVvLTqKOrU69iLjAZfOIsMCiSNTM/view?usp=sharing](url)
avif with `-j 4 -y 420 -r full -s 1`, I don’t remember the quality anymore, I selected it so that the size was 4 times smaller than the original
ffmpeg ssim
jpeg `SSIM Y:0.938718 (12.126704) U:0.959499 (13.925375) V:0.959101 (13.882865) All:0.945579 (12.642336)`
avif `SSIM Y:0.946353 (12.704542) U:0.962295 (14.236041) V:0.961743 (14.172845) All:0.951575 (13.149299)`
According to my tests, with the settings that avif now has, it gives a tangible win in pictures without noise and with a small amount of detail, such as anime art.

**Comment by joedrago** [comment]
Noise synthesis is being discussed at the codec level in AOM mailing lists, but is out of scope specifically for the AVIF container layer (this repo is about the container format). It is best to join the `av1-discuss` mailing list and bring this up there:

https://groups.google.com/a/aomedia.org/forum/#!forum/av1-discuss
