### ISSUE TITLE
v1.1.0 fails with system googletest

### ISSUE THREAD

**Issue by jbeich** [AOMediaCodec/libavif#2258]
Regressed by #2097. Affects downstream packaging where bundled libraries are discouraged e.g., on [FreeBSD](https://docs.freebsd.org/en/books/porters-handbook/bundled-libs.html).

```cmake
$ cmake -DAVIF_CODEC_AOM=SYSTEM -DAVIF_LIBYUV=OFF -DAVIF_GTEST=SYSTEM -DAVIF_BUILD_TESTS=ON -B /tmp/libavif_build
-- libavif: Enabling warnings for Clang
-- libavif: Codec enabled: aom (encode/decode)
-- The CXX compiler identification is Clang 18.1.6
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/libz.so (found version "1.3.1")
-- Found PNG: /usr/local/lib/libpng.so (found suitable version "1.6.43", minimum required is "1.6.32")
-- Found JPEG: /usr/local/lib/libjpeg.so (found version "80")
CMake Error at CMakeLists.txt:202 (find_package):
  By not providing "FindGoogletest.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Googletest", but CMake did not find one.

  Could not find a package configuration file provided by "Googletest" with
  any of the following names:

    GoogletestConfig.cmake
    googletest-config.cmake

  Add the installation prefix of "Googletest" to CMAKE_PREFIX_PATH or set
  "Googletest_DIR" to a directory containing one of the above files.  If
  "Googletest" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  tests/CMakeLists.txt:90 (check_avif_option)


-- Configuring incomplete, errors occurred!
```

**Comment by vrabaud** [comment]
Thx for the report. libavif is packaged with its tests on FreeBSD ? What is the content of the googletest package on FreeBSD? If it is like Ubuntu, it is probably just source based (cf https://packages.ubuntu.com/focal/all/googletest/filelist and https://www.eriksmistad.no/getting-started-with-google-test-on-ubuntu/).

**Comment by wantehchang** [comment]
Jan: With the `-DAVIF_GTEST=SYSTEM` cmake option, libavif looks for GoogleTest installed on the system. Is there a GoogleTest package in FreeBSD?

In https://github.com/AOMediaCodec/libavif/pull/2097/files#diff-4461c617ceae0c7e0206622aacdf555aedd62eb129c2efb74c84fa1567bcbe0d, we changed from `find_package(GTest REQUIRED)` to looking for a package named `Googletest`. Is that the source of the problem?

**Comment by jbeich** [comment]
According to [FreeBSD package file list](https://github.com/freebsd/freebsd-ports/blob/main/devel/googletest/pkg-plist) it should be possible to find GoogleTest via CMake (e.g., `find_package(GTest)`) or pkg-config (e.g., `pkg_check_modules(GTEST gtest)`).

**Comment by jbeich** [comment]
> https://packages.ubuntu.com/focal/all/googletest/filelist

Ubuntu Focal has ancient googeltest 1.10.0 (released on 2019-10-03). On FreeBSD googletest is the latest 1.14.0 (released on 2023-08-02).

**Comment by jbeich** [comment]
I have no clue how Ubuntu managed to screw up packaging. For googletest 1.10.0 on FreeBSD see https://github.com/freebsd/freebsd-ports/blob/fbea4307e854/devel/googletest/pkg-plist It did support CMake/pkg-config even back then.

**Comment by jbeich** [comment]
> looking for a package named `Googletest`

Yes, such CMake/pkg-config name doesn't exist at least on BSDs (DragonFly, FreeBSD, NetBSD, OpenBSD). I haven't checked various Linux distros (via [Repology](https://repology.org/project/gtest/packages) to find recipes) as some generate file list automatically. Finding affected that also hook libavif tests is time-consuming.

**Comment by vrabaud** [comment]
`GTest` is the way to name it, cf https://cmake.org/cmake/help/latest/module/FindGTest.html#findgtest
We probably got confused with https://cmake.org/cmake/help/latest/module/GoogleTest.html
Also, `Gtest::gtest` is a modern convention, that appeared in CMake 3.20, cf https://cmake.org/cmake/help/v3.20/module/FindGTest.html#findgtest. The old one should be used for broader support (it is also still supported): `GTest::GTest`.

@jbeich , can you please test https://github.com/AOMediaCodec/libavif/pull/2263 to see if it works for you? Thx.

**Comment by jbeich** [comment]
@vrabaud, I confirm, #2263 fixes tests build in FreeBSD package.
