### ISSUE TITLE
Refactor --lossless cmdline handling in avifenc

### ISSUE THREAD

**Issue by joedrago** [AOMediaCodec/libavif#226]
Related to #157 

The flow for `--lossless` and subsequent warnings has gotten too complicated and fragile, and needs a refactor.

I think the primary issue here is that there are too many ways to derive the requested output settings:

* Defaults prior to argument parsing
* Argument parsing
* First image's format (especially Y4M files)
* Secondary images' format (especially Y4M files)
* Codec limitations (monochrome)

The refactor should account for all of this. It should track what the user explicitly asked for via the commandline, override anything that conflicts with the input image data (warning appropriately), and falling back to defaults (also warning if necessary, but in potentially different ways).

**Comment by vrabaud** [comment]
I believe all those cases have now been implemented for lossless with appropriate tests.
