### ISSUE TITLE
Regenerate test files for DecodeGainMapGrid, DecodeColorGridGainMapNoGrid, DecodeColorNoGridGainMapGrid

### ISSUE THREAD

**Issue by ccameron-chromium** [AOMediaCodec/libavif#2261]
These test files need to be updated to the new ISO 21496-1 metadata. The branch [referenced](https://source.chromium.org/chromium/chromium/src/+/main:third_party/libavif/src/tests/data/README.md;l=493;drc=3408ce685293d8c1fed9656a460cef78f105b92d) in the README is out of date and will need to be rebased.

**Comment by gregbenz** [comment]
Is it just the test images that are outdated? Are the encode / decode capabilities under AVIF_ENABLE_EXPERIMENTAL_GAIN_MAP compliant with ISO 21496-1? References in the code base appear to be largely from last year.

**Comment by wantehchang** [comment]
Hi Greg,

There is a pending pull request to update the code: https://github.com/AOMediaCodec/libavif/pull/2235

**Comment by gregbenz** [comment]
@wantehchang Thanks!
