### ISSUE TITLE
In CMakeLists.txt, AVIF_ENABLE_NODISCARD probably should set CMAKE_CXX_STANDARD to 17

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#2276]
In CMakeLists.txt, `AVIF_ENABLE_NODISCARD` sets `CMAKE_C_STANDARD` to 23:

```
if(AVIF_ENABLE_NODISCARD)
    if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.21.0)
        set(CMAKE_C_STANDARD 23)                  
        set_property(TARGET avif_obj PROPERTY C_STANDARD 23)
    else()
```

It probably should also set `CMAKE_CXX_STANDARD` to 17, because the `nodiscard` attribute was added in C++17:
https://en.cppreference.com/w/cpp/language/attributes/nodiscard

Note: GCC 13.2.0 and Clang 16.0.6 support `[[nodiscard]]` when the `-std=gnu++14` flag is used. I guess `[[nodiscard]]` is considered a GNU extension in C++14 mode.

**Comment by vrabaud** [comment]
Let's not try to figure out the right flags with which version. Let's stick to C++17, it is easier.
