### ISSUE TITLE
[discussion] no check when avifAlloc() is used

### ISSUE THREAD

**Issue by vtorri** [AOMediaCodec/libavif#230]
hello

is it normal that no check is done when memory allocation is done with avifAlloc() (malloc() actually) ?

**Comment by 1480c1** [comment]
https://github.com/AOMediaCodec/libavif/blob/master/src/mem.c#L11

the check is done inside `avifAlloc` for now

**Comment by vtorri** [comment]
i'm not fond of abort in a lib, but if it's the way you deal with memory, ok

**Comment by 1480c1** [comment]
https://github.com/AOMediaCodec/libavif/issues/103

original discussion, it was put there because there were no checks previously, so a null pointer deref was possible.

**Comment by vtorri** [comment]
ok, closing then, thank you
