### ISSUE TITLE
Grid image arranges tiles in wrong order if IDs in the `iref` are not sequential

### ISSUE THREAD

**Issue by farindk** [AOMediaCodec/libavif#2311]
libavif apparently assumes that the tile IDs of a grid image are sequential. If that is not the case, the tiles are composed into the output image in an incorrect arrangement.

Here is an [example image](https://cloud.dirk-farin.de/s/8nW38ym2DQjHBdt) that is decoded by libavif like this:

![image](https://github.com/user-attachments/assets/d5215bff-6c15-458f-835f-5ed47ae764ec)

**Comment by y-guyon** [comment]
> libavif apparently assumes that the tile IDs of a grid image are sequential. If that is not the case, the tiles are composed into the output image in an incorrect arrangement.

The tile IDs should not matter at all. HEIF spec ISO/IEC 23008-12 says:

```
The input images are inserted in row-major order, top-row first, left to right, in the order of
SingleItemTypeReferenceBox of type 'dimg' for this derived image item within the ItemReferenceBox. 
```

However libavif does not respect that pattern as of today (libavif is used in Chrome for example):
![2345 avif](https://github.com/user-attachments/assets/45342ea8-eaba-41f3-941c-208635454d4b)

![5432 avif](https://github.com/user-attachments/assets/0c31f46f-12e8-49d7-9839-e67a6a512efe)

**Comment by y-guyon** [comment]
Not sure what GIMP 2.10.36 uses under the hood but it opens the out-of-order `dimg` association file correctly.

**Comment by y-guyon** [comment]
(Thank you for taking the time to report this issue by the way.)

**Comment by wantehchang** [comment]
To test the fix for this issue, we also need an image grid in which multiple grid tiles reference the same image item. (In the extreme case, all grid tiles reference the same image item.)

@farindk Dirk: do yo happen to have such an image available?

**Comment by y-guyon** [comment]
> To test the fix for this issue, we also need an image grid in which multiple grid tiles reference the same image item. (In the extreme case, all grid tiles reference the same image item.)

I manually edited
https://github.com/AOMediaCodec/libavif/blob/676a6cb82c0261cf5474c086f8e94f0f65ad4645/tests/data/sofa_grid1x5_420.avif
to repeat the same tile twice in `dimg`:
![sofa_grid1x5_420_dimg_repeat avif](https://github.com/user-attachments/assets/98fb5c42-0ad0-4243-a2cd-3eafd8ea50c1)

The image does not work in Chrome (libavif).  
However it does not work in GIMP (libheif) either:  
```
Opening '/home/yguyon/Downloads/sofa_grid1x5_420_dimg_repeat.avif' failed:
Loading HEIF image failed: Invalid input: Unspecified: 'iref' has double references
```

Which is compliant with the ISOBMFF specification ISO/IEC 14496-12:

```
8.11.12.1 Definition
The items linked to are then represented by an array of to_item_IDs;
within a given array, a given value shall occur at most once.
```

A workaround would be an intermediate `iden` derived image item (which is also unsupported by libavif).

Anyway I believe this is a different issue than https://github.com/AOMediaCodec/libavif/issues/2311.

**Comment by wantehchang** [comment]
Yannis: That's good news. I was mislead by the incorrect comment in libavif. Thank you for finding proof that this is not compliant with ISOBMFF.
