### ISSUE TITLE
Seemingly uncommon use of $<BUILD_INTERFACE> generator expressions in target_compile_options()

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#2323]
In the top-level CMakeLists.txt file, `$<BUILD_INTERFACE>` generator expressions are used in several `target_compile_options()` calls, e.g., to set the compiler warning options on the `avif_obj` OBJECT library:

```
# Enable all warnings
include(CheckCCompilerFlag)
if(MSVC)
    message(STATUS "libavif: Enabling warnings for MSVC")
    target_compile_options(
        avif_obj
        PUBLIC $<BUILD_INTERFACE: /W4 # For clang-cl, /W4 enables -Wall and -Wextra 
               /wd4324 # Disable: structure was padded due to alignment specifier       
               >
    )
    ...
elseif(CMAKE_C_COMPILER_ID MATCHES "Clang")
    message(STATUS "libavif: Enabling warnings for Clang")
    target_compile_options(avif_obj PUBLIC $<BUILD_INTERFACE:-Wall -Wextra -Wshorten-64-to-32>)
elseif(CMAKE_C_COMPILER_ID MATCHES "GNU")
    message(STATUS "libavif: Enabling warnings for GCC")
    target_compile_options(avif_obj PUBLIC $<BUILD_INTERFACE:-Wall -Wextra>)
else()
    message(FATAL_ERROR "libavif: Unknown compiler, bailing out")
endif()
```

I am not an advanced CMake user, but based on my searches in CMake documentation, the `$<BUILD_INTERFACE>` generator expression is mainly used in `target_include_directories()` and `target_link_libraries()` calls, and it is often used in conjunction with the  `$<INSTALL_INTERFACE>` generator expression. So the way we use it in `target_compile_options()` calls seems uncommon.

@vrabaud @fdintino I guess it was one of you who wrote this code. Could you explain why you wrote it that way, and whether it is possible to replace it with "basic" CMake code. For example, can we change

```
    target_compile_options(avif_obj PUBLIC $<BUILD_INTERFACE:-Wall -Wextra -Wshorten-64-to-32>)
```

to

```
    target_compile_options(avif_obj PUBLIC -Wall -Wextra -Wshorten-64-to-32)
```

?

**Comment by vrabaud** [comment]
This is to only use those flags during build, and not export them when another project uses that lib.
Otherwise, they end up being used when another lib, outside of libavif uses it.

You have an example of that at the bottom of: https://cmake.org/cmake/help/latest/guide/tutorial/Adding%20Generator%20Expressions.html (TODO 4)

**Comment by wantehchang** [comment]
Vincent: Thank you for the reply. That answered my question.

Note: I think we can achive the same goal without using the `$<BUILD_INTERFACE>` generator expressions by adding those compiler options in the `PRIVATE` scope in `target_compile_options()` calls.
