### ISSUE TITLE
Consider enabling compiler warnings in add_avif_fuzztest() in tests/CMakeLists.txt

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#2350]
@jzern @vrabaud @y-guyon 

In https://github.com/AOMediaCodec/libavif/pull/2344 I enabled compiler warnings in the tests/ directory, but I had to exclude the `add_avif_fuzztest()` macro because there are compiler warnings in the FuzzTest and Abseil headers.

It would be good to look into whether it is possible to enable compiler warnings in `add_avif_fuzztest()`, e.g., by turning off the warnings in the FuzzTest and Abseil headers.

I am surprised that Abseil headers have compiler warnings when compiled with `-Wall -Wextra`. The [Abseil Compiler Flags](https://abseil.io/docs/cpp/platforms/compilerflags#abseil-warning-flags) page says they compile with `-Wall -Wextra` under GCC but turn off `-Wsign-compare` (which is one of the warnings I saw). So we can first suppress the compiler warnings in Abseil headers under the guidance of the Abseil Compiler Flags page, and then see what we need to do with the compiler warnings in FuzzTest headers.

**Comment by vrabaud** [comment]
In CMake 3.25 and above, we can add the SYSTEM property to the add_subdirectory of the fuzztest folder. fuzztest only recommends to use an add_subdirectory but we could try to FetchContent it as imported targets are SYSTEM I believe.

**Comment by wantehchang** [comment]
We ignore the compiler warnings when FuzzTest itself is compiled. This issue is about the compiler warnings when our fuzztest source files are compiled (because they include FuzzTest headers).

**Comment by wantehchang** [comment]
Vincent: I misunderstood your comment. Sorry. I think adding the SYSTEM property to the add_subdirectory() call of the fuzztest folder is a good solution. Thanks for the suggestion. I am testing it in https://github.com/AOMediaCodec/libavif/pull/2356.
