### ISSUE TITLE
avifenc, avifdec and avifutil can notcompile with mingw-w64: %z unknown

### ISSUE THREAD

**Issue by vtorri** [AOMediaCodec/libavif#240]
with mingw-w64, %z is unknown, and %i should be used instead : 

https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2019

all versions of Visual Studio support %I, only some recent Visual Studio support also %z

see #239

**Comment by 1480c1** [comment]
@joedrago I think this can be closed now
