### ISSUE TITLE
Can you release a new version for android

### ISSUE THREAD

**Issue by wzes** [AOMediaCodec/libavif#2401]
The latest version is [1.0.1.262e11d](https://mvnrepository.com/artifact/org.aomedia.avif.android/avif/1.0.1.262e11d)
Can you release a new version based on the main branch?

**Comment by vigneshvg** [comment]
Done. Version [1.1.1.14d8e3c4](https://repo1.maven.org/maven2/org/aomedia/avif/android/avif/1.1.1.14d8e3c4/) is now available on maven central.
