### ISSUE TITLE
Failed to build libavif with Clang GNU driver on Windows

### ISSUE THREAD

**Issue by AlifianK** [AOMediaCodec/libavif#2442]
Failed to build libavif with Clang GNU driver on WIndows, MSVC and clang-cl are not affected.
```
cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS='-flto=full -march=native' -DCMAKE_CXX_FLAGS='-flto=full -march=native' -DCMAKE_BUILD_TYPE=Release -DAVIF_CODEC_DAV1D=LOCAL -DAVIF_LIBYUV=LOCAL -DAVIF_LIBSHARPYUV=LOCAL -DAVIF_JPEG=LOCAL -DAVIF_ZLIBPNG=LOCAL -DAVIF_CODEC_AOM=LOCAL -DAVIF_BUILD_APPS=ON ..
```
```
-- The C compiler identification is Clang 19.1.0 with GNU-like command-line
...
[83/84] Linking CXX executable avifenc.exe
FAILED: avifenc.exe
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE -nostartfiles -nostdlib -flto=full -march=native -O3 -DNDEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrt -Xlinker /subsystem:console   /MANIFEST:NO -fuse-ld=lld-link CMakeFiles/avifenc.dir/apps/avifenc.c.obj CMakeFiles/avifenc.dir/apps/utf8.rc.res -o avifenc.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:avifenc.lib -Xlinker /pdb:avifenc.pdb -Xlinker /version:0.0   avif_apps.lib  avif.lib  _deps/libpng/libpng16_static.lib  _deps/zlib/zlibstatic.lib  D:/dev/libavif/ext/libjpeg-turbo/build.libavif/jpeg.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames  && C:\WINDOWS\system32\cmd.exe /C "cd /D D:\dev\libavif\builddyn && "C:\Program Files\PowerShell\7-preview\pwsh.exe" -noprofile -executionpolicy Bypass -file C:/Users/Alifian/scoop/apps/vcpkg/current/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/dev/libavif/builddyn/avifenc.exe -installedDir C:/Users/Alifian/scoop/apps/vcpkg/current/installed/x64-win-llvm-lto-static-rel/bin -OutVariable out""
clang++: error: no such file or directory: '/MANIFEST:NO'
```

**Comment by wantehchang** [comment]
@AlifianK Thanks for the bug report. This is a bug in libavif/CMakeLists.txt. It should not be hard to fix.

The `/MANIFEST:NO` option is set in libavif/CMakeLists.txt:

```
    if(WIN32)
        # MinGW doesn't have a manifest tool (mt.exe), so we need to wrap
        # utf8.manifest in a resource-definition script (.rc file).
        target_sources(avifenc PRIVATE apps/utf8.rc)
        # The MSVC linker (link.exe) fails with the following error if we
        # don't use the /MANIFEST:NO linker option:
        #   /MANIFEST:EMBED,ID=1" failed (exit code 1123) with the following
        #   output:
        #   CVTRES : fatal error CVT1100: duplicate resource.  type:MANIFEST,
        #   name:1, language:0x0409
        if(NOT MINGW)
            target_link_options(avifenc PRIVATE /MANIFEST:NO)
        endif()
    endif()
```

So we need to refine the condition `if(NOT MINGW)`. @jzern James: any suggestions? Maybe checking both [CMAKE_C_COMPILER_ID](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html#variable:CMAKE_%3CLANG%3E_COMPILER_ID) and [CMAKE_C_COMPILER_FRONTEND_VARIANT](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_FRONTEND_VARIANT.html)?

**Comment by jzern** [comment]
> So we need to refine the condition `if(NOT MINGW)`. @jzern James: any suggestions? Maybe checking both [CMAKE_C_COMPILER_ID](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html#variable:CMAKE_%3CLANG%3E_COMPILER_ID) and [CMAKE_C_COMPILER_FRONTEND_VARIANT](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_FRONTEND_VARIANT.html)?

I wonder if `MSVC` will be enough here.

**Comment by wantehchang** [comment]
You are right. Let me try `MSVC` first.

**Comment by wantehchang** [comment]
@AlifianK Could you please test the patch in https://github.com/AOMediaCodec/libavif/pull/2443/files? Thanks!

**Comment by AlifianK** [comment]
It fails with duplicate resource error instead

```
FAILED: avifenc.exe
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE -nostartfiles -nostdlib -flto=full -march=native -O3 -DNDEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrt -Xlinker /subsystem:console   -fuse-ld=lld-link CMakeFiles/avifenc.dir/apps/avifenc.c.obj CMakeFiles/avifenc.dir/apps/utf8.rc.res -o avifenc.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:avifenc.lib -Xlinker /pdb:avifenc.pdb -Xlinker /version:0.0   avif_apps.lib  avif.lib  _deps/libpng/libpng16_static.lib  _deps/zlib/zlibstatic.lib  D:/dev/libavif/ext/libjpeg-turbo/build.libavif/jpeg.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames  && cd ."
lld-link: error: duplicate resource: type MANIFEST (ID 24)/name ID 1/language 1033, in CMakeFiles/avifenc.dir/apps/utf8.rc.res and in avifenc.exe.manifest.res
```
I think Clang-GNU still needs to have `/MANIFEST:NO` just like MSVC and Clang-MSVC, I've tested it by manually copying and editing the failed command and it builds properly. But the problem are:
- As said in this issue, instead of `-Xlinker /subsystem:console -Xlinker /MANIFEST:NO   -fuse-ld=lld-link`, it became `-Xlinker /subsystem:console   /MANIFEST:NO -fuse-ld=lld-link` instead and it incorrectly treated as a path.
- Even if we correctly set the `target_link_options` in `CMakeLists.txt` with this:
```
if(NOT MINGW)
    if(CMAKE_C_COMPILER_ID STREQUAL "Clang" AND CMAKE_C_COMPILER_FRONTEND_VARIANT STREQUAL "GNU")
        target_link_options(avifenc PRIVATE LINKER:/MANIFEST:NO)
    else()
        target_link_options(avifenc PRIVATE /MANIFEST:NO)
endif()
```
And the resulting command is this:
```
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE -nostartfiles -nostdlib -flto=full -march=native -O3 -DNDEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrt -Xlinker /subsystem:console   -Xlinker /MANIFEST:NO -fuse-ld=lld-link CMakeFiles/avifenc.dir/apps/avifenc.c.obj CMakeFiles/avifenc.dir/apps/utf8.rc.res -o avifenc.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:avifenc.lib -Xlinker /pdb:avifenc.pdb -Xlinker /version:0.0   avif_apps.lib  avif.lib  _deps/libpng/libpng16_static.lib  _deps/zlib/zlibstatic.lib  D:/dev/libavif/ext/libjpeg-turbo/build.libavif/jpeg.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames  && cd ."
```
Notice how `-Xlinker /MANIFEST:NO` is still in front of `-Xlinker /MANIFEST:EMBED`, therefore overwritten by it, and still fails. So the solution would be overwriting `/MANIFEST:EMBED` or putting `/MANIFEST:NO` behind it, but I don't know how to do that. Any suggestions?

**Comment by AlifianK** [comment]
I'm using MSVC toolchain with clang, if you specify just `clang` instead of `clang-cl`, CMake will detect the GNU frontend, or maybe you could call it as driver.

> I'd prefer the working case mentioned is not "corrected" like this.

I think it's just a pretty niche thing with the combination of MSVC+Clang+GNU command handling manifest linking, I have no problem if this issue is closed as I usually build libavif with `clang-cl` anyway.

**Comment by AlifianK** [comment]
Filed an upstream issue https://gitlab.kitware.com/cmake/cmake/-/issues/26328

**Comment by bradking** [comment]
For toolchains targeting the MSVC ABI, CMake has first-class support for embedding manifests.  Just list `utf8.manifest` as a normal source file.  Manual embedding through a `.rc` source is needed only when targeting the GNU ABI on Windows (MinGW) since CMake doesn't have first-class support ([CMake Issue 23244](https://gitlab.kitware.com/cmake/cmake/-/issues/23244)).  I suggest

```cmake
if(MSVC)
  target_sources(avifenc PRIVATE utf8.manifest)
elseif(MINGW)
  # ... embed utf8.manifest through a .rc file as before
endif()
```

**Comment by wantehchang** [comment]
@bradking Brad: Thanks a lot for the suggestion!

@AlifianK Could you please test the new patch in https://github.com/AOMediaCodec/libavif/commit/4362ac61487b19e62e79017396ca5c23f98c80fa.patch? Thanks.

**Comment by AlifianK** [comment]
> @AlifianK Could you please test the new patch in https://github.com/AOMediaCodec/libavif/commit/4362ac61487b19e62e79017396ca5c23f98c80fa.patch? Thanks.
 It builds successfully. Thanks!
