### ISSUE TITLE
FWIW appveyor build is failing

### ISSUE THREAD

**Issue by emerth** [AOMediaCodec/libavif#2448]
Per https://github.com/AOMediaCodec/libavif#prebuilt-library-windows

https://ci.appveyor.com/project/louquillio/libavif has been failing for over a month.

**Comment by wantehchang** [comment]
Thank you for the bug report. We dropped the AppVeyor build but forgot to update the README.md file.

Yannis, could you search for "AppVeyor" in the README.md file and update it with the replacement? Thanks!

**Comment by wantehchang** [comment]
@emerth You can dwnload the Windows binary distribution of the latest libavif v1.1.1 release from https://github.com/AOMediaCodec/libavif/releases/tag/v1.1.1.

**Comment by y-guyon** [comment]
> We dropped the AppVeyor build

I thought we only dropped it for the main branch but kept it until the next 1.0.x release. I see https://github.com/AOMediaCodec/libavif/releases/tag/v1.0.4 has avifenc.exe and avifdec.exe in a zip, likely uploaded manually. I guess it is fine to fully remove AppVeyor now.

**Comment by y-guyon** [comment]
> Yannis, could you search for "AppVeyor" in the README.md file and update it with the replacement? Thanks!

Done at https://github.com/AOMediaCodec/libavif/pull/2451.

**Comment by y-guyon** [comment]
Also done for v1.0.x at https://github.com/AOMediaCodec/libavif/pull/2452.

I wonder why AppVeyor still triggers though.

**Comment by maryla-uc** [comment]
I think we might have to disable appveyor through our appveyor account on https://www.appveyor.com/ or maybe https://ci.appveyor.com/login (not sure, and no idea what the account it)

**Comment by y-guyon** [comment]
This is @louquillio's [project](https://ci.appveyor.com/project/louquillio/libavif).

**Comment by y-guyon** [comment]
> I wonder why AppVeyor still triggers though.

Solved by https://github.com/AOMediaCodec/libavif/pull/2455.
