### ISSUE TITLE
Android 15 16kb Pages

### ISSUE THREAD

**Issue by soundlicious** [AOMediaCodec/libavif#2464]
With Android 15, users can now choose to activate the [16kb pages](https://source.android.com/docs/core/architecture/16kb-page-size/16kb) on arm64 devices.
Natives libraries need to support this to avoid crashes.

Can a new Android release be made with those changes ?

**Comment by soundlicious** [comment]
@wantehchang @jzern 
Someone might have made [a fork](https://github.com/xuetaotao/libavif) with the alignment according to this [issue in Glide repo](https://github.com/bumptech/glide/issues/5433#issuecomment-2260078481)

**Comment by jzern** [comment]
The [r27 Changelog](https://github.com/android/ndk/wiki/Changelog-r27#announcements) provides details.

**Comment by vigneshvg** [comment]
I can reproduce this bug with a local build using CMake (the fix is to include the linker flag ''Wl,-z,max-page-size=16384" ).

However, the maven hosted version does not seem to have this issue and is already aligned properly (it is generated by internal google build tools and not CMake).

**Comment by vigneshvg** [comment]
The issue has been fixed with CMake builds.

The maven release with tag '1.1.1.14d8e3c4' works on devices with 16kb pages as well.
