### ISSUE TITLE
Androidjni png or jpeg convert to AVIF?

### ISSUE THREAD

**Issue by fangzb** [AOMediaCodec/libavif#2480]
Regarding the Android JNI part of the project, I would like to implement a feature that converts the corresponding JPEG or PNG photos taken by an Android device into AVIF format. Are the native methods currently supported for this?

**Comment by vigneshvg** [comment]
> Regarding the Android JNI part of the project, I would like to implement a feature that converts the corresponding JPEG or PNG photos taken by an Android device into AVIF format. Are the native methods currently supported for this?

The Android JNI wrappers currently exist only for the decoder. There is no encoder support as of now.

**Comment by fangzb** [comment]
> > Regarding the Android JNI part of the project, I would like to implement a feature that converts the corresponding JPEG or PNG photos taken by an Android device into AVIF format. Are the native methods currently supported for this?
> 
> The Android JNI wrappers currently exist only for the decoder. There is no encoder support as of now.
Got it, Thx bro:)

**Comment by fangzb** [comment]
> > Regarding the Android JNI part of the project, I would like to implement a feature that converts the corresponding JPEG or PNG photos taken by an Android device into AVIF format. Are the native methods currently supported for this?
> 
> The Android JNI wrappers currently exist only for the decoder. There is no encoder support as of now.

> Got it, Thx bro:)
