### ISSUE TITLE
Support for encoding only?

### ISSUE THREAD

**Issue by kornelski** [AOMediaCodec/libavif#249]
Currently libavif requires [_some_](https://github.com/AOMediaCodec/libavif/blob/59256ac2c061a443193d1debd049186fdd1c7140/CMakeLists.txt#L273-L275) library capable of decoding AV1.

Would it be possible to support builds without any decoding capability at all? 

I'm interested only in creating images with `rav1e`, and the non-Rust dependencies make my builds more complicated, so I'd rather avoid them.

**Comment by joedrago** [comment]
Hmm. I guess there's no great reason to not support this path, other than a current lack of testing paths for such a thing.

If you locally remove that small block from libavif's CMake which bails out on a missing decoder, does it work for you?

**Comment by 1480c1** [comment]
Perhaps it can be changed to just a simple
```cmake
message(WARNING "libavif: No decoding library is enabled.")
```

**Comment by kornelski** [comment]
Yes, it actually compiles fine if I just remove the block.
