### ISSUE TITLE
Fix local libjpeg-turbo by setting api to 8

### ISSUE THREAD

**Issue by gitoss** [AOMediaCodec/libavif#2495]
For the local libjpeg-turbo to work, -DWITH_JPEG8=ON is required in
https://github.com/AOMediaCodec/libavif/blob/main/cmake/Modules/LocalJpeg.cmake
and (for manual local libjpeg-turbo compilation)
https://github.com/AOMediaCodec/libavif/blob/main/ext/libjpeg.cmd 
or avifenc.exe quits with "Wrong JPEG library version: library is 62, caller expects 8"

```
 -- Emulating libjpeg API/ABI v8.0 (WITH_JPEG7 = 0, WITH_JPEG8 = 1)
 -- libjpeg API shared library version = 8.3.2

```

I have no idea if this is just me (with VS & LLVM), mayvbe other people just use a system-provided libjpeg that uses api 8 ... at least media audibuild suite seems to do so with the msys2 package, maybe VS with VSPKG does so, too?

And since I seem to depend on the built-in libs with Visual Studio, just fyi - and yes, I did notice the "Feel free to use a more recent commit" line;

libjpeg-turbo is on 3.0.4 now ... https://github.com/libjpeg-turbo/libjpeg-turbo/tree/3.0.4
There are some fixes: https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/3.0.4
https://github.com/AOMediaCodec/libavif/blob/main/ext/libjpeg.cmd
https://github.com/AOMediaCodec/libavif/blob/main/cmake/Modules/LocalJpeg.cmake

If I ever get stuff to compile, maybe I'll learn how to do github pull requests, too :-)

**Comment by vrabaud** [comment]
We do have CI with MSVC and clang-cl working with a local JPEG: https://github.com/AOMediaCodec/libavif/blob/4a4e5b43e50e62c4d420aaf9af7ad68295117508/.github/workflows/ci-windows-shared-local.yml#L53
That should cover your use case no ?
