### ISSUE TITLE
Add support for reading/writing metatdata (exif/xmp)

### ISSUE THREAD

**Issue by cryptomilk** [AOMediaCodec/libavif#26]
Please add support for reading and writing metadata. This means exif and xmp data.

**Comment by darix** [comment]
another option would be to extend exiv2 to understand that iso format. it would need it for CR3 and HEIF anyway no?

**Comment by cryptomilk** [comment]
exiv2 plans to use libheif to write exiv2 data to heic images.

**Comment by joedrago** [comment]
`v0.5.1` should have this now (see the README for examples).
