### ISSUE TITLE
Build for Android?

### ISSUE THREAD

**Issue by programmingisart** [AOMediaCodec/libavif#279]
Hello, first thanks to all for this amazing work!

Is there any instruction for building the library and the examples for arm64 Android?

Thanks!

**Comment by joedrago** [comment]
Hello! I am not an Android dev, so I don't have any information on this, but if I remember correctly, @AurelC2G was building it for Android at some point in the last few months. (AurelC2G - Feel free to ignore if I'm mistaken.)

**Comment by AurelC2G** [comment]
Also not an Android dev, but yes I am using libavif on both Android and iOS. I'm using our (FB's) internal build system rather than CMake so can't easily share exactly how I am building it, but for libavif itself it is really straightforward. You may run into more difficulties when building the underlying decoding library (I am using dav1d), because some of it is written directly in asm and is platform-specific, but for these simply following their build steps (for dav1d, using meson/nasm) should work. libavif, on the other hand, is plain C, so you shouldn't run into any issues.

Are you running into a specific problem? If so, can you share some details, so I can have a look?

Then comes the question of how to expose this native code to your java app. In my case I simply exposed libavif as a plugin for the open-source Spectrum library (https://libspectrum.io/, https://github.com/facebookincubator/spectrum/tree/master/cpp/spectrum/plugins/avif), which took care of the java <-> native part for me. But shouldn't be too hard to expose libavif directly if you need to.

**Comment by jackcolentern** [comment]
> Also not an Android dev, but yes I am using libavif on both Android and iOS. I'm using our (FB's) internal build system rather than CMake so can't easily share exactly how I am building it, but for libavif itself it is really straightforward. You may run into more difficulties when building the underlying decoding library (I am using dav1d), because some of it is written directly in asm and is platform-specific, but for these simply following their build steps (for dav1d, using meson/nasm) should work. libavif, on the other hand, is plain C, so you shouldn't run into any issues.
> 
> Are you running into a specific problem? If so, can you share some details, so I can have a look?
> 
> Then comes the question of how to expose this native code to your java app. In my case I simply exposed libavif as a plugin for the open-source Spectrum library (https://libspectrum.io/, https://github.com/facebookincubator/spectrum/tree/master/cpp/spectrum/plugins/avif), which took care of the java <-> native part for me. But shouldn't be too hard to expose libavif directly if you need to.

Hello, thank you very much for your response.

I am trying to convert image from/to avif format on Android but I lack the knowledge to build these libraries.

I tried to accomplish this use Spectrum, but I get nothing (file with size of 0 byte) as the result of conversion, and I cannot find any documentation about AVIF support in Spectrum, so I am assuming that AVIF is not yet supported in Spectrum?

**Comment by jackcolentern** [comment]
I managed to build for android arm64 successfully (with dav1d).

For those who wants to do the same, here is a very crude instruction:

1. Build dav1d for Android

clone dav1d 

Edit  dav1d/package/crossfiles/aarch64-android.meson  to choose the correct tools in android-ndk  (remember to choose tools for aarch64)
run   meson setup --cross-file 'package/crossfiles/aarch64-android.meson'  build
run   cd build
run   ninja


2.  Copy the entire dav1d foder in to ext forder of libavif

3.  In CMakeLists.txt, set    AVIF_CODEC_DAV1D    and    AVIF_LOCAL_DAV1D to ON
(Enable avif_example1 also for testing)


4. run
cmake -DCMAKE_TOOLCHAIN_FILE=<path_to>/android-ndk-r21d/build/cmake/android.toolchain.cmake -DANDROID_ARM_MODE=ON -DANDROID_NDK=<path_to>/android-ndk-r21d -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=23 . 

run     make




I don't know if I did all of the steps 100% correctly, but it does give my a working executable to run on Android

Thanks for all the info, feel free to close this issue now, thanks!

**Comment by cursem** [comment]
@programmingisart run meson setup --cross-file 'package/crossfiles/aarch64-android.meson' --default-library static build

**Comment by cursem** [comment]
> I managed to build for android arm64 successfully (with dav1d).
> 
> For those who wants to do the same, here is a very crude instruction:
> 
> 1. Build dav1d for Android
> 
> clone dav1d
> 
> Edit dav1d/package/crossfiles/aarch64-android.meson to choose the correct tools in android-ndk (remember to choose tools for aarch64)
> run meson setup --cross-file 'package/crossfiles/aarch64-android.meson' --default-library static build
> run cd build
> run ninja
> 
> 1. Copy the entire dav1d foder in to ext forder of libavif
> 2. In CMakeLists.txt, set    AVIF_CODEC_DAV1D    and    AVIF_LOCAL_DAV1D to ON
>    (Enable avif_example1 also for testing)
> 3. run
>    cmake -DCMAKE_TOOLCHAIN_FILE=<path_to>/android-ndk-r21d/build/cmake/android.toolchain.cmake -DANDROID_ARM_MODE=ON -DANDROID_NDK=<path_to>/android-ndk-r21d -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=23 .
> 
> run make
> 
> I don't know if I did all of the steps 100% correctly, but it does give my a working executable to run on Android
> 
> Thanks for all the info, feel free to close this issue now, thanks!

Hi, when id run make, i got the errors:
[  1%] Linking C shared library libavif.so
CMakeFiles/avif.dir/src/reformat_libyuv.c.o: In function `avifImageYUVToRGBLibYUV':
/Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:63: undefined reference to `kYuvF709Constants'
/Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:63: undefined reference to `kYuvF709Constants'
/Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:64: undefined reference to `kYvuF709Constants'
/Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:64: undefined reference to `kYvuF709Constants'
/Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:70: undefined reference to `kYuvJPEGConstants'
/Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:70: undefined reference to `kYuvJPEGConstants'
/Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:71: undefined reference to `kYvuJPEGConstants'
/Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:71: undefined reference to `kYvuJPEGConstants'
/Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:77: undefined reference to `kYuvV2020Constants'

What should i do?

**Comment by cursem** [comment]
@programmingisart Hello, do you know how convert rgb(10bit) to bitmap ？

**Comment by cursem** [comment]
@programmingisart I have built .so successfully. But another issue is comming. How to judge avif format in java/kotlin? Can i read the raw data to parse the header, what should do.

**Comment by programmingisart** [comment]
> @programmingisart I have built .so successfully. But another issue is comming. How to judge avif format in java/kotlin? Can i read the raw data to parse the header, what should do.

Hello, actually I am not a experienced Android / Java developer, I am just experimenting with building for different OS, so unfortunately I did not know the answer, sorry about that.

**Comment by cursem** [comment]
> > @programmingisart I have built .so successfully. But another issue is comming. How to judge avif format in java/kotlin? Can i read the raw data to parse the header, what should do.
> 
> Hello, actually I am not a experienced Android / Java developer, I am just experimenting with building for different OS, so unfortunately I did not know the answer, sorry about that.

Any way, thanks for your replying.

**Comment by vanchung1995** [comment]
Hello everybody. How can I use this lib with java wrapper? Thanks alot

**Comment by ruanxiao** [comment]
@programmingisart

**Comment by ruanxiao** [comment]
Hello, see you successfully compiled libavif, based on dav1d
Is there a detailed tutorial here? I was stumped by dav1d compilation in the first step
Thanks for any reply
@programmingisart

**Comment by dreamuniverse** [comment]
> meson.build:25:0: ERROR: Unknown compiler(s): [['aarch64-linux-android21-clang']]

Hi, I came across the same problem. meson.build:25:0: ERROR: Unknown compiler(s): [['aarch64-linux-android21-clang']]
Yet I modified the crossfile/aarch64-android.meson configures to my paths of ndk, yet it still throws the error. I tried to install the clang-12 and replace it with system clang-12, still failed.
Would you mind sharing your solution? thanks

**Comment by yufengvac** [comment]
> > I managed to build for android arm64 successfully (with dav1d).
> > For those who wants to do the same, here is a very crude instruction:
> > 
> > 1. Build dav1d for Android
> > 
> > clone dav1d
> > Edit dav1d/package/crossfiles/aarch64-android.meson to choose the correct tools in android-ndk (remember to choose tools for aarch64)
> > run meson setup --cross-file 'package/crossfiles/aarch64-android.meson' --default-library static build
> > run cd build
> > run ninja
> > 
> > 1. Copy the entire dav1d foder in to ext forder of libavif
> > 2. In CMakeLists.txt, set    AVIF_CODEC_DAV1D    and    AVIF_LOCAL_DAV1D to ON
> >    (Enable avif_example1 also for testing)
> > 3. run
> >    cmake -DCMAKE_TOOLCHAIN_FILE=<path_to>/android-ndk-r21d/build/cmake/android.toolchain.cmake -DANDROID_ARM_MODE=ON -DANDROID_NDK=<path_to>/android-ndk-r21d -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=23 .
> > 
> > run make
> > I don't know if I did all of the steps 100% correctly, but it does give my a working executable to run on Android
> > Thanks for all the info, feel free to close this issue now, thanks!
> 
> Hi, when id run make, i got the errors: [ 1%] Linking C shared library libavif.so CMakeFiles/avif.dir/src/reformat_libyuv.c.o: In function `avifImageYUVToRGBLibYUV': /Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:63: undefined reference to `kYuvF709Constants' /Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:63: undefined reference to `kYuvF709Constants' /Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:64: undefined reference to `kYvuF709Constants' /Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:64: undefined reference to `kYvuF709Constants' /Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:70: undefined reference to `kYuvJPEGConstants' /Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:70: undefined reference to `kYuvJPEGConstants' /Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:71: undefined reference to `kYvuJPEGConstants' /Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:71: undefined reference to `kYvuJPEGConstants' /Users/wangwensheng/AndroidStudioProjects/avif/libavif/src/reformat_libyuv.c:77: undefined reference to `kYuvV2020Constants'
> 
> What should i do?

I also encountered this problem
How did you solve it？

**Comment by vigneshvg** [comment]
Hi all,

libavif now contains JNI wrappers for decoding in the android_jni directory.

There is also a hosted version in maven central here: https://mvnrepository.com/artifact/org.aomedia.avif.android/avif

The instructions in android_jni directory uses libgav1 as an example decoder. The maven hosted version uses dav1d.
