### ISSUE TITLE
MP4Box incidate full_range_flag="1" but avifdec report Limited range

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#281]
[testfile.zip](https://github.com/AOMediaCodec/libavif/files/5070210/testfile.zip)
z.avif was created via libheif and I believe the file should be full range.

However avifdec reports Limited range:
```
Image decoded: z.avif
 * Resolution     : 2048x1366
 * Bit Depth      : 8
 * Format         : YUV420
 * Alpha          : Absent
 * Range          : Limited
 * Color Primaries: 2
 * Transfer Char. : 2
 * Matrix Coeffs. : 6
 * ICC Profile    : Absent (0 bytes)
 * XMP Metadata   : Absent (0 bytes)
 * EXIF Metadata  : Absent (0 bytes)
 * Transformations: None
 * 1 timescales per second, 1.00 seconds (1 timescales), 1 frame
 * Frames:
   * Decoded frame [0] [pts 0.00 (0 timescales)] [duration 1.00 (1 timescales)]
```
Output of mp4box.exe -diso zlibavif.avif indicate **full_range_flag=1** so I am confused:
`<ColourInformationBox Container="video_sample_entry ipco encv resv" Specification="iff" Type="colr" Size="19" full_range_flag="1" matrix_coefficients="6" transfer_characteristics="2" colour_primaries="2" colour_type="nclx"> </ColourInformationBox>`

**Comment by joedrago** [comment]
Hm, you're right; the underlying AV1 payload's color range is "winning" here, and it shouldn't. 

Is there any reason the underlying AV1 payload would be incorrectly signaled? I'll fix libavif to properly let the `nclx` box override this, but I feel like the AV1 payload's signaling should correspond.

**Comment by joedrago** [comment]
After talking with @wantehchang , I chose to make a smaller, simpler fix for this. Either way, it should work now.
