### ISSUE TITLE
find_package(rav1e) causes build error due to -Wpoison-system-directories

### ISSUE THREAD

**Issue by kornelski** [AOMediaCodec/libavif#284]
libavif fails to build with clang 12, because libavif sets `-Werror`, and clang 12 has added new warnings.

```cmake
        if(NOT TARGET rav1e)
            find_package(rav1e REQUIRED)
            set(AVIF_CODEC_INCLUDES ${AVIF_CODEC_INCLUDES} ${RAV1E_INCLUDE_DIR})
        endif()
```

I have `rav1e` in `/usr/local/{include,lib}` and `find_package` correctly finds it there. The problem is, that the result ends up in `AVIF_CODEC_INCLUDES`, which is then used as an include path.

Clang is given `-Werror`, and defaults to having `-Wpoison-system-directories`, which forbids adding `-I/usr/local/include`

> error: include location '/usr/local/include' is unsafe for cross-compilation [-Werror,-Wpoison-system-directories]

(for the record: I'm not cross-compiling)

----

I suggest using `-Werror` only in environment you control, such as your CI or your own development machines. It's asking for failures when the library is used with compilers you don't control.

**Comment by 1480c1** [comment]
Probably better to move it to `CMAKE_C_FLAGS_DEBUG` so it's not applied for release builds

**Comment by wantehchang** [comment]
Another solution is to not use clang's -Weverything. -Weverything enables some warnings that are not generally useful, and libavif's build system has to disable them with -Wno-xxx:

```
if(CMAKE_C_COMPILER_ID MATCHES "Clang")
  MESSAGE(STATUS "libavif: Enabling warnings for Clang")
  add_definitions(
    -Weverything
    -Werror
    -Wno-bad-function-cast
    -Wno-cast-align
    -Wno-conversion
    -Wno-covered-switch-default
    -Wno-disabled-macro-expansion
    -Wno-documentation
    -Wno-documentation-unknown-command
    -Wno-double-promotion
    -Wno-float-equal
    -Wno-missing-noreturn
    -Wno-padded
    -Wno-sign-conversion
    -Wno-error=c11-extensions
  )
```

**Comment by bnason-nf** [comment]
I could be missing something, but I think this whole issue might be simpler to solve by using the CMake `target_compile_definitions()` construct (instead of `add_definitions()` with strict `PRIVATE` warnings levels, and loose or no warnings for `PUBLIC`.

https://cmake.org/cmake/help/latest/command/target_compile_definitions.html

**Comment by vrabaud** [comment]
The AVIF_ENABLE_WERROR option now exists and third party libs are now SYSTEM included.
