### ISSUE TITLE
Store alpha before color channels

### ISSUE THREAD

**Issue by kornelski** [AOMediaCodec/libavif#287]
Currently write.c calls `avifEncoderDataCreateItem` for color first, then for alpha if needed.

Because encoded data is written to the file in the order the items were created, the AVIF file ends up with color channels first, alpha channel second.

This is problematic for streaming of images over a network connection, because displaying partially-loaded color channel without alpha can look ugly. If the data was in the opposite order: alpha first, color second, then networked clients could decode incoming color data with alpha already known.

**Comment by joedrago** [comment]
This is most certainly a rendering/downstream decision. The `meta` box, which is always at the beginning of the file, is sufficient to know if alpha is present in the file. If you can choose to not render when you have a full alpha frame and an incomplete color frame, you can similarly choose to not render when you have a full color frame and an incomplete alpha frame.

**Comment by kornelski** [comment]
I'm not sure if you've understood what I'm asking for.

Clients, like web browsers, that are streaming images over HTTP in practice don't have a choice over the order the data comes in.

"incomplete color & no alpha" vs "complete alpha & incomplete color" are not equivalent choices. User experience of these two situations is dramatically different.

Rendering of color channels without alpha can look jarring and broken. No current browser ever does that. In this case clients will choose not to render anything at all until alpha starts loading. This increases latency, because color data is usually much larger than alpha data.

OTOH waiting for smaller alpha data allows clients to start rendering partial image with all channels sooner. It gives user experience similar to baseline PNG.

There's no file size overhead to switching order of these two items, and in libavif it's a matter of reordering a few lines of code, so I don't see any reason not to do it.

A great implementation could go even further and use iloc extents to interleave color and alpha data, but that's more work.

**Comment by jakearchibald** [comment]
+1. Interleaved alpha is ideal, but alpha-first at least allows for a streaming render. The perceived performance impact here is huge.

**Comment by wantehchang** [comment]
I think this is a choice between two objectives:

1. Produce an AVIF container structure that is "obviously correct" and won't raise questions. This favors the "primary image before auxiliary images" order.

2. Allow for incremental decoding and rendering of AVIF images with alpha planes. This favors the "alpha image before primary image" order.

To some programmers, 1 could be very appealing. I think I am that kind of programmer. From my work on Chrome, I also know incremental decoding and rendering of AVIF images (with or without alpha planes) in Chrome is nontrivial to implement and is unlikely to happen soon. So I probably would not consider 1 until we known of an application that is planning to attempt 2.

Does anyone know of an application that is planning to decode and render AVIF images incrementally? I am not following all the AVIF-related activities, so I may not be aware of some work in progress.

Interleaving color and alpha data seems like premature optimization at this point. I would definitely only do that when an application exists that can take advantage of interleaved color and alpha data.

**Comment by kornelski** [comment]
The `iloc` box already supports reordering and interleaving, so as an implementer you already don't have a choice. The complexity is already there, and you must support arbitrary order and interleaving. It's not raising questions, it's how `iloc` works.

Using non-obvious order would in fact be helpful to keep decoders spec-compliant, so that they can't ignore `iloc`, `pitm` and blindly assume color data comes first. 

TLS has "GREASE" to prevent "ossification" of implementations. If libavif supported alpha-first ordering, it would play the same role.

**Comment by joedrago** [comment]
Putting AVIF ordering and parsing aside for a second, there doesn't currently exist an AV1 decoder that accepts a partial sample and returns a partial frame. without such a thing, all of these gains are purely hypothetical, as any implementation of AVIF plane ordering would still require both samples to be fully downloaded before you could see anything.

libavif already supports arbitrary ordering of iloc or any other payloads upon decode, but I think purposefully making "odd" ordering under the guise of keeping people spec compliant is bad. I am completely on board for having a suite of test files that have interesting orders and transformations and whatnot, but I would way rather have the most common files be the friendliest and most obvious. To me, this means that the primary item is the first thing in the mdat payload and all auxiliary data comes after it.

Short of partial-frame/sample decode being officially  added to dav1d and/libaom, I don't plan to change the default ordering.

**Comment by jakearchibald** [comment]
There's a chicken/egg problem here.

It would be more appealing to create a partial-frame decoder if it would benefit user experience. If the majority of AVIFs in the wild are built to be hostile to partial-frame decoding, that becomes less appealing.

**Comment by kornelski** [comment]
AV1 can be encoded using tiles (and I do use them, because it speeds up encoding a lot). I wonder if display of partial tiles would be good enough as a partial decoder. I think that's something which could be implementable already.

**Comment by joedrago** [comment]
> There's a chicken/egg problem here.
> 
> It would be more appealing to create a partial-frame decoder if it would benefit user experience. If many of AVIFs in the wild are built to be hostile to partial-frame decoding, that becomes less appealing.

This is overstating a bit. The _vast_ majority of images likely to be encoded as AVIF are going to be fully opaque, and thus are no more "hostile" than any other format on this regard, has the alpha payload is completely skipped on opaque images.

**Comment by bnason-nf** [comment]
The chicken and egg point I think cuts to the heart of the matter. My understanding is that in order to get some sort of progressive AVIF decoding, we would need to use tiled encodes. If that understanding is wrong, please let me know (and ignore the rest of this). If it's correct, then I think we would need some changes at various levels in the pipeline to get progressive decoding and rendering:

1. The decoders would need to support returning decoded tiles to libavif before all the tiles were completely decoded.
2. The libavif APIs would need to be extended to support the same thing, to provide tiles to the application before the image is complete.
3. The application would need to use the new libavif APIs and render the tiles as they arrived.

Please correct me if I'm wrong, but I believe right now that none of these things are supported. It seems strange to request that we start at the middle of this chain, I would think instead we'd want to start at the lowest level, adding support in the decoders, and then libavif, and then applications.

Also since images would need to be encoded with tiles, and probably with a high enough granularity to make sense for a progressive decode and render, this could significantly impact encoding efficiency. This is contrary to one of the primary motivations for using AVIF in the first place.

In any case, this whole thing is completely independent of alpha ordering, and I cant see any point in changing the alpha order before we have a plan for progressive decoding and rendering.

**Comment by kornelski** [comment]
I agree with you that it'd need entire pipeline to support, at least returning the tiles. The good news is that tiled encoding is well supported, and because AV1 encoding is so painfully slow, it gets used :)

All images I generate from my tools (including [Cloudflare's image processing API](https://developers.cloudflare.com/images/about)) use tiled encoding (I keep tiles larger than ~128x128px to keep overhead low). I've already released a tool that [embeds alpha first](//lib.rs/cavif). I'm working on a streaming parser right now.

**Comment by cconcolato** [comment]
> My understanding is that in order to get some sort of progressive AVIF decoding, we would need to use tiled encodes.

That is not the only way. AV1 (and AVIF) supports scalable encoding. Unfortunately, very few encoders support this feature, yet.

**Comment by joedrago** [comment]
I thought about this more this evening, and I was conflating my distaste for reordering the items / item IDs themselves (and the resultant meta box and code flow) with the actual `mdat` payload ordering, of which I'm ambivalent. 

I honestly don't see any gains here, but I'll chalk it up to not knowing what future AV1 codec implementation magic is coming, and this is a harmless enough change in the mdat writer. If you think this ordering will matter in the future, this is a fairly benign change, so I'm on board.

**Comment by jakearchibald** [comment]
Ohh great news! Thank you!

@cconcolato is there anywhere I can read about 'scalable encoding'?
