### ISSUE TITLE
Use of min/max quantizer for images

### ISSUE THREAD

**Issue by jakearchibald** [AOMediaCodec/libavif#290]
Apologies for using this as a support forum - let me know if there's a better place.

I've used min/max quantizers in video encoding before, especially when targeting a particular file size, but I can't figure out how it should be used for images. Roughly speaking, how are min/max quantizers used in a single image?

**Comment by novomesk** [comment]
The results are encoder specific and it also depends on image dimensions and speed levels.

I suggest to make several experiments with combinations of minQ and maxQ.

If you want to have almost lossless result, use minQ=0, maxQ=0.

If you choose minQ=0, maxQ<15 the result still look high quality - close to visually lossless.

Values like minQ=10, maxQ=30 gives good compression with decent quality.

Even using maxQ=40 is good for some internet photos.

**Comment by jakearchibald** [comment]
How does AOM use these values?

**Comment by vrabaud** [comment]
I believe this is now obsolete since the introduction of the quality parameter in https://github.com/AOMediaCodec/libavif/pull/1138
