### ISSUE TITLE
Reading of multiple extents

### ISSUE THREAD

**Issue by kornelski** [AOMediaCodec/libavif#291]
I've noticed support for `iloc` extents is missing (https://crbug.com/1122634):

https://github.com/AOMediaCodec/libavif/blob/3fd2db22eef9fbd20bc5f768b50f13102ec77f7c/src/read.c

and this makes it impossible to read images that interleave color and alpha data.

I think I could try implementing it.

Should `avifDecoderItem` use `AVIF_ARRAY_DECLARE` to store the extents' offset/lenghts?

It seems like a lot of code assumes it can use `avifDecoderDataCalcItemPtr` to get a contiguous chunk of memory. To avoid breaking that assumption, I suggest copying concatenated extents into a new, contiguous chunk of memory owned by `avifDecoderItem`. Will that work? Or should the copy be in `avifDecoderData`?

**Comment by joedrago** [comment]
I'll look into it. Eventually I would want full samples in the decoder input struct, so it might require a bit of new plumbing.

**Comment by kornelski** [comment]
Thanks. Here are test files:

[mixedextents.zip](https://github.com/AOMediaCodec/libavif/files/5138207/mixedextents.zip)

**Comment by joedrago** [comment]
Looking good!

@wantehchang Please review/audit this change when you can.

```
>avifdec twoextents.avif twoextents.png
Decoding with AV1 codec 'dav1d', please wait...
Image decoded: twoextents.avif
Image details:
 * Resolution     : 150x100
 * Bit Depth      : 8
 * Format         : YUV444
 * Alpha          : Absent
 * Range          : Limited
 * Color Primaries: 1
 * Transfer Char. : 13
 * Matrix Coeffs. : 1
 * ICC Profile    : Absent (0 bytes)
 * XMP Metadata   : Absent (0 bytes)
 * EXIF Metadata  : Absent (0 bytes)
 * Transformations: None
Wrote PNG: twoextents.png
```
![twoextents](https://user-images.githubusercontent.com/332342/91538966-7493bb80-e8cd-11ea-932f-a69d5a28bf44.png)

**Comment by kornelski** [comment]
That was quick!
