### ISSUE TITLE
Premultiplied alpha support

### ISSUE THREAD

**Issue by kornelski** [AOMediaCodec/libavif#292]
Efficient compression of images with alpha benefits from using premultiplied alpha color space.

In AVIF that is marked by `iref` box with `prem` type: https://github.com/AOMediaCodec/av1-avif/issues/96#issuecomment-679191375

I'm attaching a test case. Both images in the zip file should look the same. If the `premultiplied.avif` looks darker, it's a bug.

[prem-test-case.zip](https://github.com/AOMediaCodec/libavif/files/5142217/prem-test-case.zip)

<small>[image attribution: wikipedia](https://en.wikipedia.org/wiki/File:PNG_transparency_demonstration_1.png)</small>

**Comment by joedrago** [comment]
So from a libavif perspective, am I understanding the support request correctly (after reading the standard):

* In addition to an `iref` of type `auxl`, consider an `iref` of type `prem` to also be an alpha auxiliary item
* Surface the boolean "the alpha is premultiplied" to `avifImage`
* If that boolean is set at encode time and alpha exists, use a reference type of `prem` instead of `auxl` for the alpha channel

Is this sufficient for libavif support? Obviously downstream projects will have to honor the boolean independently of libavif.

**Comment by kornelski** [comment]
Hmmm… I understood the spec differently. The alpha association remains exactly as-is, nothing changes there. And there in _addition_ to image<>auxl assocation, there exists a _reverse_ association of type `prem` that only acts as a boolean.

**Comment by joedrago** [comment]
@cconcolato Can you provide guidance on how the actual boxes should be structured for `prem`?

I'd prefer to not actually offer pixel manipulation in `avifenc` itself (other than the YUV conversion requirements, of course). I think it is reasonable to let people signal to `avifenc` if the data they're offering me is premultiplied or not, but I'd rather not get involved with converting their pixel data for them.

**Comment by kornelski** [comment]
It would be very useful to have an option to accept and return premultiplied alpha data unchanged. Premultiplied alpha is the "native" format on macOS and iOS.

If you don't want to do conversions, that's a bit unfortunate. I don't see this colorspace conversion much different than all the other conversions the library needs to do.

If you don't want to perform the conversion, please keep `AVIF_RGB_FORMAT_RGBA` to mean uncorrelated alpha and add another identifier for premultiplied. Otherwise I'm afraid applications will ignore the flag and mangle the alpha. It's not a theoretical issue. The first [QuickLook AVIF plugin](https://github.com/dreampiggy/AVIFQuickLook) I've tried has exactly this bug.

**Comment by joedrago** [comment]
In your mind, how would this correctly interact with YUV<->RGB conversion? I'm concerned that this will turn into a huge can of worms, and I haven't fit the issue entirely in my head yet.

@bnason-nf Do you have opinions on these mechanisms?

**Comment by kornelski** [comment]
I imagine this to be something like `alphaFormat` in `avifImage`. You can't apply it to YUV channels, so it has to exist as a flag there.

And then I'd expect `avifImageYUVToRGB` to be aware of the flag, and either undo premultplication automatically and generate `AVIF_RGB_FORMAT_RGBA` with uncorrelated alpha, or if you prefer not to change the pixels, then I'd expect it to set format to `AVIF_RGB_FORMAT_RGBA_PREMULTIPLIED`.

**Comment by cconcolato** [comment]
> The alpha association remains exactly as-is, nothing changes there. And there in _addition_ to image<>auxl assocation, there exists a _reverse_ association of type `prem` that only acts as a boolean.

I agree with that.

**Comment by baumanj** [comment]
FYI, there's support for premultiplied alpha now in Firefox nightly and should be part of the next release (86) when AVIF support will be enabled by default

**Comment by joedrago** [comment]
I think this is worth tracking still, for sure. I can make a new issue if you're prefer to not be involved, however. Let me know.

**Comment by joedrago** [comment]
I just accepted PR #477, which should add support for this.
