### ISSUE TITLE
YCgCo fails silently

### ISSUE THREAD

**Issue by kornelski** [AOMediaCodec/libavif#305]
`avifImageRGBToYUV`/`avifImageYUVToRGB` lack support for `AVIF_MATRIX_COEFFICIENTS_YCGCO`.

The immediate problem is that the logic just falls through without returning error, and does invalid conversion instead, producing images with nonsensical data. 

It should be returning `AVIF_RESULT_REFORMAT_FAILED` or actually doing the conversion.

**Comment by joedrago** [comment]
I'll fix this one. I designed `avifReformatMode` to handle these "more interesting" cases (identity, YCgCo, BT2020CL), but I agree that the paths that aren't supported (yet) should error out.

**Comment by joedrago** [comment]
Alright, I have protection in place to bail out if I don't currently support the matrixCoefficients supplied, and I've created a new issue to track adding more support in the future:

https://github.com/AOMediaCodec/libavif/issues/306
