### ISSUE TITLE
Error writing PNG: known incorrect sRGB profile when writing to PNG

### ISSUE THREAD

**Issue by SenhLiu** [AOMediaCodec/libavif#310]
Get the error: known incorrect sRGB profile, when trying to convert the linked image to PNG.

[TestImage.zip](https://github.com/AOMediaCodec/libavif/files/5211097/TestImage.zip)

Using avifdec Version: 0.8.1 (dav1d:0.7.1-0-ge9df70c, aom:2.0.0)

Command line:

avifdec HeatherGraham.avif out.png

Image views OK with Chrome.

**Comment by joedrago** [comment]
This is a default option for libpng, and it is erroring out inside of libpng, but I agree that this isn't really any of `avifdec`'s business to care. It is up to the enduser to decide for themselves if they want to keep an ICC profile (even if it is odd or known-incorrect), so I've disabled that specific libpng check and I've mirrored `--ignore-icc` from avifenc into avifdec, in case you just wanted to completely strip the profile in the future.

https://github.com/AOMediaCodec/libavif/commit/2fadd1d19815317fd444d177623b9c1458f7c637

**Comment by SenhLiu** [comment]
Thanks for the quick patch! Looking forward to the next release.
