### ISSUE TITLE
a question on License

### ISSUE THREAD

**Issue by qlcom** [AOMediaCodec/libavif#316]
The Licence text looks like 2-clause BSD license, but it contain the sentence "All Rights Reserved."

The 2-clause BSD license as mentioned on https://opensource.org/licenses/BSD-2-Clause and https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_.28.22Simplified_BSD_License.22_or_.22FreeBSD_License.22.29 don't contain that sentence.

can you take a look in to it?

thanks.

**Comment by joedrago** [comment]
Hello! I'll preface this with an obligatory "I Am Not A Lawyer", but my intent has always been to use the most obvious 2-Clause BSD license there is, with no hidden gotchas or anything.

If you search for the string `SPDX-License-Identifier: BSD-2-Clause` which is at the top of all of my source files, you'll most likely find yourself here:

https://spdx.org/licenses/BSD-2-Clause

This has the "All Rights Reserved." wording on the Copyright line. In addition, the libaom repo's LICENSE file follows the same pattern:

https://aomedia.googlesource.com/aom/+/refs/heads/master/LICENSE#1

@wantehchang @cconcolato @mwatson2 Do any of you have any insight on this? I don't feel like this wording is in error.

**Comment by mwatson2** [comment]
I, also, am not a lawyer, but my guess is that this is standard and the meaning is to first reserve all rights as to copyright to the author and then, in the text below, to grant specific rights with conditions. Perhaps if you don't at first assert your ownership of the rights you are in no position to then give them away or attach conditions.

**Comment by wantehchang** [comment]
The BSD-3-Clause license file in the Chromium source tree also says "All rights reserved.":
https://chromium.googlesource.com/chromium/src/+/master/LICENSE

Other examples:
https://code.videolan.org/videolan/dav1d/-/blob/master/COPYING
https://github.com/xiph/rav1e/blob/master/LICENSE
https://golang.org/LICENSE
https://chromium.googlesource.com/libyuv/libyuv/+/master/LICENSE
https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/LICENSE

**Comment by qlcom** [comment]
> The BSD-3-Clause license file in the Chromium source tree also says "All rights reserved.":
> https://chromium.googlesource.com/chromium/src/+/master/LICENSE
> 
> Other examples:
> https://code.videolan.org/videolan/dav1d/-/blob/master/COPYING
> https://github.com/xiph/rav1e/blob/master/LICENSE
> https://golang.org/LICENSE
> https://chromium.googlesource.com/libyuv/libyuv/+/master/LICENSE
> https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/LICENSE

but this project uses 2-clause license

**Comment by qlcom** [comment]
i am sorry for wasting all of your time.

I am not a lawyer. I just saw that license and noticed that sentence don't present in the texts i mentioned.
