### ISSUE TITLE
Factor out ISOBMFF parser

### ISSUE THREAD

**Issue by ao2** [AOMediaCodec/libavif#317]
Hi,

AFAIU libavif has to parse ISOBMFF files to do its job, I was wondering whether it would be worth splitting up the ISOBMFF parsing code into a library.

Ideally this would enable sharing the code with other projects like [libheif](https://github.com/strukturag/libheif) and possibly even [libexif](https://github.com/libexif/libexif) in case they decided to support extracting EXIF data from ISOBMFF files.

I know that this is easier said that done, but I wanted to at least ask if there is interest.

FWIW there is already [libbmff](https://github.com/frejoel/bmffparse) by @frejoel, which is a small C shared library for parsing ISOBMFF but I don't know in what shape it is.

Feel free to close the issue if this is too far fetched. :sweat_smile:

Thanks,
Antonio

**Comment by joedrago** [comment]
I don't personally have any interest in doing such a thing. As AVIF is getting some traction, I think there are at least five container parser implementations out there (some on C/C++, at least one in Rust), and each of them have managed to do the BMFF box parsing pretty quickly without too much issue.

That said, libavif is BSD licensed, to feel free to make a fresh library that does what you want and use the code in read.c as a reference or snippets(following the license, of course).

**Comment by ao2** [comment]
OK, thanks @joedrago, I appreciate your taking the time to reply.

Take care, Antonio
