### ISSUE TITLE
a problem for building libaom/libavif？

### ISSUE THREAD

**Issue by October5** [AOMediaCodec/libavif#322]
Hello, first thanks for the work.

I have a problem when I ran  avif encoder demo. Found that the function( avifEncoderFinish()) run very slow, time-consuming is about **12s!!!** 

Would you please help me have a look? Thanks.

Build steps:
1) ./aom.cmd
2) cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DCMAKE_BUILD_TYPE="Release" -DBUILD_SHARED_LIBS=OFF -DAVIF_CODEC_AOM=ON -DAVIF_LOCAL_AOM=ON .
3) make -j4

platform: MacOS

Demo code: 
    ... ...
     avifEncoder * encoder = avifEncoderCreate();
     ... //set parameters

    avifRWData raw = AVIF_DATA_EMPTY;
    while (nextimage) {
        avifImage * image = avifImageCreate(width, height, depth, AVIF_PIXEL_FORMAT_YUV420);
       ... 

        avifResult image_result = avifEncoderAddImage(encoder, image, 100, AVIF_ADD_IMAGE_FLAG_NONE);    
 
        avifImageDestroy(image);
    }
    ... 
    //start_time
    avifResult res = avifEncoderFinish(encoder, &raw);
   //endtime;  endtime - starttime -> 12-13s

Demo building dependency:
    ...
    target_link_libraries(avif_demo libavif.a libaom.a)
    ...

Thanks.

**Comment by joedrago** [comment]
Just to manage your expectations a bit, you can certainly configure an AV1 encoder such that it will take many seconds to encode, depending on the image's resolution and depth, whether or not you're allowing multithreading, the speed, tiling, and quantizers chosen. 

Assuming you're building libaom fully optimized, can you try adding these lines just after calling `avifEncoderCreate()`:

        encoder->speed = AVIF_SPEED_FASTEST;
        encoder->maxThreads = 12; // or whatever number of cores you have on your machine

Again, assuming your libaom is built with optimizations and your input file isn't massive, this should be noticeably faster. You're going to want to find a `speed` value that is a reasonable tradeoff between the time you're willing to spend and the efficiency in the output. Perhaps try something around `4` and see if that is a nice middle ground, perhaps.

**Comment by joedrago** [comment]
Just for some ballpark numbers:

On my machine here (an older i7 with 6 cores), I encoded a `4032x3024` 8bpc image a few times. It encoded at speed `10` at `3.65s`, speed `7` in `13.88s`, speed `4` in `15.79s`, and speed `0` in `100.08s` (!). For reference, it took ImageMagick to convert this image to PNG in `5.00s`, so 4-15s isn't too outrageous, IMO.

**Comment by October5** [comment]
> Just to manage your expectations a bit, you can certainly configure an AV1 encoder such that it will take many seconds to encode, depending on the image's resolution and depth, whether or not you're allowing multithreading, the speed, tiling, and quantizers chosen.
> 
> Assuming you're building libaom fully optimized, can you try adding these lines just after calling `avifEncoderCreate()`:
> 
> ```
>     encoder->speed = AVIF_SPEED_FASTEST;
>     encoder->maxThreads = 12; // or whatever number of cores you have on your machine
> ```
> 
> Again, assuming your libaom is built with optimizations and your input file isn't massive, this should be noticeably faster. You're going to want to find a `speed` value that is a reasonable tradeoff between the time you're willing to spend and the efficiency in the output. Perhaps try something around `4` and see if that is a nice middle ground.

Thank you very much. I tested with a sequence ( 270x360  & 8bits & 100 frames & 4 threads &  speed->default -1 ~). After Adding encoder->speed = 8, time consuming is within 1s, as expected. 

Thanks.

**Comment by joedrago** [comment]
Great! It might be worth familiarizing yourself with how libavif's `speed` value corresponds to the lower level codecs, just so you go into this with both eyes open. From the header:

        // * Speed range: [AVIF_SPEED_SLOWEST - AVIF_SPEED_FASTEST]. Slower should make for a better quality
        //   image in less bytes. AVIF_SPEED_DEFAULT means "Leave the AV1 codec to its default speed settings"./
        //   If avifEncoder uses rav1e, the speed value is directly passed through (0-10). If libaom is used,
        //   a combination of settings are tweaked to simulate this speed range.

If you don't pick a speed on `avifEncoder`, it simply lets the underlying codec use its own speed defaults. I think `rav1e` picks something middling (6?), and libaom configures itself to be slow-but-efficient-output. The speed value is just directly handed to `rav1e`, but for libaom, here is the code that interprets `speed`:

https://github.com/AOMediaCodec/libavif/blob/master/src/codec_aom.c#L359

As you can see, `8` is actually when we switch libaom from `AOM_USAGE_GOOD_QUALITY` to `AOM_USAGE_REALTIME`, which I imagine turns off a handful of encoder tricks. Feel free to look into libaom's differences between these modes (and `cpu-used`) for more insight into the decisions here.
