### ISSUE TITLE
Any boilerplate on how to interface with Java using JNI

### ISSUE THREAD

**Issue by mridang** [AOMediaCodec/libavif#325]
Hello, would it be possible to provide some examples on how to interface with libavif using Java using JNI? There doesn't seem to be any bindings available. Any help if appreciated. 🙏🏼

**Comment by dwbuiten** [comment]
I would expect it to be the same as interfacing with any C API via JNI? (I have never used JNI myself).

I'm not sure libavif is the appropriate place to have this information, though, as it would not seem to be specific to libavif?

**Comment by vigneshvg** [comment]
libavif now has JNI bindings built in to the library: https://github.com/AOMediaCodec/libavif/tree/main/android_jni

a maven hosted version can be found here: https://repo1.maven.org/maven2/org/aomedia/avif/android/avif/
