### ISSUE TITLE
Inconsistent prototypes of avifIO functions for memory buffers

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#344]
In avif.h, three avifIO functions for memory buffers are declared:

```
avifIO * avifIOCreateMemoryReader(const uint8_t * data, size_t size);

avifResult avifDecoderReadMemory(avifDecoder * decoder, avifImage * image, const avifROData * input);

avifResult avifDecoderSetIOMemory(avifDecoder * decoder, const avifROData * rawInput);
```

The first function uses a buffer pointer and a buffer size to represent the memory buffer, whereas the second and third functions use an avifROData struct to represent the memory buffer. It would be good to standardize on a single representation.

Joe, which one would you prefer? Once I know your preference, I can make the change.

My preference would be to use the buffer pointer and buffer size. However, I noticed that the avifROData form is more convenient for converting code from old API because the old protype of avifDecoderParse took a const avifROData * input.

**Comment by joedrago** [comment]
I think data+size is preferable to more `avifROData`s on the stack.

**Comment by wantehchang** [comment]
Fixed by https://github.com/AOMediaCodec/libavif/commit/7de4445a3929847f28bb8bae45b42f81053dad7b.
