### ISSUE TITLE
Support for repeating image sequences

### ISSUE THREAD

**Issue by igo95862** [AOMediaCodec/libavif#347]
I found a comment that avif can support looping images (like gif)

https://github.com/AOMediaCodec/av1-avif/issues/73#issuecomment-605335922

>To indicate that media is repeated, an enhancement to the EditListBox is used. The edit list maps the media timeline to the presentation timeline. The semantics of the flags field of the EditListBox as defined in ISO/IEC 14496-12 are extended as follows. When (flags & 1) is equal to 1, the entire edit list is repeated a sufficient number of times to equal the track duration.
NOTE The number of times the edit list is repeated does not need to be an integer. In other words, the last repetition of the edit list may be cut to match the track duration.
If the track duration is unknown/indefinite, the edit list is repeated indefinitely.

Right now `avifenc` can create image sequences but they are not looping (at least when played in `ffplay`)

**Comment by easyteacher** [comment]
What should be regarded as the default behavior, endless loop or loop only once?

**Comment by jzern** [comment]
Currently Chrome will ignore any edit lists and loop avifs infinitely. ffmpeg might need an update once the hints are added.

With `ffplay` and APNG/GIF you can use `-ignore_loop 0` to respect the loop value.

**Comment by vigneshvg** [comment]
`avifenc` now has a `--repetition-count` that lets you specify the number of loops.

Chrome will respect the loop count set by this option. I am not sure about `ffplay`. But that's outside the scope of this issue tracker.
