### ISSUE TITLE
Accessing image metadata without decoding

### ISSUE THREAD

**Issue by AurelC2G** [AOMediaCodec/libavif#35]
Right now, it is necessary to call `avifDecoderRead` prior to reading anything from the `avifImage`. However, there are cases when we may want to read some of the image's metadata without actually decoding the image data itself (pixel values). Such metadata includes:

* image dimensions
* depth
* color profile
* exif / xmp metadata
* potentially, whether there is an alpha plane

Could we add an api to make this possible? Ideally we would expose as much as we can without requiring anything from the codec.

**Comment by joedrago** [comment]
This path exists already. See the decoding sample in the readme which calls avifDecoderParse().

**Comment by joedrago** [comment]
I should clarify:

avifDecoderParse() is the function you are looking for, and it populates a bunch of members in avifDecoder prefixed with "container", which include the width, height, and depth. XMP and EXIF are also available after this call.

There is no guarantee that these values match the actual decoded image (if someone were being malicious), but they will be correct most of the time, and if they ever mismatch you can consider it an error.
