### ISSUE TITLE
Improve the comments for the 'itemID' and 'offset' fields of the avifDecodeSample struct

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#358]
Joe, could you improve the comments for the `itemID` and `offset` fields of the `avifDecodeSample` struct? Here is my proposed patch, but please edit it, especially the comment for `itemID`:

```
diff --git a/include/avif/internal.h b/include/avif/internal.h
index cd1a8d4..0a08088 100644
--- a/include/avif/internal.h
+++ b/include/avif/internal.h
@@ -100,8 +100,8 @@ typedef struct avifDecodeSample
     avifBool ownsData;
     avifBool partialData; // if true, data exists but doesn't have all of the sample in it
 
-    uint32_t itemID; // if non-zero, data comes from a mergedExtents buffer, not a file offset
-    uint64_t offset;
+    uint32_t itemID; // if non-zero, data comes from a mergedExtents buffer in an avifDecoderItem, not a file offset
+    uint64_t offset; // used only when itemID is zero, ignored and set to 0 when itemID is non-zero
     uint32_t size;
     avifBool sync; // is sync sample (keyframe)
 } avifDecodeSample;
```

The problem with the original comment for `itemID` is that it may not be clear what `mergedExtents` is when a reader first reads this comment. I tried to clarify it by pointing out that `mergedExtents` is a field in the `avifDecoderItem` struct, but maybe we could just say "data comes from an avifDecoderItem" or "data comes from an item."

As for `offset`, I was confused when I saw some code set it to 0. So I tried to document when `offset` is used and when it is ignored (and set to 0).

Thank you!

**Comment by joedrago** [comment]
I think your changes are reasonable, especially if they seem sufficient to remove the confusion you felt when you first saw the code.

https://github.com/AOMediaCodec/libavif/commit/0265cd7a10d1425cf42908458a0807e919195914
