### ISSUE TITLE
The meaning of the error code "AVIF_RESULT_NO_IO" is not clear

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#364]
When I first saw the new error code "AVIF_RESULT_NO_IO", its meaning was not clear to me. The corresponding error message is simply "No IO" and therefore does not help to explain this error condition.

After I read the implementation, I learned that this error code means an avifDecoder (or in the futre, an avifEncoder) object does not have an avifIO object associated with it, or the associated avifIO object does not have a read() or write() function defined.

Perhaps we can rename this error code or make its error message more informative?

For example, "AVIF_RESULT_IO_NOT_SET", which suggests avifDecoderSetIO*() has not been called. Or "AVIF_RESULT_NO_IO_OBJECT" or "AVIF_RESULT_NO_IO_READER", which clarifies what "IO" refers to.

**Comment by joedrago** [comment]
I'm on board with changing it to `AVIF_RESULT_IO_NOT_SET`.
