### ISSUE TITLE
Move avif_decode_fuzzer.cc from oss-fuzz/projects/libavif/ to the libavif project

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#366]
The fuzzer program avif_decode_fuzzer.cc lives in the oss-fuzz project right now. This is inconvenient when we change the prototype of a libavif function used by avif_decode_fuzzer.cc, because we can't update avif_decode_fuzzer.cc at the same time.

It would be good to move avif_decode_fuzzer.cc into the libavif project. I know oss-fuzz supports this setup, e.g., libaom's fuzzer program used to live in the oss-fuzz project but now lives in the libaom project (aom/examples/av1_dec_fuzzer.cc), but I don't know how to do this off the top of my head.

**Comment by joedrago** [comment]
This should be an easy one. If we simply commit `avif_decode_fuzzer.cc` into `/tests`, we can just change `build.sh` in the `oss-fuzz` repo to point at it instead and remove it from the oss-fuzz repo. I can do this.

**Comment by wantehchang** [comment]
Great! Thank you, Joe!
