### ISSUE TITLE
AVIF lossless worse than WebP lossless

### ISSUE THREAD

**Issue by cagelight** [AOMediaCodec/libavif#374]
Why does AVIF even bother having a lossless mode if it's going to be almost universally worse than WebP's? Isn't AVIF supposed to be superseding WebP? Why can't AVIF simply at least use WebP's lossless algorithm, which is an entirely different codepath? I know the simple answer is "just use WebP for lossless", but this seems like quite a flaw in AVIF's design if it has a lossless mode that nobody should ever use in the first place since it can't even beat its predecessor.

**Comment by joedrago** [comment]
This repo is just for the implementation of the AVIF standard, and has little say over the standard itself. If you'd like to raise this issue, please do it here:

https://github.com/AOMediaCodec/av1-avif/issues/

**Comment by cagelight** [comment]
My apologies, I've never brought up an issue with a standard before. Thank you for directing me.
