### ISSUE TITLE
Finish coverage implementation

### ISSUE THREAD

**Issue by joedrago** [AOMediaCodec/libavif#385]
The goal of the coverage code was to get as close to 100% coverage of read.c as possible for testing. To finish this, two big things must be added:

* `aviftest`'s IO tests must have a mechanism where it is legal for a file to fail (perhaps a naming convention on the loaded file that it is known to fail)
* A ton of carefully crafted AVIFs that will test each path in read.c (this is the tough one)

**Comment by vrabaud** [comment]
We are now at 40%. Coverage is complex as the current one cannot combine the gtest coverage, the executable coverage (executed through shell scripts) and the fuzzing coverage. So closing for now as this is an ever going progress.
