### ISSUE TITLE
Segfault on example

### ISSUE THREAD

**Issue by vladbondarenko** [AOMediaCodec/libavif#386]
Hi,

Trying to run example avif_example1.c but faced Segmantation Fault:

Steps to introduce:
1) git clone repo
2) mkdir build && cd build && cmake PATH_to_clone
3) make && make install (also with ldconfig)
4) cd ../examples
5) gcc avif_example1.c -lavif
6) ./a.out:
avif version: 0.8.2
Segmentation fault

cmake version 3.16.3
Debian10,Ubuntu16,AmazonLinux1 and AmazonLinux2 are segfaulting.

Any ideas?

**Comment by joedrago** [comment]
It doesn't appear that you're enabling any AV1 codecs via CMake, so you're very likely dying somewhere in the encoding steps. If you have `libaom` available on your system (say), you'd add `-DAVIF_CODEC_AOM=1` to your `cmake` commandline.

The examples need a bit of refactoring, and one of those updates can include protecting against running a libavif that wasn't compiled against any encoders/decoders, but this simple example assumes you are capable of both encoding and decoding.

**Comment by vladbondarenko** [comment]
Thats it, thanks!
