### ISSUE TITLE
Add a way to avoid libyuv in avifImageYUVToRGB() when converting YUV 4:4:4 to RGB

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#406]
Right now one can set the chromaUpsampling field of struct avifRGBImage to an appropriate value to avoid libyuv in avifImageYUVToRGB(). Since the chromaUpsampling field is ignored when converting YUV 4:4:4 to RGB, this method does not work for the YUV 4:4:4 format. It would be good to add a way to avoid libyuv in avifImageYUVToRGB() that is not tied to chrome upsampling.

**Comment by joedrago** [comment]
I did a quick audit of the logic after reading this, and technically you can avoid libyuv by simply asking for BEST_QUALITY on upsampling. It might be better to enforce this with an explicit bool in the future (`disableLibYUV` on `avifDecoder`, say), but the documentation in `avif.h` is very clear about when libyuv is used/avoided. I removed a snippet just now which was actually incorrect in the YUV444 case, though.

https://github.com/AOMediaCodec/libavif/commit/960d7a9f3fb599fc7dcb863abc9c3f392041c8c0
