### ISSUE TITLE
Support for jpeg files

### ISSUE THREAD

**Issue by cachila** [AOMediaCodec/libavif#409]
Hi, I'm using this lib to successfully convert my png files even with alpha channel. But I can't figure it out how to convert to avif from a jpeg file. Is this supported? 

Thanks

**Comment by wantehchang** [comment]
Hi cachila,

Yes, avifenc can convert a jpeg file to avif. It is automatic if the jpeg file has the file extension .jpg or .jpeg (case-insensitive).

**Comment by cachila** [comment]
Yes, thanks for the response. 

I closed it when I found what I was doing wrong.
