### ISSUE TITLE
Support clap, imir, irot property in ItemPropertyContainerBox

### ISSUE THREAD

**Issue by ledyba-z** [AOMediaCodec/libavif#41]
Hi!

@dreampiggy says that he or she wants to support rotation/mirroring/cropping in [SDImageAVIFCoder](https://github.com/SDWebImage/SDWebImageAVIFCoder), but I found that `imr`, `irot`, `clap` box (defined in [HEIF](https://www.iso.org/standard/66067.html)) is not recognized:

https://github.com/AOMediaCodec/libavif/blob/f9bba7d9934b8aefeb1d5f1a57c98ea809aebe50/src/read.c#L653-L679

[MIAF](https://www.iso.org/standard/74417.html) specification says that there are no transformation information in EXIF metadata in MIAF, so libavif might have to parse those boxes to handle transformation correctly.

> There is no need for a reader to understand the details of the metadata.
> There should be no image transformations expressed by Exif (rotation, mirroring, etc.) indicated in the Exif metadata, in files encoded according to this document. 
> [MIAF](https://www.iso.org/standard/74417.html), p16

Our avif parser implementation, [libavif-container](https://github.com/link-u/libavif-container) parses them, so please refer if you need.

https://github.com/link-u/libavif-container/blob/371ca8f421d1622065cd1f34e8d0abe0886cf259/src/avif/Parser.cpp#L231-L321

**Comment by ledyba-z** [comment]
FYI: I prepared the test images with rotation/mirroring/crop operations, so please use them:

https://github.com/link-u/avif-sample-images#kimono---transformation-tests

**Comment by novomesk** [comment]
Windows applications display 1080x1920 picture:
![Ronda_rotate90_IrfanView](https://user-images.githubusercontent.com/52529860/76085207-de33ac80-5fb1-11ea-8ded-d67402efbd54.png)
But we display 1920x1080:
![Ronda_rotate90_gimp](https://user-images.githubusercontent.com/52529860/76085217-e55aba80-5fb1-11ea-9b75-fcf90d73cbb6.png)
I think it is because of **irot**.
Testfile: https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Microsoft/Ronda_rotate90.avif
I can rotate the picture myself but I need some info that I should do it.

**Comment by joedrago** [comment]
I am in the middle of refactoring the RGB conversion, but after that I can surface the content of these boxes the way that I surface `container*` values right now.

**Comment by novomesk** [comment]
What a co-incidence. New testfiles appeared: https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles/Link-U

**Comment by ledyba-z** [comment]
I created those files, haha. Please use them!

**Comment by joedrago** [comment]
I've decided that it is libavif's responsibility to plumb through these boxes (both encode and decode), but I'm going to consider the implementation of these transformations to be an entirely separate thing . I could see offering optional convenience functions for people that directly manipulate the pixel buffers, but that isn't in scope for this specific issue.

I'm going to implement these boxes now and surface/honor them in avifImage. I'm hoping to have this in today, and they'll be available in v0.6.0.

**Comment by joedrago** [comment]
@ledyba-z Thanks for those test images; they were very useful in verifying my plumbing.
