### ISSUE TITLE
"Unrecognized file format" only based on file extension

### ISSUE THREAD

**Issue by vHeemstra** [AOMediaCodec/libavif#411]
When using `avifenc` to convert images (inside `gulp`), I got the "Unrecognized file format". This is because the input file is a temporary file that has no extension. Therefore [`avifGuessFileFormat`](https://github.com/AOMediaCodec/libavif/blob/d2b825486a0fb7dd4ff7f5ae91edfe58c66ec96b/apps/shared/avifutil.c#L70) can't figure out what type of file is used.

Is it possible to make this filetype guessing/checking function have a look at the actual contents? Similar to [this JS module](https://github.com/sindresorhus/file-type/blob/master/core.js), where it checks specific bytes depending on the expected filetype.

I believe that would make a great improvement on ease of use, as well as security (prevent usage of for example a PDF file that was just renamed to `.jpg`).

**Comment by joedrago** [comment]
Good idea. I took some of my signatures from `colorist` and dropped them in. Let me know if this fixes your issue.

**Comment by vHeemstra** [comment]
Great!
(I'm actually not that good at compiling the lib myself.. :) So when the Windows pre-built has the new version, I'll test it.

**Comment by joedrago** [comment]
This build should have it:

https://ci.appveyor.com/project/louquillio/libavif/builds/36364236/artifacts

**Comment by vHeemstra** [comment]
Yes! It worked
