### ISSUE TITLE
Disable clang's -Wswitch-enum warning

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#417]
I just added the following switch statement to src/reforma.c:

```
    switch (image->matrixCoefficients) {
        case AVIF_MATRIX_COEFFICIENTS_IDENTITY:
            state->mode = AVIF_REFORMAT_MODE_IDENTITY;
            break;
        case AVIF_MATRIX_COEFFICIENTS_YCGCO:
            state->mode = AVIF_REFORMAT_MODE_YCGCO;
            break;
        default:
            state->mode = AVIF_REFORMAT_MODE_YUV_COEFFICIENTS;
            break;
    }
```

When I compile this code with clang 7.0.1, I get the following compiler warning:

```
/opt/clang-7.0.1/bin/clang -DAVIF_CODEC_AOM=1 -DAVIF_CODEC_AOM_DECODE=1 -DAVIF_CODEC_AOM_ENCODE=1 -DAVIF_CODEC_SVT=1 -I../include -I../ext/SVT-AV1/include -I../ext/aom -g   -Weverything -Wno-bad-function-cast -Wno-cast-align -Wno-conversion -Wno-covered-switch-default -Wno-disabled-macro-expansion -Wno-documentation -Wno-documentation-unknown-command -Wno-double-promotion -Wno-float-equal -Wno-missing-noreturn -Wno-padded -Wno-sign-conversion -Wno-error=c11-extensions -Werror -pthread -std=gnu99 -MD -MT CMakeFiles/avif.dir/src/reformat.c.o -MF CMakeFiles/avif.dir/src/reformat.c.o.d -o CMakeFiles/avif.dir/src/reformat.c.o   -c ../src/reformat.c
../src/reformat.c:41:13: error: 12 enumeration values not explicitly handled in switch: 'AVIF_MATRIX_COEFFICIENTS_BT709', 'AVIF_MATRIX_COEFFICIENTS_UNSPECIFIED', 'AVIF_MATRIX_COEFFICIENTS_FCC'... [-Werror,-Wswitch-enum]
    switch (image->matrixCoefficients) {
            ^
1 error generated.
```

I think it is reasonable to use a default case in that switch statement. The -Wswitch-enum warning is too strict. I suggest we disable this warning.

Here is the documentation of this warning in GCC (for some reason gcc 10.2.0 does not emit this warning):

https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

> -Wswitch-enum
> 
> Warn whenever a switch statement has an index of enumerated type and lacks a case for one or more of the named codes of that enumeration. case labels outside the enumeration range also provoke warnings when this option is used. The only difference between -Wswitch and this option is that this option gives a warning about an omitted enumeration code even if there is a default label.

**Comment by joedrago** [comment]
Hmm, I'm split on this one. I agree with you that this warning can be a nuisance at times and effectively elminates all usefulness of the `default` case. That said, I do like it when it shows me all of the places I need to inspect if someone adds a new enum value.

I think if we turn this warning off, we should audit libavif's switch statements and perhaps remove all cases adjacent to `default`.

**Comment by wantehchang** [comment]
Joe: Are you worried the -Wswitch warning is not enough?

I remember those cases adjacent to a default case. Now I know why the default cases are there :-)

**Comment by vrabaud** [comment]
It seems this is not happening anymore
