### ISSUE TITLE
Avif image weird stretching

### ISSUE THREAD

**Issue by cachila** [AOMediaCodec/libavif#428]
Hi,

I am trying to convert the knife.jpeg image using `avifenc --min 30 --max 30 knife.jpeg knife.avif` but the resulting avif file is stretched weirdly. Am I doing something wrong?

![knife.jpeg](https://user-images.githubusercontent.com/5391176/100487106-be1abf00-30e5-11eb-97de-6c751b5338cf.jpeg)

![knife avif (screenshot)](https://user-images.githubusercontent.com/5391176/100486973-3fbe1d00-30e5-11eb-9157-858dcabe8c90.png)

I'll upload a zip file in case github changes de original image.
[knife.zip](https://github.com/AOMediaCodec/libavif/files/5609711/knife.zip)

PD: Feel free to change the title since I don't understand what is actually going on.

**Comment by joedrago** [comment]
This has to do with the JPEG decode of the source file for sure, and not the AVIF output. When I try to view or convert that source file with other tools (of mine), I get very similar errors:

![knife](https://user-images.githubusercontent.com/332342/100491615-db499080-30d9-11eb-99a1-bab6ad9638fb.png)

How was this JPEG created? It appears that Windows and Chrome are perfectly capable of decoding it correctly, so I'm sure I'm just missing something in my JPEG decode path.

**Comment by cachila** [comment]
I actually have no access to the source file and how was it created. 
I tried converting it to webp with imagemagick and the output was ok. Maybe I was missing some parameter on the avifenc tool.

Please let me know if there is something I can do to help you look into this issue.

**Comment by tongyuantongyu** [comment]
This JPEG file is using Grayscale colorspace, confirmed by imagemagick:
```
$ magick identify knife.jpeg
knife.jpeg JPEG 520x520 520x520+0+0 8-bit Gray 256c 5651B 0.000u 0:00.004
```

JPEG can store pixels in many colorspaces (see [here](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/c7ca521bc85b57d41d3ad4963c13fc0100481084/jccolor.c#L578)) and on decompress libjpeg will [try to be smart](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/c7ca521bc85b57d41d3ad4963c13fc0100481084/jdapimin.c#L126) and guess one for us, and in this case, Grayscale.

If we want to deal with RGB only, we can just tell libjpeg we want RGB explicitly, and that should be easy with an one-line patch.
```diff
diff --git a/apps/shared/avifjpeg.c b/apps/shared/avifjpeg.c
index e3719a8..7e5646b 100644
--- a/apps/shared/avifjpeg.c
+++ b/apps/shared/avifjpeg.c
@@ -66,6 +66,7 @@ avifBool avifJPEGRead(avifImage * avif, const char * inputFilename, avifPixelFor
     setup_read_icc_profile(&cinfo);
     jpeg_stdio_src(&cinfo, f);
     jpeg_read_header(&cinfo, TRUE);
+    cinfo.out_color_space = JCS_RGB;
     jpeg_start_decompress(&cinfo);

     int row_stride = cinfo.output_width * cinfo.output_components;
```

But there's also `AVIF_PIXEL_FORMAT_YUV400` so maybe converting to & from RGB is not necessary... and maybe there's some plan (#372) on accept YCbCr directly from jpeg? I'm not very sure.

For this issue, I made a pull request #429 to make libjpeg always output RGB samples as a triage.

**Comment by joedrago** [comment]
Ah, that's the issue. Thanks for the PR; I've merged it.

**Comment by cachila** [comment]
Thank you both. Worked like a charm.
