### ISSUE TITLE
Please add libavif to the OSS-Fuzz project.

### ISSUE THREAD

**Issue by dalecurtis** [AOMediaCodec/libavif#43]
This will ensure continuous fuzzing coverage for the project.

Documentation:
https://google.github.io/oss-fuzz/

Specifically you'd want to add a libavif folder here with the relevant configuration:
https://github.com/google/oss-fuzz/tree/master/projects

E.g., here's how dav1d and libaom have been added:
https://github.com/google/oss-fuzz/tree/master/projects/dav1d
https://github.com/google/oss-fuzz/tree/master/projects/libaom

**Comment by joedrago** [comment]
Hi Dale!

I took a stab at it and I have a PR open here:

https://github.com/google/oss-fuzz/pull/3302

I imagine there'll be some swirl here getting the corpus correct and coverage and whatnot, but this seems to work at a high level and is something we can tune.

**Comment by dalecurtis** [comment]
Thanks Joe!

**Comment by joedrago** [comment]
This is all done, closing this
