### ISSUE TITLE
Support for Centos 7 Linux Distribution

### ISSUE THREAD

**Issue by ksgulyani** [AOMediaCodec/libavif#431]
Pre compiled AVIF encoder (decoder optional) for centos 7 is needed.

Command - 
cmake -D AVIF_CODEC_AOM=on --build .

**Comment by 1480c1** [comment]
it would be more helpful if you said what exactly was the issue for centos 7 when compiling

**Comment by ksgulyani** [comment]
I am facing issues with dependencies - libgav1.
I was able to install libyuv but could not make libgav1 work.

**Comment by 1480c1** [comment]
Then you would have a better time reporting that to libgav1 here https://issuetracker.google.com/issues/new?component=750480&template=1355007, also you should probably mention what specifically you are having issues in libgav1 such as running the configure/cmake or doing a compile, etc

**Comment by ksgulyani** [comment]
How do I build avif with just AOM encoder? Why do I need libgav1 for the same?

**Comment by ksgulyani** [comment]
I was able to resolve the errors and build a static library for libavif (libavif.a). I was using ninja-build while all cmd mentioned ninja, hence the cmd scripts were failing.

**Comment by wantehchang** [comment]
ksgulyani: Glad to hear you resolved the build errors. I am going to close this issue then.
