### ISSUE TITLE
Failed to compile on MINGW using Clang due to -Wused-but-marked-unused

### ISSUE THREAD

**Issue by tongyuantongyu** [AOMediaCodec/libavif#435]
Clang warns every use of `printf` and `sprintf`, due to their declaration in MINGW headers is marked unused. (definition of `printf`: https://github.com/mirror/mingw-w64/blob/master/mingw-w64-headers/crt/stdio.h#L354 , definition of macro `__mingw_ovr`: https://github.com/mirror/mingw-w64/blob/master/mingw-w64-headers/crt/_mingw_mac.h#L290 ) 
This simple code can reproduce the problem:
```bash
clang -Weverything -Werror -x c - <<EOF
#include <stdio.h>

int main() {
    printf("");
}
EOF
```

Here's GCC's (https://gcc.gnu.org/onlinedocs/gcc-10.2.0/gcc/Common-Function-Attributes.html) and Clang's (https://clang.llvm.org/docs/AttributeReference.html#maybe-unused-unused) document of the `unused` attribute, and Clang's (https://releases.llvm.org/11.0.0/tools/clang/docs/DiagnosticsReference.html#wused-but-marked-unused) document of the diagnostic.

For solution, we either disable this warning by adding `-Wno-used-but-marked-unused`, or by adding definition `-D__USE_MINGW_ANSI_STDIO=0` (on this case MINGW headers use another definition of `*printf` which doesn't contain the `unused` attribute: https://github.com/mirror/mingw-w64/blob/master/mingw-w64-headers/crt/stdio.h#L561 ), but I'm feeling doing something wrong in both cases, so I created this issue.

**Comment by wantehchang** [comment]
Hi Yuan Tong,

Ideally we should ask the MINGW maintainers how they suggest we fix this compiler warning.

If you don't have time to do that, I suggest we disable the warning with -Wno-used-but-marked-unused. libavif itself does not use the 'unused' attribute, so this compiler warning is not useful to libavif right now. (In fact I think this compiler warning is only appropriate in some cases, and it can be manually enabled in those cases.)
