### ISSUE TITLE
Question about enabling libyuv or not

### ISSUE THREAD

**Issue by eclipseo** [AOMediaCodec/libavif#441]
What is the impact of enabling  or not enabling libyuv? Is there a difference of quality while up/down sampling from/to RGB/YUV? Or is it only speed related?

Thanks for your tine.

**Comment by tongyuantongyu** [comment]
Currently libyuv is only used in YUV->RGB conversion, so decoding only. It will be used if `--upsampling` parameter is not specified or set to automatic/fastest, if image depth is 8, and if libyuv can handle the combination of YUV format + MC + RGB format specified in AVIF file. Currently, libyuv do chroma upsampling using nearest method. (see https://bugs.chromium.org/p/libyuv/issues/detail?id=872)

If you wants best quality, specify `--upsampling best`, which currently uses bilinear, and gives better result than nearest. For the difference between the two, check this: https://bugs.chromium.org/p/chromium/issues/detail?id=1121579.

**Comment by linkboyx** [comment]
> Currently libyuv is only used in YUV->RGB conversion, so decoding only. It will be used if `--upsampling` parameter is not specified or set to automatic/fastest, if image depth is 8, and if libyuv can handle the combination of YUV format + MC + RGB format specified in AVIF file. Currently, libyuv do chroma upsampling using nearest method. (see https://bugs.chromium.org/p/libyuv/issues/detail?id=872)
> 
> If you wants best quality, specify `--upsampling best`, which currently uses bilinear, and gives better result than nearest. For the difference between the two, check this: https://bugs.chromium.org/p/chromium/issues/detail?id=1121579.

Hi, Would you @tongyuantongyu consider to use libyuv in RGBA/RGB->YUV for faster encoding speed? I really expect that.

I tested using libyuv through RGBA(android bitmap)->BGRA->J420, it may reduce 30~40ms on my Android phone.

This conversion looks not pretty, do you have a better solution? 

Thank you for your time.

**Comment by tongyuantongyu** [comment]
> Hi, Would you @tongyuantongyu consider to use libyuv in RGBA/RGB->YUV for faster encoding speed? I really expect that.
> 
> I tested using libyuv through RGBA(android bitmap)->BGRA->J420, it may reduce 30~40ms on my Android phone.

You can avoid `avifRGBImage` and call libyuv functions yourself to fill `avifImage` directly. libavif is just selecting the suitable function from libyuv.

> This conversion looks not pretty, do you have a better solution?

RGB->YUV part of libyuv doesn't support custom constant, so It's probably the best you can do for now.
