### ISSUE TITLE
Lossless + svt gets wrong colors

### ISSUE THREAD

**Issue by eclipseo** [AOMediaCodec/libavif#442]
When I run SVT with lossless quality:

`avifenc --lossless --tilecolslog2 1 -c svt -s d -y 420 -o test.avif subset1/08-2011._Panthera_tigris_tigris_-_Texas_Park_-_Lanzarote_-TP04.png`

I get a distorted image with wrong colors:
https://imgpile.com/images/uyxeyo.png

This does not happen if I use ` -min 0 -max 0`.

**Comment by tongyuantongyu** [comment]
This is not specific to SVT, just some wrong logic of avifenc in handling `--lossless`. A refactor has been planned as #226.

`--lossless` is just a shorthand of `--yuv 444 --min 0 --max 0 --minalpha 0 --maxalpha 0 --codec aom --cicp 1/13/0` (assuming ICC Profile not present), and it's generally a bad idea to override these settings, as only this combination (`--cicp` can be `x/x/0` or `x/x/8`) can provide what 'lossless' means.

For your case,  Section 6.4.2 of AV1 spec requires YUV444 for MC=0(IDENTITY) so avifenc tries to fix this conflict - unfortunately, after image has been read, colorspace converted and chroma downsampled, so avifenc can't do very much. avifenc changes MC to 6(BT601), just to created a format-correct file, but the meaning of planes are going to be misinterpreted.

I guess you want `--lossless` but also want to try out SVT-AV1? Currently only AOM can do lossless encoding, and SVT-AV1 can only do YUV420 which is possibly far from what you expected by saying 'lossless'.

**Comment by vrabaud** [comment]
The current command line returns:
```
./avifenc --lossless --tilecolslog2 1 -c svt -s d -y 420 -o test.avif ~/Downloads/08-2011._Panthera_tigris_tigris_-_Texas_Park_-_Lanzarote_-TP04.jpg
When set, the pixel format can only be 444 in lossless mode. 400 also works if the input is grayscale.
```
Without `-y 420`:
```
./avifenc --lossless --tilecolslog2 1 -c svt -s d -o test.avif ~/Downloads/08-2011._Panthera_tigris_tigris_-_Texas_Park_-_Lanzarote_-TP04.jpg
SVT-AV1 doesn't support lossless encoding yet: https://gitlab.com/AOMediaCodec/SVT-AV1/-/issues/1636
```
Without `-c svt`, it works:
```
./avifenc --lossless --tilecolslog2 1 -s d -o test.avif ~/Downloads/08-2011._Panthera_tigris_tigris_-_Texas_Park_-_Lanzarote_-TP04.jpg
Successfully loaded: /usr/local/google/home/vrabaud/Downloads/08-2011._Panthera_tigris_tigris_-_Texas_Park_-_Lanzarote_-TP04.jpg
AVIF to be written: (Lossless)
 * Resolution     : 5110x3407
 * Bit Depth      : 8
 * Format         : YUV444
 * Alpha          : Absent
 * Range          : Full
 * Color Primaries: 2
 * Transfer Char. : 2
 * Matrix Coeffs. : 0
 * ICC Profile    : Present (3144 bytes)
 * XMP Metadata   : Present (8412 bytes)
 * Exif Metadata  : Present (13344 bytes)
 * Transformations: None
 * Progressive    : Unavailable
Encoding with AV1 codec 'aom' speed [default], color quality [100 (Lossless)], alpha quality [100 (Lossless)], tileRowsLog2 [0], tileColsLog2 [1], 16 worker thread(s), please wait...

Encoded successfully.
 * Color AV1 total size: 26125386 bytes
 * Alpha AV1 total size: 0 bytes
Wrote AVIF: test.avif
```
