### ISSUE TITLE
Is it okay to ignore TransferCharacteristics and MatrixCoefficients?

### ISSUE THREAD

**Issue by ledyba-z** [AOMediaCodec/libavif#45]
Hi!

I found that `TransferCharacteristics` and `MatrixCoefficients` are retrieved from Sequence Header OBU, but not used for transformation from YUV to RGB or RGB to YUV.
https://github.com/AOMediaCodec/libavif/search?q=transferCharacteristics&unscoped_q=transferCharacteristics
https://github.com/AOMediaCodec/libavif/search?q=matrixCoefficients&unscoped_q=matrixCoefficients

However, according to [H.273](https://www.itu.int/rec/T-REC-H.273/en) (that is refered by AV1 Spec, `6.4.2. Color config semantics`), it seems `TransferCharacteristics` parameters are required to calculate YUV values (See equation 11~13). And also, there are multiple different conversion equations from RGB to YUV for each `MatrixCoefficients` (See equation 20-74).

In current implementation, only `ColorPrimaries` parameters are used for conversion.
https://github.com/AOMediaCodec/libavif/blob/master/src/colr.c#L142-L155
But, for example, the color primaries for `SMPTE ST 2085` is not defined in `ColorPrimaries`. I wonder what happens `SMPTE ST 2085 (11)`, `Rec. ITU-R BT.2020-2 (constant luminance) (10)` or `Rec. ITU-R BT.2100-0 ICtCp(14)` is specified for `MatrixCoefficients`... Can current implementation convert YUV between RGB correctly?

Is it really okay to ignore `TransferCharacteristics` and `MatrixCoefficients`?

I am not very familiar with color management....Please tell me!

**Comment by joedrago** [comment]
My YUV<->RGB conversion is very likely incomplete on some of those MatrixCoefficients cases, and in the subset that depend on the TransferCharacteristics, they might also be wrong. That said, I believe most of the most commonly used paths are correct, and I think typical YUV<->RGB conversion does not temporarily linearize with the transfer function. 

I'll mark this issue as "help wanted" in case someone wants to contribute solutions to some of the more interesting combinations. Long term, I'd prefer libyuv to support all of these combinations (including 12bpc) and I can replace reformat.c entirely with that library.

**Comment by ledyba-z** [comment]
Thank you for replying! 
I will survey about other project. And if I can find some information or solutions, I will share them.

> Long term, I'd prefer libyuv to support all of these combinations (including 12bpc) and I can replace reformat.c entirely with that library.

Yeah, I also really want to replace YUV <-> RGB conversion functions with libyuv also in our implementations...

**Comment by joedrago** [comment]
As a note, you are never required to use libavif's YUV<->RGB ever, they are just provided for convenience. libavif can be used entirely with just the YUV planes in both directions, and you can convert to RGB completely independent of libavif.

**Comment by ledyba-z** [comment]
Thanks for notice!

Yeah, we use Apple's [vImage Frameworks](https://developer.apple.com/documentation/accelerate/conversion?language=objc) for iPhones (of course, they are only available in iOS or macOS).

**Comment by ledyba-z** [comment]
I found that [H.273](https://www.itu.int/rec/T-REC-H.273/en) (refered by AV1-spec) specify about conversion.

In a nutshell, just MatrixCoefficients affects a conversion matrix.

**Comment by joedrago** [comment]
With your recent accepted PR, I'm going to close this. Thanks for the code.

**Comment by ValZapod** [comment]
Actually, with BT.2020-CL transfer is inserted into matrix and with Chromaticity-derived luminance systems matrix does not matter at all (except that it signals it is Chromaticity-derived luminance system), since the matrix is directly dervied from primaries. Also ICtCp uses more complex 2 level insertion of transfer and primaries to allow from CL and CI.
