### ISSUE TITLE
Should libavif do bounds checks when reading transferCharacteristics and matrixCoefficients ?

### ISSUE THREAD

**Issue by tsdgeos** [AOMediaCodec/libavif#461]
From looking at avifParseColourInformationBox i see that they are read as a uint16_t and directly assigned to the respective fields, but the actual valid enums values are actually smaller than that.

We're running fuzzing on test on top of libavif and we have some Invalid-enum-value warnings because 
`   runtime error: load of value 251, which is not a valid value for type 'avifTransferCharacteristics'`

I guess we can try to check this at our level, but probably makes more sense to check it on libavif?

**Comment by wantehchang** [comment]
Thank you for the bug report. This is a tough question. Strictly speaking, the "invalid" values are reserved and may be used in the future. If a version of libavif is deployed for many years without update, it may actually see a previously reserved value being used in the future, so libavif needs to handle reserved values properly.

If we want avifTransferCharacteristics to remain an enum type, we can do something like this:

```
typedef enum avifTransferCharacteristics
{
    // This is actually reserved, but libavif uses it as a sentinel value.
    AVIF_TRANSFER_CHARACTERISTICS_UNKNOWN = 0,

    AVIF_TRANSFER_CHARACTERISTICS_BT709 = 1,
    AVIF_TRANSFER_CHARACTERISTICS_UNSPECIFIED = 2,
    AVIF_TRANSFER_CHARACTERISTICS_BT470M = 4,  // 2.2 gamma
    AVIF_TRANSFER_CHARACTERISTICS_BT470BG = 5, // 2.8 gamma
    AVIF_TRANSFER_CHARACTERISTICS_BT601 = 6,
    AVIF_TRANSFER_CHARACTERISTICS_SMPTE240 = 7,
    AVIF_TRANSFER_CHARACTERISTICS_LINEAR = 8,
    AVIF_TRANSFER_CHARACTERISTICS_LOG100 = 9,
    AVIF_TRANSFER_CHARACTERISTICS_LOG100_SQRT10 = 10,
    AVIF_TRANSFER_CHARACTERISTICS_IEC61966 = 11,
    AVIF_TRANSFER_CHARACTERISTICS_BT1361 = 12,
    AVIF_TRANSFER_CHARACTERISTICS_SRGB = 13,
    AVIF_TRANSFER_CHARACTERISTICS_BT2020_10BIT = 14,
    AVIF_TRANSFER_CHARACTERISTICS_BT2020_12BIT = 15,
    AVIF_TRANSFER_CHARACTERISTICS_SMPTE2084 = 16, // PQ
    AVIF_TRANSFER_CHARACTERISTICS_SMPTE428 = 17,
    AVIF_TRANSFER_CHARACTERISTICS_HLG = 18,
    AVIF_TRANSFER_CHARACTERISTICS_RESERVED19 = 19,
    AVIF_TRANSFER_CHARACTERISTICS_RESERVED20 = 20,
    ...
    AVIF_TRANSFER_CHARACTERISTICS_RESERVED255 = 255,
} avifTransferCharacteristics;
```

However, that is extremely tedious. I wonder if the following would be a reasonable solution:

```
typedef uint8_t avifTransferCharacteristics;
enum
{
    // This is actually reserved, but libavif uses it as a sentinel value.
    AVIF_TRANSFER_CHARACTERISTICS_UNKNOWN = 0,

    AVIF_TRANSFER_CHARACTERISTICS_BT709 = 1,
    AVIF_TRANSFER_CHARACTERISTICS_UNSPECIFIED = 2,
    AVIF_TRANSFER_CHARACTERISTICS_BT470M = 4,  // 2.2 gamma
    AVIF_TRANSFER_CHARACTERISTICS_BT470BG = 5, // 2.8 gamma
    AVIF_TRANSFER_CHARACTERISTICS_BT601 = 6,
    AVIF_TRANSFER_CHARACTERISTICS_SMPTE240 = 7,
    AVIF_TRANSFER_CHARACTERISTICS_LINEAR = 8,
    AVIF_TRANSFER_CHARACTERISTICS_LOG100 = 9,
    AVIF_TRANSFER_CHARACTERISTICS_LOG100_SQRT10 = 10,
    AVIF_TRANSFER_CHARACTERISTICS_IEC61966 = 11,
    AVIF_TRANSFER_CHARACTERISTICS_BT1361 = 12,
    AVIF_TRANSFER_CHARACTERISTICS_SRGB = 13,
    AVIF_TRANSFER_CHARACTERISTICS_BT2020_10BIT = 14,
    AVIF_TRANSFER_CHARACTERISTICS_BT2020_12BIT = 15,
    AVIF_TRANSFER_CHARACTERISTICS_SMPTE2084 = 16, // PQ
    AVIF_TRANSFER_CHARACTERISTICS_SMPTE428 = 17,
    AVIF_TRANSFER_CHARACTERISTICS_HLG = 18
};
```

**Comment by tsdgeos** [comment]
I guess you didn't ask for my opinion since my knowledge of this whole thing is very limited :)

From a point of view of someone that knows nothing adding all those AVIF_TRANSFER_CHARACTERISTICS_RESERVEDXX doesn't seem great since what do you do when it stops being reserved? Remove the enum? That's technically source incompatible. Keep the enum add add another one with the same = XX value? That's ok but kind of ugly.

**Comment by wantehchang** [comment]
Hi tsdgeos,

Thank you for your comment. Since you reported the bug, I am interested in knowing your opinion.

I agree the AVIF_TRANSFER_CHARACTERISTICS_RESERVED* solution is a bad idea. It is not practical, because we will need to deal with three enum types this way. Let's abandon this solution.

In my second solution, the avifTransferCharacteristics type becomes a non-enum type (an alias for uint8_t), and the AVIF_TRANSFER_CHARACTERISTICS_* enumeration constants are defined in an 'enum' block without a tag:

```
typedef uint8_t avifTransferCharacteristics;
enum
{
    // This is actually reserved, but libavif uses it as a sentinel value.
    AVIF_TRANSFER_CHARACTERISTICS_UNKNOWN = 0,

    AVIF_TRANSFER_CHARACTERISTICS_BT709 = 1,
    AVIF_TRANSFER_CHARACTERISTICS_UNSPECIFIED = 2,
    AVIF_TRANSFER_CHARACTERISTICS_BT470M = 4,  // 2.2 gamma
    AVIF_TRANSFER_CHARACTERISTICS_BT470BG = 5, // 2.8 gamma
    AVIF_TRANSFER_CHARACTERISTICS_BT601 = 6,
    AVIF_TRANSFER_CHARACTERISTICS_SMPTE240 = 7,
    AVIF_TRANSFER_CHARACTERISTICS_LINEAR = 8,
    AVIF_TRANSFER_CHARACTERISTICS_LOG100 = 9,
    AVIF_TRANSFER_CHARACTERISTICS_LOG100_SQRT10 = 10,
    AVIF_TRANSFER_CHARACTERISTICS_IEC61966 = 11,
    AVIF_TRANSFER_CHARACTERISTICS_BT1361 = 12,
    AVIF_TRANSFER_CHARACTERISTICS_SRGB = 13,
    AVIF_TRANSFER_CHARACTERISTICS_BT2020_10BIT = 14,
    AVIF_TRANSFER_CHARACTERISTICS_BT2020_12BIT = 15,
    AVIF_TRANSFER_CHARACTERISTICS_SMPTE2084 = 16, // PQ
    AVIF_TRANSFER_CHARACTERISTICS_SMPTE428 = 17,
    AVIF_TRANSFER_CHARACTERISTICS_HLG = 18
};
```

We will need this kind of solution if we want to store an invalid or reserved value in a variable or struct field of the avifTransferCharacteristics type. In this approach, libavif and its clients will need to validate an avifTransferCharacteristics variable or struct field before using it.

Alternatively, we can first validate a value and then only store a valid value in a variable or struct field of the avifTransferCharacteristics type. Then avifTransferCharacteristics can remain an enum type.

**Comment by tsdgeos** [comment]
> Alternatively, we can first validate a value and then only store a valid value in a variable or struct field of the avifTransferCharacteristics type. Then avifTransferCharacteristics can remain an enum type.

I honestly think this makes more sense.

On your initial comment you say "If a version of libavif is deployed for many years without update, it may actually see a previously reserved value being used in the future, so libavif needs to handle reserved values properly."

But to me this seems like a time travelling kind of problem. If i build code nowadays with the current libavif code, i can't predict what those new enums witll be and handle them in my code. If/when those values get meaning and i start handling them in my code why would i keep using an old libavif version that doesn't know about those values?

**Comment by wantehchang** [comment]
Hi tsdgeos,

There are several reasonable ways to handle a reserved value. For example, if reserved values will only ever be used for optional features, then it is reasonable to specify that a decoder shall ignore a reserved value. In general, a decoder can treat a reserved value as an invalid value, or a decoder can display a reserved value but take care to not use it.

Since the transfer characteristics function value is not used by libavif, one can argue that libavif should still decode the image and faithfully record the unknown/invalid transfer characteristics function value, and let the client decide what to do with the decoded image and the transfer characteristics function.

**Comment by wantehchang** [comment]
> There are several reasonable ways to handle a reserved value. For example, if reserved values will only ever be used for optional features, then it is reasonable to specify that a decoder shall ignore a reserved value. In general, a decoder can treat a reserved value as an invalid value, or a decoder can display a reserved value but take care to not use it.

I just wanted to emphasize one point that may be unclear in my previous comments. Note that none of the decoder behaviors I described above use a reserved value. When I say "handle reserved values properly", I don't mean "use reserved values". I mean that it may be reasonable to ignore or to record (but not use) reserved values, rather than treat them as errors.

**Comment by joedrago** [comment]
I should probably weigh in on this conversation. I think switching it to a `uint8_t` and documenting that it can signal any legal value from CICP is probably the right play. the enum will then just be for convenience/readability, and people will know that they have to have a fallback/default case in their own handling.

**Comment by novomesk** [comment]
@joedrago If you want to change the NCLX emus to uint8_t, I suggest to do it together with other big changes.

For example good opportunity is now, because of the premultiplied format support.

**Comment by joedrago** [comment]
They're now `uint16_t` now (as they are inside of the `nclx` box), along with a beefy comment above them in the header explaining why.

**Comment by novomesk** [comment]
I use `AVIF_API void avifColorPrimariesGetValues(avifColorPrimaries acp, float outPrimaries[8]);` in my code.

Now, when the type changed from `avifColorPrimaries` to `uint16_t`, should be the acp parameter in avifColorPrimariesGetValues changed too?

In one program I use `avifColorPrimariesFind` too, but without using the return value (only to detect name via `const char ** outName`)

**Comment by joedrago** [comment]
Ah, yes, it should be. My intent is to make the enum just constants. I should probably remove the actual enum/typedef itself and just make it a big pile of constants. I'll fix it tomorrow.

**Comment by joedrago** [comment]
Alright, that latest change should cover it. Those 3 enums no longer exist, and should be treated as `uint16_t` everywhere now. Hopefully this paves the way for future compatibility if/when H.273 gains a few new enums, and should answer the question on bounds checking these values in the first place.

**Comment by wantehchang** [comment]
Joe: We don't need to remove the avifColorPrimaries, avifTransferCharacteristics. and avifMatrixCoefficients types. They can be defined as typedefs, to make code more readable:

```
typedef uint16_t avifColorPrimaries;
typedef uint16_t avifTransferCharacteristics;
typedef uint16_t avifMatrixCoefficients;
```

H.273 specifies that these three types all have the range of 0-255, so uint8_t could be used. (I know the uint16_t type comes from the ISO BMFF colr box.)

**Comment by wantehchang** [comment]
Joe: I wrote a pull request to define those types as aliases of uint16_t. You can take a look and see if you like the typedefs. (It's better to see it concretely.)
