### ISSUE TITLE
avifenc and avifEncoderCreate() have different default encoder speeds

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#481]
I just realized that the avifenc program and the C API function avifEncoderCreate() have different default encoder speeds. This is a little confusing.

avifEncoderCreate() sets the default encoder speed to AVIF_SPEED_DEFAULT (-1), which means "use the codec's default encoder speed". The default encoder speed of libaom is 0, the slowest speed (but highest compression efficiency).

avifenc sets the default encoder speed to 6 (was 8 before).

I am not sure if this is by design.

**Comment by joedrago** [comment]
It is more the opposite: a non-goal to ensure that the defaults of the library/API correspond to any commandline tools. 

The defaults in avifenc/avifdec are mostly my opinion and observations for newcomers. Anyone actually using avifenc/avifdec in some sort of downstream tool or recipe is likely to override these defaults; I'm just trying to help people trying out avifenc for the first time with "avifenc foo.png foo.avif" to not make a bad decision. 

Putting those opinions at the API level felt bad to me, so I just set them to either codec defaults, or extremes (lossless, etc). Users of the actual library should be making informed decisions on these things.

**Comment by wantehchang** [comment]
Joe: Thank you for confirming this is by design.
