### ISSUE TITLE
ipma box parsing accepts invalid inputs

### ISSUE THREAD

**Issue by baumanj** [AOMediaCodec/libavif#485]
Per HEIF (ISO 23008-12:2017) § 9.3.1, there are several forms of technically invalid input that libavif currently accepts (and  mp4parse does not). With each, I've provided a test file which demonstrates the issue and a link to the code that enforces the requirement in mp4parse.

1. "flags should be equal to 0 unless there are more than 127 properties in the ItemPropertyContainerBox" [[file](https://github.com/mozilla/mp4parse-rust/blob/3011a2b923c8b0f1b392bcdd008cd8b95ffd846b/mp4parse/tests/corrupt/bad-ipma-flags.avif)] [[code](https://github.com/mozilla/mp4parse-rust/blob/3011a2b923c8b0f1b392bcdd008cd8b95ffd846b/mp4parse/src/lib.rs#L1759)]
1. "The version 0 should be used unless 32-bit item_ID values are needed" [[file](https://github.com/mozilla/mp4parse-rust/blob/master/mp4parse/tests/corrupt/bad-ipma-version.avif)] [[code](https://github.com/mozilla/mp4parse-rust/blob/3011a2b923c8b0f1b392bcdd008cd8b95ffd846b/mp4parse/src/lib.rs#L2022)]
1. "There shall be at most one `ItemPropertyAssociationbox` with a given pair of values of version and flags." [[file](https://github.com/AOMediaCodec/libavif/files/6224428/ipma-duplicate-version-and-flags.avif.zip)] [[code](https://github.com/mozilla/mp4parse-rust/blob/e8be415ca3b4793fe88225238ba5ef4a95cb6b55/mp4parse/src/lib.rs#L1787)]

**Comment by rbouqueau** [comment]
PS: the shall is implemented, but the should are not.

**Comment by joedrago** [comment]
1 and 2 are "should", so I'm not going to implement those, as they'd be warnings. I'll implement 3 now.

**Comment by joedrago** [comment]
That's good, more info from the warden is always good.

To be clear, libavif's encoder always emits a valid ipma, this issue is just adding restrictions to the decoder.

**Comment by rbouqueau** [comment]
FYI v27 released: https://gpac.github.io/ComplianceWarden-wasm/avif.html
