### ISSUE TITLE
 Compilation error due to file name

### ISSUE THREAD

**Issue by Digitalizer** [AOMediaCodec/libavif#488]
Develop a project that uses several external libraries.
File names with the same name among external libraries cause compilation errors.
For example, utils.c, read.c, write.c, stream.c, etc.
I think it can be solved by adding avif_.

**Comment by joedrago** [comment]
Typically, modern build systems will emit `.o` files for each source subdir into its own destination subdir. What build environment are you using? Certainly CMake (the officially supported build for libavif) does this.

**Comment by Digitalizer** [comment]
Thanks for the quick reply.
I am using VS2019 without using CMake.
I am using libjpeg-turbo, libtiff, libpng, zlib, etc.
In my case I had a problem with utils.c.
In the case of VS2019, this is a problem that occurs when all .obj files are created in one output folder.

**Comment by Digitalizer** [comment]
Looking at the important libraries used in various environments, it seems that various prefixes are used.
libjpeg uses j, libtiff uses tif_, libpng uses png, and zlib uses zutil.c instead of util.c.
I think it's a way to avoid problems in many different environments.

**Comment by joedrago** [comment]
Hmm, I have mixed feelings on this one. 

On one hand, I think making such a change wouldn't be too significant for libavif, and I could probably live with it. We're only talking about 18 source files in a single directory.

On the other hand, I think you should consider another solution to this, as you're regularly going to run into this issue, and the whole notion is a bit outdated. For example, it is true that older libraries prefix their files as you say (and even some newer ones like libaom), but some don't. For example, you're going to run into the same issues with `dav1d` (which is the fastest way to actually decode the AV1 payload right now), or libgav1 (if you prefer this for Android). I'd be surprised if you could convince dav1d to budge on this one. 

I use VS2019 daily for my projects at work, and it certainly doesn't demand such a thing. Perhaps it is worth making some adjustments in your project?

**Comment by Digitalizer** [comment]
In my ongoing project I solved it by modifying another utils.cpp.
However, I talked about it because this could be a problem someday in other big projects.
This is not a functional problem, it is a compilation problem, and it is not important.
Still, libavif hasn't reached 1.0.0 yet, so I wondered if some changes were possible.
Thank you for your interest.

**Comment by wantehchang** [comment]
Yes, I also suspect this is a problem with the VS2019 project's setup. As a concrete example, the Chrome browser is a big project. Here are the files in the Chrome source tree named utils.c or utils.cc. It shows a big project like the Chrome source tree has no problem handling this. In particular, the ffmpeg library has eight files named utils.c:

```
~/chromium.1/src$ find . -name "utils.c*"
./jingle/glue/utils.cc
./chrome/browser/resource_coordinator/utils.cc
./chrome/browser/chromeos/power/auto_screen_brightness/utils.cc
./chrome/chrome_cleaner/logging/utils.cc
./extensions/browser/api/declarative_net_request/utils.cc
./extensions/browser/api/bluetooth_low_energy/utils.cc
./chromeos/services/assistant/public/shared/utils.cc
./chromeos/services/assistant/utils.cc
./components/update_client/utils.cc
./components/safe_browsing/core/common/utils.cc
./components/security_interstitials/content/utils.cc
./v8/test/inspector/utils.cc
./v8/src/utils/utils.cc
./v8/src/torque/utils.cc
./third_party/shaderc/src/cmake/utils.cmake
./third_party/tflite-support/src/tensorflow_lite_support/codegen/utils.cc
./third_party/private_membership/src/internal/utils.cc
./third_party/perfetto/src/base/test/utils.cc
./third_party/perfetto/src/base/utils.cc
./third_party/perfetto/tools/trace_to_text/utils.cc
./third_party/webrtc/examples/peerconnection/server/utils.cc
./third_party/tflite/src/tensorflow/core/grappler/clusters/utils.cc
./third_party/tflite/src/tensorflow/core/grappler/costs/utils.cc
./third_party/tflite/src/tensorflow/core/grappler/utils.cc
./third_party/tflite/src/tensorflow/core/grappler/inputs/utils.cc
./third_party/tflite/src/tensorflow/compiler/tf2tensorrt/convert/utils.cc
./third_party/tflite/src/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/utils.cc
./third_party/tflite/src/tensorflow/lite/delegates/utils.cc
./third_party/tflite/src/tensorflow/lite/delegates/gpu/common/testing/feature_parity/utils.cc
./third_party/tflite/src/tensorflow/lite/delegates/hexagon/utils.cc
./third_party/tflite/src/tensorflow/lite/tools/evaluation/utils.cc
./third_party/tflite/src/tensorflow/lite/experimental/support/codegen/utils.cc
./third_party/cld_3/src/src/utils.cc
./third_party/liblouis/src/liblouis/utils.c
./third_party/libavif/src/src/utils.c
./third_party/ffmpeg/libavutil/utils.c
./third_party/ffmpeg/libavdevice/utils.c
./third_party/ffmpeg/libswscale/utils.c
./third_party/ffmpeg/tests/utils.c
./third_party/ffmpeg/libavresample/utils.c
./third_party/ffmpeg/libavcodec/tests/utils.c
./third_party/ffmpeg/libavcodec/utils.c
./third_party/ffmpeg/libavformat/utils.c
./third_party/libwebp/src/utils/utils.c
./third_party/liburlpattern/utils.cc
./third_party/openh264/src/codec/common/src/utils.cpp
./third_party/nearby/src/cpp/core/internal/mediums/utils.cc
./third_party/libgav1/src/tests/utils.cc
./third_party/freetype-testing/src/fuzzing/src/utils/utils.cpp
```
