### ISSUE TITLE
The "Sanity check items" loop in avifDecoderParse() seems to be a no-op

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#490]
The `avifDecoderParse()` function has the following code:

```
    // Sanity check items
    for (uint32_t itemIndex = 0; itemIndex < decoder->data->meta->items.count; ++itemIndex) {
        avifDecoderItem * item = &decoder->data->meta->items.item[itemIndex];
        if (item->hasUnsupportedEssentialProperty) {
            // An essential property isn't supported by libavif; ignore the item.
            continue;
        }
    }
```

This for loop seems to have no side effects. I think we should either actually ignore items with an unsupported essential property, or delete this for loop.

**Comment by joedrago** [comment]
Yes, this loop is vestigial from when I added avifIO here:

https://github.com/AOMediaCodec/libavif/commit/be4cbb92c087349bdd0df35bd202a711e29f988d

It should be gone now.

**Comment by wantehchang** [comment]
Joe: Thank you for the fix!

**Comment by wantehchang** [comment]
Joe: Thank you for the fix!
