### ISSUE TITLE
Should we set cinfo.input_components to 4 when we set cinfo.in_color_space to JCS_EXT_RGBX?

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#502]
The `avifJPEGWrite()` function in apps/shared/avifjpeg.c has the following code:

```
#if defined(JCS_ALPHA_EXTENSIONS)
    cinfo.input_components = 3;
    cinfo.in_color_space = JCS_EXT_RGBX;
#else
    cinfo.input_components = 3;
    cinfo.in_color_space = JCS_RGB;
#endif
```

Should we set cinfo.input_components to 4 when we set cinfo.in_color_space to JCS_EXT_RGBX?

**Comment by joedrago** [comment]
@tongyuantongyu - Can you field this question, please?

**Comment by wantehchang** [comment]
Does cinfo.input_components = 3 tell the JPEG library to use only the first three components?

If this code is correct, maybe we can rewrite it as:

```
    cinfo.input_components = 3;
#if defined(JCS_ALPHA_EXTENSIONS)
    cinfo.in_color_space = JCS_EXT_RGBX;
#else
    cinfo.in_color_space = JCS_RGB;
#endif
```

**Comment by tongyuantongyu** [comment]
`avifJPEGWrite` has some wrongs I didn't caught (including the above one). I found them later, and while trying to solve them I'm feeling having these things in `avifjpeg.c` is wrong, so I moved them to conversion code, which resulted in #491. Could you take a look on that?

**Comment by wantehchang** [comment]
Fixed by https://github.com/AOMediaCodec/libavif/pull/505.
