### ISSUE TITLE
AVIF_COLOR_PRIMARIES_BT470M red primaries constants not accepted by Qt

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#522]
libavif defines red chromacity coordinates `0.67f, 0.33f` in https://github.com/AOMediaCodec/libavif/blob/master/src/colr.c

Qt do not accept these constants because they have following code:
```
    static bool isValidChromaticity(const QPointF &chr)
    {
        if (chr.x() < qreal(0.0) || chr.x() > qreal(1.0))
            return false;
        if (chr.y() <= qreal(0.0) || chr.y() > qreal(1.0))
            return false;
        if (chr.x() + chr.y() > qreal(1.0))
            return false;
        return true;
    }
```
The constants returned from libavif are rejected:
`QColorSpace attempted constructed from invalid primaries: QPointF(0.31,0.316) QPointF(0.67,0.33) QPointF(0.21,0.71) QPointF(0.14,0.08)`

Mathematicians say that 0.67 + 0.33 equals 1. But computer thinks that the result is something like `1.00000002980232238770` which is higher than `1.0`

You to solve the problem? Can we somehow pre-quantize the 0.67 and 0.33 values so together they will not be higher than 1 ?

**Comment by joedrago** [comment]
I recognize the issue the you're running into, but if Qt has an overly restrictive check in its code, I feel like any massaging of these numbers make more sense at the boundary between libavif and Qt, not inside of libavif. I would prefer that the values inside of libavif stay the exact values in the standards.

Perhaps before feeding them into Qt, check to see if adding them together exceeds 1, and if so, subtract the amount over 1 from one of the coordinates?

**Comment by novomesk** [comment]
I will set the Y to `1.0f - 0.67f` and Qt will be happy.
Y before:
`0.3300000131130218505859375`
Y after:
`0.3299999833106994628906250`
