### ISSUE TITLE
12-Bit support?

### ISSUE THREAD

**Issue by gitoss** [AOMediaCodec/libavif#524]
The current avifenc supports 12-bit encoding, but the current specs seem only to allow up to 10-bit - are you positive higher bit depth will get added to the spec  - or output a warning that the encoded image is not compliant? 

The spec https://aomediacodec.github.io/av1-avif/ currently is only up to "AVIF Advanced Profile" with "The AV1 profile shall be the High Profile and the level shall be 6.0 or lower." and high profile and level 6.0 instead of 5.1 for images seems to be just about the max tile size (7680x4320 instead of 3840x2160) 

From https://aomediacodec.github.io/av1-spec/av1-spec.pdf  "The Professional profile extends support over the High profile to also bitstreams with bit depth equal to 12, and also adds support for the 4:2:2 video format."

Btw it's nice to be able to encode 12bit with libavif, but I'm wondering about how this is going to work out.

**Comment by cconcolato** [comment]
There has been no real request in the past to specify a profile for 12b images. If there is enough interest, it could be added to the spec. For now, the spec does not forbid packaging 12b images in AVIF. It just means that if the image is 12b, no specific profile (Basic or Advanced) can be signaled.

**Comment by gitoss** [comment]
Well, how does one show interest for a 12bit avif profile? :-)

I'm pretty sure there is a lot... for video 12bit might not matter that much, but the lack of it for image compression is a much more significant competitive disadvantage: 
https://cloudinary.com/blog/time_for_next_gen_codecs_to_dethrone_jpeg?utm_source=reddit&utm_medium=social&utm_campaign=time-for-next-gen-codecs-to-dethrone-jpeg

Plus, without an official profile 12bit avif could be and is seen as a 'hack' - see the discussions on reddit.com/r/av1

**Comment by cconcolato** [comment]
> Well, how does one show interest for a 12bit avif profile? :-)

You just started :) I'd suggest describing the use cases a bit more and asking people to do the same in this issue and to +1 your request. This can be discussed in the working group.

> Plus, without an official profile 12bit avif could be and is seen as a 'hack' - see the discussions on reddit.com/r/av1
We have some official 12b images in our test suite, see for example:
https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles/Link-U

**Comment by joedrago** [comment]
FWIW, the best place to advocate for AVIF standards changes is the [av1-avif](https://github.com/AOMediaCodec/av1-avif/) repo.

**Comment by gitoss** [comment]
Will do. I created a post on reddit with a link to this ticket: https://www.reddit.com/r/AV1/comments/lroh37/support_the_addition_of_a_12bit_professional/

**Comment by joedrago** [comment]
Can you please recreate this issue in the av1-avif repo? This repo is simply for the C implementation of the AVIF standard. This isn't the right place to do this.

**Comment by gitoss** [comment]
> FWIW, the best place to advocate for AVIF standards changes is the [av1-avif](https://github.com/AOMediaCodec/av1-avif/) repo.

ok, done and Link on reddit changed to https://github.com/AOMediaCodec/av1-avif/issues/128

**Comment by joedrago** [comment]
Thanks.
