### ISSUE TITLE
pkg-config file lacks dependency information

### ISSUE THREAD

**Issue by 1480c1** [AOMediaCodec/libavif#528]
Right now, the pc file that is generated lacks any `Requires:` fields so if I'm trying to link to libavif statically, I am required to supply `-laom` etc inside LDFLAGS manually and the .pc file has almost no use other than giving an indication that libavif exists

This is currently an issue with jpeg-xl since they try to link to libavif for their benchmark tool but fail on linking because of aom symbols.

**Comment by joedrago** [comment]
I suppose the Requires field would be dependent on which codecs we're choosing to build against, right?

**Comment by 1480c1** [comment]
Yep, it would probably just consist of adding a `@AVIF_PKG_CONFIG_REQUIRES@` and appending `aom`, `rav1e`, `SvtAv1Enc` etc as needed with spaces in between

**Comment by 1480c1** [comment]
This assumes the user of the pkg-config file has a proper system setup so pkg-config can find the other .pc files

**Comment by lazka** [comment]
I think you want `Requires.private:` if it's only needed for static linking.

**Comment by vrabaud** [comment]
I believe this has been fixed in https://github.com/AOMediaCodec/libavif/pull/1905
