### ISSUE TITLE
Working with Alpha Channels - Request for Help

### ISSUE THREAD

**Issue by ksgulyani** [AOMediaCodec/libavif#545]
I am using the basic avif conversion as follows (Input - width, height, quality, doAlpha, numComps & pixels) - 
```
    avifRGBImage rgb;
    avifImage * image = avifImageCreate(width, height, 8, AVIF_PIXEL_FORMAT_YUV420);
    avifRGBImageSetDefaults(&rgb, image);
    rgb.pixels=(uint8_t*)  pixels.ptr();
    rgb.rowBytes=numComps * width
    memset(rgb.pixels, 255, rgb.rowBytes * image->height);

    if (doAlpha) {
        rgb.format = AVIF_RGB_FORMAT_RGBA;
    } else {
        rgb.format = AVIF_RGB_FORMAT_RGB;
    }

    if (avifImageRGBToYUV(image, &rgb) != AVIF_RESULT_OK) {
        avifImageDestroy(image);
        //throw exception
    }

    avifRWData encodedData = AVIF_DATA_EMPTY;
    avifEncoder * encoder = NULL;
    encoder = avifEncoderCreate();
    encoder->codecChoice=AVIF_CODEC_CHOICE_AUTO;

    int min_quantizer, max_quantizer, alpha_quantizer;
    max_quantizer = AVIF_QUANTIZER_WORST_QUALITY * ( 100 - quality) / 100;
    min_quantizer = 0;
    alpha_quantizer = 0;

    if ( max_quantizer > 20 ) {
        min_quantizer = max_quantizer - 20;

        if (max_quantizer > 40) {
            alpha_quantizer = max_quantizer - 40;
        }
    }

    encoder->maxThreads = 2;
    encoder->minQuantizer = min_quantizer;
    encoder->maxQuantizer = max_quantizer;
    encoder->minQuantizerAlpha = 0;
    encoder->maxQuantizerAlpha = alpha_quantizer;
    encoder->speed = 8;

    if ( avifEncoderWrite(encoder, image, &encodedData) != AVIF_RESULT_OK) {
        avifEncoderDestroy(encoder);
        avifImageDestroy(image);
        //throw exception
    }

    avifEncoderDestroy(encoder);
    avifImageDestroy(image);
```

Normal avif works well. What all am I missing for images with alpha?

**Comment by joedrago** [comment]
This all looks reasonable. Are you aware that libavif avoids writing an alpha plane if the alpha plane is entirely opaque, as a missing alpha plane is assumed to be opaque?

Try this memset instead in your test code :

`memset(rgb.pixels, 128, rgb.rowBytes * image->height);`

Does this behave more in line with the way you expect, or is something else missing for you?

**Comment by ksgulyani** [comment]
Nope... 
Here is the output with simple AVIF
![image](https://user-images.githubusercontent.com/6462948/111617304-f23afc80-8808-11eb-9a5d-5063940f8329.png)
Here is the output with alpha
![image](https://user-images.githubusercontent.com/6462948/111617371-067ef980-8809-11eb-8ade-474c0cb0c54e.png)

**Comment by joedrago** [comment]
Oh, upon reread of your code I noticed that you are choosing your pixel format based on the "doAlpha" boolean, but that is changing the number of input channels. If you have three input channels, you should always use AVIF_RGB_FORMAT_RGB, and if you have four input channels you should always use AVIF_RGB_FORMAT_RGBA.

**Comment by wantehchang** [comment]
Yes, do check the value of `numComps` in this statement

`rgb.rowBytes=numComps * width`

If doAlpha is true, then `numComps` should be 4, not 3.

Another thing to check is whether the RGBA samples in your `pixels.ptr()` buffer are in the R, G, B, A order, i.e., `rgb.pixels[0]` is R, `rgb.pixels[1]` is G, `rgb.pixels[2]` is B, and `rgb.pixels[3]` is A.

I don't understand the memset call:

`memset(rgb.pixels, 255, rgb.rowBytes * image->height);`

**Comment by joedrago** [comment]
I was under the impression that they were trying to just write some test code that wrote out a bunch of white, opaque pixels with that memset call (I've certainly done that when trying out some new code). It was why I tried to get them to try 128 (gray + half opacity).

**Comment by ksgulyani** [comment]
Thanks. So here is what I did to get it working - 
(Input - width, height, quality, doAlpha, numComps & pixels) -
`
    avifRas = CreateRasForAvif(ras, doAlpha); 
    // Above function checks if alpha channel exists in Image raster
    // If exists & doAlpha is true, it copies alpha & RGB buffers in one buffer as RGBA. 
    // Else returns RGB buffer

    avifRGBImage rgb;
    avifImage * image = avifImageCreate(width, height, 8, AVIF_PIXEL_FORMAT_YUV420);
    avifRGBImageSetDefaults(&rgb, image);
    rgb.pixels=(uint8_t*)  pixels.ptr();
    rgb.rowBytes=avifRas.numComps() * avifRas.rect().wd();

    if (doAlpha && (avifRas.numComps() == 4)) {
        rgb.format = AVIF_RGB_FORMAT_RGBA;
    } else {
        rgb.format = AVIF_RGB_FORMAT_RGB;
    }

    if (avifImageRGBToYUV(image, &rgb) != AVIF_RESULT_OK) {
        avifImageDestroy(image);
        //throw exception
    }

    avifRWData encodedData = AVIF_DATA_EMPTY;
    avifEncoder * encoder = NULL;
    encoder = avifEncoderCreate();
    encoder->codecChoice=AVIF_CODEC_CHOICE_AUTO;

    int min_quantizer, max_quantizer, alpha_quantizer;
    max_quantizer = AVIF_QUANTIZER_WORST_QUALITY * ( 100 - quality) / 100;
    min_quantizer = 0;
    alpha_quantizer = 0;

    if ( max_quantizer > 20 ) {
        min_quantizer = max_quantizer - 20;

        if (max_quantizer > 40) {
            alpha_quantizer = max_quantizer - 40;
        }
    }

    encoder->maxThreads = 2;
    encoder->minQuantizer = min_quantizer;
    encoder->maxQuantizer = max_quantizer;
    encoder->minQuantizerAlpha = 0;
    encoder->maxQuantizerAlpha = alpha_quantizer;
    encoder->speed = 8;

    if ( avifEncoderWrite(encoder, image, &encodedData) != AVIF_RESULT_OK) {
        avifEncoderDestroy(encoder);
        avifImageDestroy(image);
        //throw exception
    }

    avifEncoderDestroy(encoder);
    avifImageDestroy(image);

    IgcBufSpec spec(encodedData.size);
    IgcBufBase::Ptr buf = IgcBufBase::Create(spec);
    memcpy(buf->buf(), encodedData.data,encodedData.size);
`
I am attaching the output of same image (with alpha channel) as output. Can someone confirm if the output is correct?
tree-alpha-alpha.avif -> Image with **alpha** channel rendered as **AVIF with alpha**
tree-noalpha-alpha.avif -> Image with **NO alpha** channel rendered as **AVIF with alpha**
tree-alpha-noalpha.avif -> Image with **alpha** channel rendered as **simple AVIF**
tree-noalpha-noalpha.avif -> Image with **NO alpha** channel rendered as **simple AVIF**

[tree.zip](https://github.com/AOMediaCodec/libavif/files/6170403/tree.zip)

**Comment by wantehchang** [comment]
Hi,

I didn't inspect the zip file you attached.

It is important that rgb.rowBytes and rgb.format be consistent with each other:

```
rgb.rowBytes=avifRas.numComps() * avifRas.rect().wd();

if (doAlpha && (avifRas.numComps() == 4)) {
    rgb.format = AVIF_RGB_FORMAT_RGBA;
} else {
    rgb.format = AVIF_RGB_FORMAT_RGB;
}
```

The condition `doAlpha && (avifRas.numComps() == 4)` seems to suggest that if is possible for `avifRas.numComps()` to be equal to 4 and for `doAlpha` to be false. If that combination is allowed, then we will set `rgb.rowBytes` and `rgb.format` to the following values:

`  rgb.rowBytes=4* avifRas.rect().wd();`

and

`    rgb.format = AVIF_RGB_FORMAT_RGB;`

Those two values are inconsistent with each other.

If it is impossible for `avifRas.numComps()` to be equal to 4 and for `doAlpha` to be false, then you can rewrite the if-else statement as follows to be clearer:

```
if (avifRas.numComps() == 4) {
    rgb.format = AVIF_RGB_FORMAT_RGBA;
} else {
    rgb.format = AVIF_RGB_FORMAT_RGB;
}
```

**Comment by ksgulyani** [comment]
Thanks. Yes I am aware of it... 
I handled that inside **avifRas = CreateRasForAvif(ras, doAlpha);**
Function checks if alpha channel exists in Image raster. If exists & doAlpha is true, it copies alpha & RGB buffers in one buffer as RGBA. Else returns RGB buffer.

```
CreateRasForAvif(ras, bool doAlpha)
{
    if ((! doAlpha )||(! ras.alphaEnabled()))
    {
        //return (ras)
    }
    else
    { 
        // Get the alpha buffer (alpha)

        // Create a "place holder" buffer which will contain both alpha and RGB (finalRas)
        
        // Now copy the data over from the two buffers (alpha, ras)
        
       // return final result (finalRas)
        
    }

```

Hence numComps will always be 3 if any one of the following is true - 
1. doAlpha is false
2. raster has no alpha buffer

Hence it does make sense to remove doAlpha check - 
```
if (avifRas.numComps() == 4) {
    rgb.format = AVIF_RGB_FORMAT_RGBA;
} else {
    rgb.format = AVIF_RGB_FORMAT_RGB;
}
```

**Comment by ksgulyani** [comment]
Also, can someone point me what would be the right way to map quality (0-100) with quantizers? Here is the code I picked up from loader.c [https://github.com/AOMediaCodec/libavif/blob/master/contrib/gdk-pixbuf/loader.c#L426-L436]
```
    int min_quantizer, max_quantizer, alpha_quantizer;
    max_quantizer = AVIF_QUANTIZER_WORST_QUALITY * ( 100 - quality) / 100;
    min_quantizer = 0;
    alpha_quantizer = 0;

    if ( max_quantizer > 20 ) {
        min_quantizer = max_quantizer - 20;

        if (max_quantizer > 40) {
            alpha_quantizer = max_quantizer - 40;
        }
    }
```

**Comment by wantehchang** [comment]
After the avifImageCreate() call, I suggest setting the following three fields in image to the current recommended values, otherwise they have the xxx_UNSPECIFIED values:
```
  image->colorPrimaries = AVIF_COLOR_PRIMARIES_BT709;
  image->transferCharacteristics = AVIF_TRANSFER_CHARACTERISTICS_SRGB;
  image->matrixCoefficients = AVIF_MATRIX_COEFFICIENTS_BT601;
```

The following statement can be omitted because `AVIF_CODEC_CHOICE_AUTO` is the default:
` encoder->codecChoice=AVIF_CODEC_CHOICE_AUTO;`

Regarding how to map a 0-100 quality factor to a 0-63 quantizer: ideally we should use a mapping table based on experiment results, but no such mapping table exists, so the linear interpolation is a very reasonable solution. The code you uses is correct, although it does assume AVIF_QUANTIZER_BEST_QUALITY is 0:

    `AVIF_QUANTIZER_WORST_QUALITY * ( 100 - quality) / 100`

This expression does not assume that:
    `AVIF_QUANTIZER_BEST_QUALITY + (AVIF_QUANTIZER_WORST_QUALITY - AVIF_QUANTIZER_BEST_QUALITY) * ( 100 - quality) / 100`

You can set the min and max quantizers to the same value. The code you copied uses higher-quality or lossless quantizers (i.e., smaller or zero quantizer values) for the alpha channel. I have less experience with the alpha channels, but there may be a good reason for that, so you can keep that policy.

**Comment by novomesk** [comment]
Mapping of quality to quantizers is a matter of experiments and personal opinions.
You may look at other implementations too:
https://github.com/joedrago/colorist/blob/master/lib/src/format_avif.c#L289
https://github.com/darktable-org/darktable/blob/master/src/imageio/format/avif.c#L482

Alpha channel should be compressed with higher quality, otherwise the transparent image looks weird. Some people think that alpha should be always lossless. When someone really wants to reach a small file, it is good to compress alpha a bit - otherwise other formats give better quality-vs-size results.

**Comment by joedrago** [comment]
Ad the author of the colorist variant, I fully admit that it is a naive attempt at mapping, and it is why I avoided it in libavif.

If you're always using libaom as the underlying encoder, I believe there is a way to ask for a constant quality using advanced parameters, and that might feel a lot more like a generic quality value.

**Comment by wantehchang** [comment]
Joe: The libaom-specific advanced parameter "cq-level" (constant/constrained quality level) is also a 0-63 quantizer value. Its advantage is that we don't need to deal with two quantizers (minQuantizer and maxQuantizer). But it is not a JPEG-style 0-100 quality factor.

**Comment by ksgulyani** [comment]
@wantehchang - Thanks I have added the fields - 
``` 
    avifRGBImage rgb;
    avifImage * image = avifImageCreate(width, height, depth, format);
    avifRGBImageSetDefaults(&rgb, image);
    image->colorPrimaries = AVIF_COLOR_PRIMARIES_BT709;
    image->transferCharacteristics = AVIF_TRANSFER_CHARACTERISTICS_SRGB;
    image->matrixCoefficients = AVIF_MATRIX_COEFFICIENTS_BT601;
    rgb.pixels=(uint8_t*)  pixels.ptr();
    rgb.rowBytes=avifRas.numComps() * avifRas.rect().wd();
```

**Comment by ksgulyani** [comment]
@wantehchang , @novomesk , @joedrago - Thanks for the inputs on quality. 
Earlier I was using this implementation - 
```
    max_quantizer = AVIF_QUANTIZER_WORST_QUALITY * ( 100 - quality) / 100;
    min_quantizer = 0;
    alpha_quantizer = 0;

    if ( max_quantizer > 20 ) {
        min_quantizer = max_quantizer - 20;

        if (max_quantizer > 40) {
            alpha_quantizer = max_quantizer - 40;
        }
    }
```
But the following implementation seemed more accurate on trying out with couple of images for mapping quality 1-100 when compared to JPEG & WEBP formats than the above one. 
```
    min_quantizer = AVIF_QUANTIZER_WORST_QUALITY - quality;
    if (min_quantizer < 0)
        min_quantizer = 0;

    max_quantizer = 100 - quality;
    if (max_quantizer > AVIF_QUANTIZER_WORST_QUALITY)
        max_quantizer = AVIF_QUANTIZER_WORST_QUALITY;

    alpha_quantizer = max_quantizer;

```
Thanks again for all the help :)

**Comment by ksgulyani** [comment]
I will be closing this issue since I was able to resolve the alpha channel & quality issues. Thanks everyone :)

**Comment by ksgulyani** [comment]
Just one more query if any of you know any idea - I see AVIF is still in pre-release stages. When is the plan for the first official one?

**Comment by wantehchang** [comment]
Hi ksgulyani,

> Just one more query if any of you know any idea - I see AVIF is still in pre-release stages. When is the plan for the first official one?

Did you mean the AVIF image format or the libavif library?

The AVIF image format  was released in 2019 (v1.0.0). The specification is being revised right now. The https://aomediacodec.github.io/av1-avif/ page shows a draft of the next version.

The libavif library still has a 0.x version number. It is common for new open-source libraries to use 0.x version numbers for a long time before they freeze the public API, so a 0.x version may be of production quality. This is the case for libavif.

**Comment by joedrago** [comment]
Yes. There are still a handful of unsupported features that are still being finalized and tested outside of libavif (layer selection, progressive, etc), and until I'm sure that we have proper interop with other non-libavif-based implementations (such as mp4parse-rust in FIrefox), it won't have a 1.0 tag. 

Once everyone agrees that the necessary features are all there, we've dialed in the right amount of "strictness" on the decoder to ensure valid files are being created everywhere, and there is some long window of stability, I'll probably tag whatever that long-standing 0.x release is as 1.0. It'll be a little while still.

**Comment by ksgulyani** [comment]
Thanks @joedrago @wantehchang. Yes I was talking about the release if libavif. Thanks a lot for all the help!
