### ISSUE TITLE
Question in avifImageYUVToRGB function

### ISSUE THREAD

**Issue by linkboyx** [AOMediaCodec/libavif#553]
function  avifImageYUVToRGB in reformat.c file:

If LibYUV used, then function returns at line 1051;  The premultipied or Unpremultiplied  at line 1139~1145 are not performed.

Is that desired?

**Comment by joedrago** [comment]
I suspect it is an oversight from when @tongyuantongyu added premultiplied support. Perhaps they can confirm.

**Comment by tongyuantongyu** [comment]
Yes this is a known issue, and my PR #530 solves it. @joedrago could you review that PR?

**Comment by joedrago** [comment]
#530 is now accepted, so this should be fixed.
