### ISSUE TITLE
avifDecoderNextImage() may return AVIF_RESULT_NO_IMAGES_REMAINING incorrectly on AV1 frame decoding error

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#556]
The error code `AVIF_RESULT_NO_IMAGES_REMAINING` means that we have decoded all the images in an AVIF file. I found that `avifDecoderNextImage()` may return `AVIF_RESULT_NO_IMAGES_REMAINING` incorrectly from this for loop:

```
    // Decode all tiles now that the sample data is ready.
    for (unsigned int tileIndex = 0; tileIndex < decoder->data->tiles.count; ++tileIndex) {
        avifTile * tile = &decoder->data->tiles.tile[tileIndex];

        const avifDecodeSample * sample = &tile->input->samples.sample[nextImageIndex];

        if (!tile->codec->getNextImage(tile->codec, sample, tile->input->alpha, tile->image)) {
            if (tile->input->alpha) {
                return AVIF_RESULT_DECODE_ALPHA_FAILED;
            } else {
                if (tile->image->width) {
                    // We've sent at least one image, but we've run out now.
                    return AVIF_RESULT_NO_IMAGES_REMAINING;
                }
                return AVIF_RESULT_DECODE_COLOR_FAILED;
            }
        }
    }
```

I run into this bug when I decode an AVIF file with the following properties:
- It is an image sequence.
- There are five images in the image sequence.
- The images at indexes 1, 2, 3 are not key frames, i.e., their 'sync' value is 0.
- The images at indexes 0, 1, 2 are correct. The image at index 3 has an AV1 bitstream error. Its temporal delimiter OBU has an obu_size of 106 but the first bit of the trailing bits is 0, not 1. NOTE: Since temporal delimiter OBUs have no payload data, all the 106 bytes are trailing bits and they should begin with a 1 bit, followed by all 0 bits.

I first call `avifDecoderNthImage()` with `index=0`. This call succeeds.

I then call `avifDecoderNthImage()` with `index=3`. This call internally calls `avifDecoderNextImage()` three times, which decode the images at indexes 1, 2, 3, respectively. The first two `avifDecoderNextImage()` calls succeed but the third `avifDecoderNextImage() `call fails because of the AV1 bitstream error.

Since `tile->image->width` is nonzero, `avifDecoderNextImage()` returns `AVIF_RESULT_NO_IMAGES_REMAINING`, as shown above. This error code is incorrect because we have not run out of images to decode. It should return `AVIF_RESULT_DECODE_COLOR_FAILED` instead.

I will write a pull request to remove the `if (tile->image->width)` statememt.

**Comment by joedrago** [comment]
Yes, that check is probably not necessary anymore, now that there is a loop prior to it which performs a superior check (and returns `AVIF_RESULT_NO_IMAGES_REMAINING`).
