### ISSUE TITLE
how to point cmake to libaom

### ISSUE THREAD

**Issue by silverhikari** [AOMediaCodec/libavif#559]
i have compile aom from github on linux, i am trying to figure out how to point libavif to it

**Comment by joedrago** [comment]
This should all be covered in the README, but I can be more specific if it helps:

If your goal is to find libaom as an installed system library, you simply need to offer `-DAVIF_CODEC_AOM=1` on the `cmake` commandline (along with any other options you want) to let it know to look for libaom in the system. 

If your goal is to make a fully _static_ build of libavif (and avifenc/avifdec), you can use the "local" scripts available in `ext/` to do that. For example:

    git clone https://github.com/AOMediaCodec/libavif.git
    cd libavif/
    cd ..
    cd libavif/ext/
    bash aom.cmd
    cd ..
    mkdir build
    cd build
    cmake -G Ninja -DBUILD_SHARED_LIBS=0 -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DAVIF_BUILD_APPS=1 ..
    ninja

The `build/` directory here will have `avifenc` and `avifdec` in it, and they'll depend on your system's versions of zlib, libpng, and libjpeg. (Those can also be made fully static with scripts in `ext/`).

I recommend leveraging your system's libraries, but I figured I'd explain both possibilities just in case.

**Comment by vrabaud** [comment]
With HEAD, you can now just install your libaom to whatever folder, set `AVIF_CODEC_AOM` to `SYSTEM` and make sure that your libaom is find_library-able by setting your https://cmake.org/cmake/help/latest/variable/CMAKE_LIBRARY_PATH.html#variable:CMAKE_LIBRARY_PATH . and https://cmake.org/cmake/help/latest/variable/CMAKE_INCLUDE_PATH.html#variable:CMAKE_INCLUDE_PATH
