### ISSUE TITLE
Re-enable cpu-used=7+ in codec_aom when a new libaom tagged release supports it 

### ISSUE THREAD

**Issue by joedrago** [AOMediaCodec/libavif#56]
This is a tracking bug to remove the artificial clamp on AOM's cpu-used when we get a new tagged release. (see comments near the top of `aomCodecEncodeImage`)

**Comment by novomesk** [comment]
Thanks Joe for solving this!

**Comment by EwoutH** [comment]
Any update on when this tag is coming? Otherwise maybe we should just pick a new commit later this week as new reference point.

**Comment by joedrago** [comment]
Nope. It is probably better just to ask the libaom repo directly.

**Comment by novomesk** [comment]
This [commit](https://aomedia.googlesource.com/aom/+/13e7da43d9fac85d2f644ea3611b8f80de687d35) indicate new speed 5 for realtime.
I don't understand it. AOM speed 5 will be used both for good quality and also for realtime?
The date indicate April 1st - hope it is not a joke.

**Comment by joedrago** [comment]
The SHA/tag in aom.cmd is only really meant to be informative, and used in my continuous builders. If you want to use a newer libaom on your local machine and reap the benefits of the new code, It is very likely to just compile and run. You should locally use whatever version you want. 

This goes for any Linux distribution as well; if Arch (or the like) wants to run the bleeding edge master branch, their API is quite stable and would likely play nicely with libavif's master branch. 

I like keeping those values up to date for CI purposes and making sure that I don't have to change my code, but the values in those files are not as rigid or important as you two suggest.

**Comment by EwoutH** [comment]
#160 unblocks this
