### ISSUE TITLE
Require zero or one Item Reference Box (iref) instances per MetaBox (meta)

### ISSUE THREAD

**Issue by baumanj** [AOMediaCodec/libavif#565]
Per ISOBMFF (ISO 14496-12:2015) § 8.11.12.1
> Container: Metadata box (‘meta’) Mandatory: No
> Quantity: Zero or one

This can be checked with the ComplianceWarden AVIF validator. [An example of invalid input](https://github.com/AOMediaCodec/libavif/files/6224372/2-iref-per-meta.avif.zip) is attached.

[mp4parse-rust already implements this check](https://github.com/mozilla/mp4parse-rust/blob/94c3b1f368c82aefcbf51967f6aa296a9ccceb69/mp4parse/src/lib.rs#L1572), so there is no corresponding issue.

**Comment by wantehchang** [comment]
This was already fixed in commit https://github.com/AOMediaCodec/libavif/commit/8f43909cf815d86220a35c7c0a12e8aa666de4fc.  The fix first appeared in libavif v0.8.2:

```
~/libavif/build$ git diff v0.8.2
~/libavif/build$ ./avifdec 2-iref-per-meta.avif output.png
Decoding with AV1 codec 'aom', please wait...
ERROR: Failed to decode image: BMFF parsing failed
```

We can close this issue.
