### ISSUE TITLE
Clarify quantizer settings

### ISSUE THREAD

**Issue by gitoss** [AOMediaCodec/libavif#571]
I did a benchmark and noticed an unexpected behaviour with setting min/max quantizer at the same or different values - it's either constant file size or not: [Benchmark: libaom 3.0.0 update cuts up to 60% avif encoding time](https://www.reddit.com/r/AV1/comments/migt5o/benchmark_libaom_300_update_cuts_up_to_60_avif/)

1. Avifenc min/max settings are rather unusual because other image encoders simply rely on a single quality setting - so what effect does it have to set different min/max values? Looking at the commit log https://github.com/AOMediaCodec/libavif/commit/5f86f969e188071e10773c16fc19e943f8d05220 this seems to be wip anyway with libaom's all-intra mode?

2. There are aom-specific advanced settings  'end-usage' and 'aq-mode' ... in the help it's not clear what appies to single-image encoding or only to image sequences.

=> Suggestion: Please clarify in the help (or at least in this git issue :-)) what same/different min/max quantizer settings result in, and what the libaom advanced settings do that are already listed in the help.

**Comment by gitoss** [comment]
This sheds some light on the settings: https://github.com/staxrip/staxrip/issues/361#issuecomment-705032898

**Comment by gitoss** [comment]
I've done a comparison with aq 1/2 - [Benchmark: 10bit avif encoding preferable to 8bit even for 8bit sources](https://www.reddit.com/r/AV1/comments/mj4dz7/benchmark_10bit_avif_encoding_preferable_to_8bit/)

**Comment by gitoss** [comment]
I'm closing this for now, will probably experiment further for myself to determine what the advanced libaom paramaters do...

**Comment by Hpsyche** [comment]
Hello, @gitoss.
I also encountered the same problem, after upgrading libaom to version 3.0.0, the image quality dropped a lot, do you have any insight now?

**Comment by wantehchang** [comment]
@Hpsyche I answered your question in https://github.com/strukturag/libheif/issues/895. What you observed was caused by a bug in libaom v2.0.0 (fixed by the change https://aomedia-review.googlesource.com/c/aom/+/113064). The image quality encoded by libaom v2.0.0 is higher than specified.
