### ISSUE TITLE
Include rav1e in release binaries

### ISSUE THREAD

**Issue by gitoss** [AOMediaCodec/libavif#573]
The rav1e lib seems to be quite competetive vs. libaom-av1 for still image encoding - it would be nice to have it included in release binaries. 

There are [up-to-date binaries on AppVeyor](https://ci.appveyor.com/project/louquillio/libavif), but they don't include rav1e yet either...

**Comment by joedrago** [comment]
I've enabled rav1e on AppVeyor builds, so rav1e encoding should be available in the next release. This turns a 9 minute build into a 28 minute build, but it is worth it for now. Someday I'll learn how to use `cargo` more efficiently and it won't take so long!

**Comment by 1480c1** [comment]
It might be worth looking into setting up [sccache](https://github.com/mozilla/sccache) (I personally haven't gotten it to work in good capacity on windows, so I'm not sure if I can help with it)
