### ISSUE TITLE
Findaom.cmake and Findrav1e.cmake mention dav1d

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#58]
Release tag: v0.5.6

Findaom.cmake and Findrav1e.cmake mention dav1d in the following code snippet:

find_package(PkgConfig QUIET)
if (PKG_CONFIG_FOUND)
    pkg_check_modules(_DAV1D dav1d)
endif (PKG_CONFIG_FOUND)

It looks like copy-and-paste errors. If it is correct, it would be good to add a comment to explain why we need to call pkg_check_modules(_DAV1D dav1d) when trying to discover the aom or rav1e package on the system.

**Comment by joedrago** [comment]
@cryptomilk Please advise!

**Comment by cryptomilk** [comment]
@wantehchang Thank you very much for the bug report. I've fixed it.
