### ISSUE TITLE
Guard the avifImageYUVToRGBLibYUV() call with alphaMultiplyMode == AVIF_ALPHA_MULTIPLY_MODE_NO_OP || avifRGBFormatHasAlpha(rgb->format)

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#587]
In src/reformat.c, the following code in `avifImageYUVToRGB()` is guarded with the conditional `alphaMultiplyMode == AVIF_ALPHA_MULTIPLY_MODE_NO_OP || avifRGBFormatHasAlpha(rgb->format)`:

```
        if ((!hasColor || (image->yuvFormat == AVIF_PIXEL_FORMAT_YUV444) || (chromaUpsampling == AVIF_CHROMA_UPSAMPLING_NEAREST)) &&
            (alphaMultiplyMode == AVIF_ALPHA_MULTIPLY_MODE_NO_OP || avifRGBFormatHasAlpha(rgb->format))) {
            // Explanations on the above conditional:
            // * None of these fast paths currently support bilinear upsampling, so avoid all of them
            //   unless the YUV data isn't subsampled or they explicitly requested AVIF_CHROMA_UPSAMPLING_NEAREST.
            // * None of these fast paths currently handle alpha (un)multiply, so avoid all of them
            //   if we can't do alpha (un)multiply as a separated post step (destination format doesn't have alpha).

            ...
        }
```

Before this block of code, `avifImageYUVToRGB()` has already tried avifImageYUVToRGBLibYUV():

```
    avifBool convertedWithLibYUV = AVIF_FALSE;
    avifResult libyuvResult = avifImageYUVToRGBLibYUV(image, rgb);
    if (libyuvResult == AVIF_RESULT_OK) {
        convertedWithLibYUV = AVIF_TRUE;
    } else {
        if (libyuvResult != AVIF_RESULT_NOT_IMPLEMENTED) {
            return libyuvResult;
        }
    }
```

Since `avifImageYUVToRGBLibYUV()` does not handle alpha (un)multiply, we should also avoid it if we can't do alpha (un)multiply as a separated post step (destination format doesn't have alpha). Therefore, I think we need to guard the `avifImageYUVToRGBLibYUV()` call with `alphaMultiplyMode == AVIF_ALPHA_MULTIPLY_MODE_NO_OP || avifRGBFormatHasAlpha(rgb->format)`.

**Comment by tongyuantongyu** [comment]
I agree with this, though currently `avifImageYUVToRGBLibYUV()` only handles formats that have alpha channel. There is `I420ToRGB24Matrix()` in libyuv that can output `AVIF_RGB_FORMAT_RGB` or `AVIF_RGB_FORMAT_BGR`, but currently it's not used by libavif.

**Comment by wantehchang** [comment]
Hi Yuan Tong,

Thank you for taking a look. It's good to have another person check my analysis.

If you have time, please write a pull request to add the conditional to the `avifImageYUVToRGBLibYUV(`) call (because you are more familiar with that code). Or I can try to write a pull request and ask you to review it.

**Comment by wantehchang** [comment]
Fixed by https://github.com/AOMediaCodec/libavif/pull/592. Thank you, Yuan Tong!
