### ISSUE TITLE
CMakeLists.txt uses DAV1D_INCLUDEDIR but Finddav1d.cmake defines DAV1D_INCLUDE_DIR

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#59]
Release tag: v0.5.6

Note: I wrote this bug report using DAV1D as an example, but the bug also applies to AOM and RAV1E.

I am not very familiar with CMake, so I may have misunderstood how Finddav1d.cmake is used. While reading CMakeLists.txt and Finddav1d.cmake I spotted three things that seem wrong.

1. CMakeLists.txt uses DAV1D_INCLUDEDIR but Finddav1d.cmake defines DAV1D_INCLUDE_DIR. Should CMakeLists.txt use DAV1D_INCLUDE_DIR instead?

2. Finddav1d.cmake defines both DAV1D_LIBRARY and DAV1D_LIBRARIES, but the comment at the top of the file does not mention DAV1D_LIBRARY:

```
  # - Try to find dav1d
  # Once done this will define
  #
  #  DAV1D_FOUND - system has dav1d
  #  DAV1D_INCLUDE_DIR - the dav1d include directory
  #  DAV1D_LIBRARIES - Link these to use dav1d
```

3. The comment I quoted above suggests DAV1D_LIBRARIES should be used, but CMakeLists.txt uses DAV1D_LIBRARY:

        set(AVIF_CODEC_LIBRARIES ${AVIF_CODEC_LIBRARIES} ${DAV1D_LIBRARY})

Should CMakeLists.txt use DAV1D_LIBRARIES instead?

**Comment by joedrago** [comment]
@cryptomilk Please advise (again, sorry)!

**Comment by cryptomilk** [comment]
1. Is a bug

2. and 3. are not a bug, it is only one library so both variable point to the same one.

**Comment by cryptomilk** [comment]
@wantehchang Thank you very much for the bug report. I've fixed it.
