### ISSUE TITLE
Enable tune butteraugli support

### ISSUE THREAD

**Issue by Lee-lithium** [AOMediaCodec/libavif#622]
Version: 0.9.0 (dav1d [dec]:0.8.2-0-gf06148e, aom [enc/dec]:3.1.0, rav1e [enc]:0.4.1 (v0.4.1))
https://ci.appveyor.com/project/louquillio/libavif  
Sorry, my english is not good

I think this issue is for libavif tune butteraugli, so i open a new issue,  
On libavif 0.9.0(aom 3.1.0), i try to pass -a tune=butteraugli parameter to libavif,  
but this parameter can't success pass, How to enable tune butteraugli support on libavif 0.9.0?

> avifenc --min 6 --max 6 --minalpha 0 --minalpha 0 -d 10 -s 4 -j 12 --cicp 1/13/8 -a end-usage=q -a cq-level=6 -a tune=butteraugli  
  
> When used with libaom 3.0.0 or later, any key-value pairs supported  
> by the aom_codec_set_option() function can be used.  
> https://github.com/AOMediaCodec/libavif/pull/526

**Comment by wantehchang** [comment]
Hi Lee-lithium,

My colleague Sai Deng, who added the tune=butteraugli option to libaom, provided the following build instructions:

1) Install jpeg-xl

The following commands are based on the build instructions in the _Quick start guide_ at https://gitlab.com/wg1/jpeg-xl. The only difference is that we added `-DJPEGXL_ENABLE_BENCHMARK=OFF` to the cmake command line to not build benchmark_xl, because benchmark_xl uses libavif if libavif is installed on your computer.

```
git clone https://gitlab.com/wg1/jpeg-xl.git --recursive
sudo apt install cmake pkg-config libbrotli-dev
sudo apt install libgif-dev libjpeg-dev libopenexr-dev libpng-dev libwebp-dev

cd jpeg-xl
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_BENCHMARK=OFF ..
cmake --build . -- -j$(nproc)

sudo cmake --install .
```

2) Install libaom

```
git clone https://aomedia.googlesource.com/aom
cd aom

# If you want to use libaom v3.1.0, run the command:
#     git checkout v3.1.0
# and then apply the following four patches:
#     https://aomedia-review.googlesource.com/c/aom/+/136044
#     https://aomedia-review.googlesource.com/c/aom/+/134506
#     https://aomedia-review.googlesource.com/c/aom/+/136082
#     https://aomedia-review.googlesource.com/c/aom/+/135521   

mkdir build.libavif
cd build.libavif
cmake -DCONFIG_TUNE_BUTTERAUGLI=1 -DCMAKE_BUILD_TYPE=Release \
-DENABLE_DOCS=0 -DENABLE_EXAMPLES=0 -DENABLE_TESTDATA=0 \
-DENABLE_TESTS=0 -DENABLE_TOOLS=0 ..
make -j
sudo make install
```

3) Build avifenc

```
cmake -G Ninja .. -DBUILD_SHARED_LIBS=OFF -DAVIF_CODEC_AOM=ON \
-DAVIF_LOCAL_AOM=OFF -DAVIF_BUILD_EXAMPLES=ON -DAVIF_BUILD_APPS=ON \
-DAVIF_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
ninja
```

**Comment by Lee-lithium** [comment]
@wantehchang  
Sorry to reply you so late, I still try to build this on msys2_mingw64,  
For now, I can't success build, and get many build problem,  
I think i need more time to success build.

**Comment by wantehchang** [comment]
Hi Lee-lithium,

I am sorry that I am not familiar with msys2_mingw64. The instructions I provided are for Linux. Hopefully you can figure out how to adapt the instructions for msys2_mingw64.

**Comment by Lee-lithium** [comment]
Hello @wantehchang  
Finally, I success build avifenc and have aom tune butteraugli support,  
```Version: 0.9.0 (aom [enc/dec]:3.1.0-13-g3bd281799)```  
```libyuv : unavailable```   

But i still can't use tune butteraugli encode image, maybe i missing something?  
```avifenc --min 7 --max 7 --minalpha 0 --minalpha 0 -d 10 -s 4 -j 12 -a tune=butteraugli```
```ERROR: Failed to finish encoding: Encoding of color planes failed```

**Comment by wantehchang** [comment]
Hi Lee-lithium,

I believe I reproduced this avifenc error on Linux. I can fix the error by changing "-d 10" to "-d 8". I will ask my colleague Sai Deng if -a tune=butteraugli only works for bit depth 8.

**Comment by wantehchang** [comment]
Hi Lee-lithium,

I have not been able to contact Sai Deng, but I found the answer by debugging.

aom_codec_encode() fails with the "Invalid parameter" error with the error detail: Only 8 bit depth images supported in tune=butteraugli mode.

That error message comes from the following code in aom/av1/av1_cx_iface.c:

```
static aom_codec_err_t validate_img(aom_codec_alg_priv_t *ctx,
                                    const aom_image_t *img) {
  ...
#if CONFIG_TUNE_BUTTERAUGLI
  if (ctx->extra_cfg.tuning == AOM_TUNE_BUTTERAUGLI) {
    if (img->bit_depth > 8) {
      ERROR("Only 8 bit depth images supported in tune=butteraugli mode.");
    }
    if (img->mc != 0 && img->mc != AOM_CICP_MC_BT_709 &&
        img->mc != AOM_CICP_MC_BT_601 && img->mc != AOM_CICP_MC_BT_470_B_G) {
      ERROR(
          "Only BT.709 and BT.601 matrix coefficients supported in "
          "tune=butteraugli mode. Identity matrix is treated as BT.601.");
    }
  }
#endif
  ...
}
```

Since you build libaom from source code, please verify that's the case. You can either use a debugger, or apply the following patch to libavif/src/codec_aom.c:

```
diff --git a/src/codec_aom.c b/src/codec_aom.c
index d275009..87587ac 100644
--- a/src/codec_aom.c
+++ b/src/codec_aom.c
@@ -32,6 +32,7 @@
 
 #include <assert.h>
 #include <limits.h>
+#include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
 
@@ -547,7 +548,10 @@ static avifResult aomCodecEncodeImage(avifCodec * codec,
 
         aom_codec_iface_t * encoderInterface = aom_codec_av1_cx();
         struct aom_codec_enc_cfg cfg;
-        aom_codec_enc_config_default(encoderInterface, &cfg, aomUsage);
+        if (aom_codec_enc_config_default(encoderInterface, &cfg, aomUsage) != AOM_CODEC_OK) {
+            fprintf(stderr, "WTC WTC WTC: aom_codec_enc_config_default() failed\n");
+            return AVIF_RESULT_UNKNOWN_ERROR;
+        }
 
         // Profile 0.  8-bit and 10-bit 4:2:0 and 4:0:0 only.
         // Profile 1.  8-bit and 10-bit 4:4:4
@@ -646,7 +650,10 @@ static avifResult aomCodecEncodeImage(avifCodec * codec,
         if (image->depth > 8) {
             encoderFlags |= AOM_CODEC_USE_HIGHBITDEPTH;
         }
-        aom_codec_enc_init(&codec->internal->encoder, encoderInterface, &cfg, encoderFlags);
+        if (aom_codec_enc_init(&codec->internal->encoder, encoderInterface, &cfg, encoderFlags) != AOM_CODEC_OK) {
+            fprintf(stderr, "WTC WTC WTC: aom_codec_enc_init() failed\n");
+            return AVIF_RESULT_UNKNOWN_ERROR;
+        }
         codec->internal->encoderInitialized = AVIF_TRUE;
 
         if (lossless) {
@@ -763,7 +770,12 @@ static avifResult aomCodecEncodeImage(avifCodec * codec,
     if (addImageFlags & AVIF_ADD_IMAGE_FLAG_FORCE_KEYFRAME) {
         encodeFlags |= AOM_EFLAG_FORCE_KF;
     }
-    aom_codec_encode(&codec->internal->encoder, aomImage, 0, 1, encodeFlags);
+    aom_codec_err_t err = aom_codec_encode(&codec->internal->encoder, aomImage, 0, 1, encodeFlags);
+    if (err != AOM_CODEC_OK) {
+        fprintf(stderr, "WTC WTC WTC: aom_codec_encode() failed: err=%d: %s: %s\n",
+                err, aom_codec_error(&codec->internal->encoder), aom_codec_error_detail(&codec->internal->encoder));
+        return AVIF_RESULT_UNKNOWN_ERROR;
+    }
 
     aom_codec_iter_t iter = NULL;
     for (;;) {
@@ -797,7 +809,10 @@ static avifBool aomCodecEncodeFinish(avifCodec * codec, avifCodecEncodeOutput *
     }
     for (;;) {
         // flush encoder
-        aom_codec_encode(&codec->internal->encoder, NULL, 0, 1, 0);
+        if (aom_codec_encode(&codec->internal->encoder, NULL, 0, 1, 0) != AOM_CODEC_OK) {
+            fprintf(stderr, "WTC WTC WTC: Flush encoder aom_codec_encode() failed\n");
+            return AVIF_FALSE;
+        }
 
         avifBool gotPacket = AVIF_FALSE;
         aom_codec_iter_t iter = NULL;
```

**Comment by Lee-lithium** [comment]
Hello wantehchang  
Thank you so much for your help :)  
A little curious, libaom tune butteraugli have plan implement higher bit depth and other cicp?  
I think butteraugli and butteraugli p-norm is very useful for keep high fidelity.

**Comment by wantehchang** [comment]
Hi Lee-lithium,

Thank you for your interest in libaom tune butteraugli. You can file an enhancement request for higher bit depth or other CICP at

    https://bugs.chromium.org/p/aomedia/issues/entry

When filing the bug report, change the label `Type-Defect` to `Type-Enhancement`. Your suggestion will help us plan our future work.
