### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/libavif#626]
The current release ([v0.9.0](https://github.com/AOMediaCodec/libavif/releases/tag/v0.9.0)) is now almost 3 months old, with [a lot of changes](https://github.com/AOMediaCodec/libavif/compare/v0.9.0...master) and improvements implemented in that time. Some projects and maintainers have a policy (or just like) to only use tagged commits, so I think it would be nice to have another tagged release somewhere in the near future.

Creating a [milestone](https://github.com/AOMediaCodec/libavif/milestones) can also be useful to track issues and PRs that need to be resolved before the next release.

**Comment by joedrago** [comment]
I agree that a new version is due, but I tend to do a release after @wantehchang does a review of the latest commits in master, as he is quite thorough and catches lots of subtle bugs. The next time he catches up to master, I will push a new version.

**Comment by wantehchang** [comment]
Joe,

If we want to create a release soon, I propose we create a release based on commit 1c39e772c2c0d687691dd4b589a12c323f5f767d. This is the last commit before the `avifDiagnostics` code landed. This commit has been in use internally at Google since May 4 with no problems.

Specifically I suggest we create a release as follows:
- Create a release branch off commit 1c39e772c2c0d687691dd4b589a12c323f5f767d.
- Unconditionally remove the pixi box presence check on the release branch. This change breaks AVIF images encoded with libheif v1.11.0 or older.
- Change version numbers and make a release on the release branch.

To remove the pixi box presence check, change the following "return AVIF_RESULT_BMFF_PARSE_FAILED" statement to "return AVIF_RESULT_OK" in libavif/src/read.c:

```
static avifResult avifDecoderItemValidateAV1(const avifDecoderItem * item)
{
    ...

    const avifProperty * pixiProp = avifPropertyArrayFind(&item->properties, "pixi");
    if (!pixiProp) {
        // A pixi box is mandatory in all valid AVIF configurations. Bail out.
        return AVIF_RESULT_BMFF_PARSE_FAILED;
    }

    ...
}
```

**Comment by wantehchang** [comment]
EwoutH wrote:
> Some projects and maintainers have a policy (or just like) to only use tagged commits, ...

This is a good policy because the not all software is "continuously releasable".

**Comment by joedrago** [comment]
If you've already audited up to 1c39e77, that leaves a reasonably small list of commits:

https://github.com/AOMediaCodec/libavif/compare/1c39e772c2c0d687691dd4b589a12c323f5f767d...master

I will audit these myself today and make any corrections I see, and perhaps make a release with all of it.

**Comment by joedrago** [comment]
This is done.

**Comment by EwoutH** [comment]
Awesome, and that was very quick!

@wantehchang I saw you contributed earlier to Chromium, could you roll the latest libavif version into it?

**Comment by wantehchang** [comment]
Hi Ewout,

Chromium has a code review requirement. I need to review the commits in the roll first.

**Comment by EwoutH** [comment]
That makes sense, thanks for the update.

@joedrago When the project was small and in it early stages it was very logical for you to commit directly to the main branch. This allows for very quick iteration, but it does result in unreviewed commits ending up in the main branch. Maybe it’s time to reconsider that policy, and start using feature branches and open PRs to the main branch from there. Then you can assign Wan-Teh (or someone else) as reviewer, who can merge it after approving it.

**Comment by joedrago** [comment]
Heh, yes, I'm quite familiar with feature branches and modern workflows. 😄 

Wan-Teh and I regularly discuss what ends up in the `master` branch; it isn't just me always shooting from the hip. You're probably right though to switch gears as `libavif` starts to reach a stable point. I'll consider this for the next set of bugfixes/features.

**Comment by EwoutH** [comment]
Thanks! A mixed policy might also make sense for now, committing small fixes directly and opening an PR for the larger or more complex ones. The advantage of PRs is that it also improves implicit documentation and allows outside contributors to easier follow the project and share their thoughts on it.

**Comment by wantehchang** [comment]
Hi Ewout and Joe,

I talked to two coworkers and they advised that I import new libavif updates into Chromium without review. So I have written a Chromium changelist to import libavif v0.9.1: https://crrev.com/c/2911174

I think it is a good idea to establish a formal code review process for libavif.

**Comment by joedrago** [comment]
I think even if it is after you merge in those changes into Chromium, it'd be worth auditing the changes afterwards. From now on, we can switch to an all-PRs approach to merging into master, but I'd like you to look over those few commits as a sanity check for me as well.

**Comment by wantehchang** [comment]
Joe: I am planning to review those changes before I import them into Google's internal repository. Please expect pull requests and issues from me in the next few days.

**Comment by aybli** [comment]
The last release is now over a year old. I would like to use the SVT encoder... and I guess there are a lot more changes.
Would it be possible to get a new version or maybe publish GitHub Actions artifacts?

**Comment by joedrago** [comment]
I was confused at this comment seeing as `v0.9.3` is from 2021/10/20, but it looks like these only show up under `Tags` and not `Releases`, ever since AppVeyor stopped offering free CI. I can assure you that every tagged version in "Tags" on GitHub is considered by me/us to be an actual "release", but I imagine you're asking for prebuilt Windows binaries? If so, we'll need to find an alternative to AppVeyor for building Windows binaries as I don't want to set a precedent for having a maintainer manually building/uploading them.

**Comment by aybli** [comment]
Thanks for your response. I wasn't aware that this is not just a simple setting on GitHub Actions to enable this so I understand that prebuilt Windows binaries may be a low priority. I guess if someone knows an easy way to do it, it would be nice to have updated Windows binaries once in a while.

**Comment by aybli** [comment]
> AppVeyor...

Not sure how I missed this but there's a recent windows build right here and it works great!
https://ci.appveyor.com/project/louquillio/libavif/build/artifacts

> ...stopped offering free CI

Does that just mean that the builds are available on AppVeyor but not on GitHub?
Anyways, I'm happy to be able to encode with the svt encoder now, thanks!

**Comment by wantehchang** [comment]
Joe: How do I mark v0.9.2 and v0.9.3 as releases? We should add this step to the [libavif release checklist](https://github.com/AOMediaCodec/libavif/wiki/Release-Checklist).

How about if you mark v0.9.2 as a release, update the release checklist, and let me try the commands on v0.9.3?

**Comment by joedrago** [comment]
Well, if done manually, it is as simple as using the "Create a new release" link, which takes you here:

https://github.com/AOMediaCodec/libavif/releases/new

You'd pick the tag and give it a title/description, and that's it. The difference here is we used to have AppVeyor's CI automatically do this and attach CI-generated Win32 binaries to the release, which our manual step wouldn't/shouldn't do. We can start making "Releases" (vs just tags), but I believe the original issue/concern here was access to some precompiled, blessed binaries.
