### ISSUE TITLE
The comment for avifDiagnostics seems to contradict the code in avifDiagnosticsPrintf

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#631]
In include/avif/avif.h, the comment for `struct avifDiagnostics` says:

```
    // Upon receiving an error from any non-const libavif API call, if the toplevel structure used
    // in the API call (avifDecoder, avifEncoder) contains a diag member, this buffer may be
    // populated with a NULL-terminated, freeform error string explaining the most recent error in
    // more detail. It will be cleared at the beginning of every non-const API call.
```

Note that it says "the most recent error". But the code in `avifDiagnosticsPrintf()` does not overwrite any existing error message:

```
void avifDiagnosticsPrintf(avifDiagnostics * diag, const char * format, ...)
{
    if (!diag) {
        // It is possible this is NULL (e.g. calls to avifFileTypeIsCompatible())
        return;
    }
    if (*diag->error) {
        // There is already a detailed error set.
        return;
    }

    va_list args;
    va_start(args, format);
    vsnprintf(diag->error, AVIF_DIAGNOSTICS_ERROR_BUFFER_SIZE, format, args);
    diag->error[AVIF_DIAGNOSTICS_ERROR_BUFFER_SIZE - 1] = '\0';
    va_end(args);
}
```

Joe, is the comment wrong? Or should we remove the `if (*diag->error)` statement in `avifDiagnosticsPrintf()`?

**Comment by joedrago** [comment]
The comment is misleading/incorrect. The intent is for it to have the _first_ encountered error for any given call into libavif, which is why the code is written as it is. The code is correct; the comment needs work. The intent of "recent" here was "from the most recent call into libavif", which is ambiguous.
