### ISSUE TITLE
0.9.1 fails to decode Netflix-released AVIF images: `Item ID 1 is missing mandatory pixi property`

### ISSUE THREAD

**Issue by happy-sea-fox** [AOMediaCodec/libavif#635]
```
>avifdec.exe D:\images\avif\Chimera-AV1-8bit-480x270-552kbps-6.avif 1.jpg
Decoding with AV1 codec 'aom' (1 worker thread), please wait...
ERROR: Failed to decode image: BMFF parsing failed
Diagnostics:
 * [Strict] Item ID 1 is missing mandatory pixi property
```

AVIF 0.9.1 compiled with AOM 3.1.0 on Windows 7 x64 with MSVC 2019.

0.9.0 with AOM 3.0.0 decodes them just fine.

[Chimera-AV1-8bit-480x270-552kbps-6.zip](https://github.com/AOMediaCodec/libavif/files/6528715/Chimera-AV1-8bit-480x270-552kbps-6.zip)

**Comment by joedrago** [comment]
Over the last few months, I've been working alongside the Chromium, Firefox, and libheif folks to make sure all of our implementations are following the standard as closely as possible, as many people tend to not read the standard, but simply see what the most popular implementations are willing to tolerate. `v0.9.1` is the first release that has a handful of new compliance enforcements, all of which should not impact any avifenc-encoded images (including very old versions).

For a few of the compliance restrictions imposed, I put them behind a "strict" mode, as there are some encoder implementations that weren't compliant until recently (or at the time of example file generation). A side effect of this, unfortunately, is that a handful of the actual example files from `av1-avif` are found to be noncompliant. I believe @cconcolato (one of the AVIF standard's authors) created this particular file, and it precedes the existence of libavif entirely. Similarly, I believe all _five_ example AVIFs that offer a `clap` box (clean aperture, providing a crop rect) are all invalid, according to the standards.

For this particular file, you can ask `avifdec` to stop being so strict about `pixi` by using `--no-strict` on the commandline, and it should decode. We still need to fix all of the relevant examples' `pixi` and `clap` boxes in our `av1-avif` examples, though.

**Comment by joedrago** [comment]
I will open a GitHub issue on `av1-avif` with a comprehensive list of which files need fixes later today.

**Comment by happy-sea-fox** [comment]
@joedrago Thanks for the great clarification! I guess the ticket can be closed.

**Comment by baumanj** [comment]
> Similarly, I believe all _five_ example AVIFs that offer a `clap` box (clean aperture, providing a crop rect) are all invalid, according to the standards.

Right you are: https://github.com/AOMediaCodec/av1-avif/issues/150
