### ISSUE TITLE
avifDecoderParse() should avoid calling tile->codec->open()

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#636]
Right now `avifDecoderParse()` calls `tile->codec->open()` at the very end via this call chain:
    `avifDecoderParse()` > `avifDecoderReset()` > `avifDecoderFlush()` > `tile->codec->open()`

```
static avifResult avifDecoderFlush(avifDecoder * decoder)
{
    avifDecoderDataResetCodec(decoder->data);

    for (unsigned int i = 0; i < decoder->data->tiles.count; ++i) {
        avifTile * tile = &decoder->data->tiles.tile[i];
        tile->codec = avifCodecCreateInternal(decoder->codecChoice);
        if (!tile->codec) {
            return AVIF_RESULT_NO_CODEC_AVAILABLE;
        }
        tile->codec->diag = &decoder->diag;
        if (!tile->codec->open(tile->codec, decoder)) {
            return AVIF_RESULT_DECODE_COLOR_FAILED;
        }
    }
    return AVIF_RESULT_OK;
}
```

Since an application may call `avifDecoderParse()` just to parse the container without decoding the image, it would be good to delay the `avifCodecCreateInternal()` and `tile->codec->open()` calls until we decode the image.

Joe, if you agree with this proposed change and have some spare time, could you please implement this change because you know this code the best? Even outlining how this should be done would be very helpful. Thank you!

**Comment by joedrago** [comment]
Similarly to how the encoding pipeline works with lazy initialization, I tried doing that with the decoding pipeline and was quite surprised at how friendly it all worked out. Even the diffs are nice and pretty!

Check it out and let me know if I missed something.

https://github.com/AOMediaCodec/libavif/pull/637

**Comment by wantehchang** [comment]
Joe: Thank you so much for working on this right away!

I forgot to mention that the reason I looked into this today was to see if it was possible to set decoder->maxThreads based on the image's width and height. But I had been wondering about this for a long time, so today I traced the code in a debugger and verified that avifDecoderParse() opens the AV1 decoder.

**Comment by joedrago** [comment]
Ah, yes. This change would allow for that quite nicely.
