### ISSUE TITLE
[Feature Request] How about -mt as well as -j N?

### ISSUE THREAD

**Issue by bat999** [AOMediaCodec/libavif#645]
Hi
**avifenc** and **avifdec** have an option...
`-j,--jobs J   : Number of jobs (worker threads, default: 1)`

That's OK, but **cwebp** and **dwebp** have an option ...
`-mt .... use multi-threading if available`
I suppose this means "all of them".

It would be neat if **avifenc** and **avifdec** had this option too.
So it would be...
`-j N`
or
`-mt`

:-)

**Comment by bat999** [comment]
Or maybe don't bother with the "-mt" but change it to...
`-j,--jobs J : Number of jobs (worker threads, default: all)
`

**Comment by bat999** [comment]
Until then...
`$ avifenc -j $(nproc) -o output.avif input.png`

**Comment by joedrago** [comment]
I could see making a special `-j` option such as `all` or `max` which would effectively set it to what `nproc` emits (but in a cross-platform way).

**Comment by bat999** [comment]
@joedrago 
Yes "**-j all**" will be OK if you're not interested in "**-mt**" like webp.

Do you think "-j,--jobs J : Number of jobs (worker threads, default: **all**)" is dangerous?

**Comment by joedrago** [comment]
It's a good question; I'm not sure. It would be a pretty large default change to go from single-threaded to "use all cores" if `-j` isn't specified at all, but it might be a good change.

**Comment by 1480c1** [comment]
Would something like GNU make's rules like no `-j` == single, `-j` no argument passed == `$(nproc)`, and `-j arg` == `arg  jobs` be okay?

**Comment by joedrago** [comment]
I don't support a single argument that can either have an argument or no argument, as the tool uses positional arguments for filenames. `-j` with no arguments is definitely out. I think `all` or `max` is a reasonable argument for `-j` and I'm still undecided on the default, but no-arg isn't a choice here.

**Comment by 1480c1** [comment]
If no-arg is out, then my personal leaning would be towards having the default being 1, since that way there's no unexpected changes for people casually updating and testing, and having `all` meaning `all of my cores` and potentially `max` meaning `maximum the library can support before breaking down`

**Comment by 1480c1** [comment]
Either that, or to preserve the idea of using numbers, maybe `-1` to mean `all`

**Comment by bat999** [comment]
@joedrago 
Hi
They have done something different at the cavif program. 
Here ---> https://github.com/kornelski/cavif-rs

They have "**-j N**", but if it is not used then it automatically sets the number of jobs to the number of cores on the PC.

This is what it says...
`-j, --threads <n>   Maximum threads to use (0 = one thread per host core) [default: 0]`

So default is 0 when nothing is entered, which means one thread per host core.
No need for them to mess about with "all" or "max" or "mt".

They must consider it to be not a "dangerous" option. 

If I run
`~ $ cavif -o output.avif input.png`
I look in `top -H` and it shows both of my cores working, even though I didn't ask for them.

If I run
`~ $ avifenc -o output.avif input.png`
I look in `top -H` and it shows only one core working.
It only runs both cores when I use -j 2

**Comment by joedrago** [comment]
Sure, I'm not 100% decided on a new default yet.

**Comment by bat999** [comment]
It's working OK.
Shows 2 worker threads.
Thanks :-)

```
~ $ avifenc -V
Version: 0.9.1 (dav1d [dec]:b3d988f, aom [enc/dec]:v3.1.1, rav1e [enc]:0.5.0-alpha (p20210615))
libyuv : available (1788)

~ $ avifenc -j all kodim20.png kodim20.avif
Successfully loaded: kodim20.png
AVIF to be written: (Lossy)
 * Resolution     : 768x512
 * Bit Depth      : 8
 * Format         : YUV444
 * Alpha          : Not premultiplied
 * Range          : Full
 * Color Primaries: 1
 * Transfer Char. : 13
 * Matrix Coeffs. : 6
 * ICC Profile    : Absent (0 bytes)
 * XMP Metadata   : Absent (0 bytes)
 * EXIF Metadata  : Absent (0 bytes)
 * Transformations: None
Encoding with AV1 codec 'aom' speed [6], color QP [24 (Medium) <-> 26 (Medium)], alpha QP [0 (Lossless) <-> 0 (Lossless)], tileRowsLog2 [0], tileColsLog2 [0], 2 worker thread(s), please wait...
Encoded successfully.
 * Color AV1 total size: 31030 bytes
 * Alpha AV1 total size: 0 bytes
Wrote AVIF: kodim20.avif
```
