### ISSUE TITLE
Effectively disabled assertion about AVIF_APP_DEFAULT_PIXEL_FORMAT in apps/avifenc.c

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#647]
In apps/avifenc.c, there is an assertion about `AVIF_APP_DEFAULT_PIXEL_FORMAT` in the following if statement:

```
    if ((image->matrixCoefficients == AVIF_MATRIX_COEFFICIENTS_IDENTITY) && (input.requestedFormat != AVIF_PIXEL_FORMAT_NONE) &&
        (input.requestedFormat != AVIF_PIXEL_FORMAT_YUV444)) {
        // This protects against this code misbehaving if AVIF_APP_DEFAULT_PIXEL_FORMAT is ever changed from AVIF_PIXEL_FORMAT_YUV444
        assert((input.requestedFormat != AVIF_PIXEL_FORMAT_NONE) || (AVIF_APP_DEFAULT_PIXEL_FORMAT == AVIF_PIXEL_FORMAT_YUV444));

        ...
    }
```

Because `input.requestedFormat != AVIF_PIXEL_FORMAT_NONE` is one of the three conditionals checked by the if statement, inside the if block, `input.requestedFormat != AVIF_PIXEL_FORMAT_NONE` is guaranteed to be true, so the assertion
```
        assert((input.requestedFormat != AVIF_PIXEL_FORMAT_NONE) || (AVIF_APP_DEFAULT_PIXEL_FORMAT == AVIF_PIXEL_FORMAT_YUV444));
```
is equivalent to
```
        assert(1 || (AVIF_APP_DEFAULT_PIXEL_FORMAT == AVIF_PIXEL_FORMAT_YUV444));
```

Therefore the assertion will never check `AVIF_APP_DEFAULT_PIXEL_FORMAT == AVIF_PIXEL_FORMAT_YUV444`. This assertion is effectively disabled.

Since I don't understand this if statement, I am sorry that I cannot suggest a fix.

**Comment by tongyuantongyu** [comment]
I believe this piece of code is to ensure IDENTITY is coupled with YUV444, and tries to correct invalid config.

The current logic is a bit messy, I think it should behave like this:
avifenc.c checks and corrects invalid config set by user.
Reader functions (avifJPEGRead, avifPNGRead) are aware of this rule and always select YUV444 for IDENTITY, but not the configurable DEFAULT_PIXEL_FORMAT.
Reformat function (avifImageRGBToYUV) will fail on invalid case. (This is already in current code)

PR #654 should fix this.
