### ISSUE TITLE
Grayscale (YUV400) support

### ISSUE THREAD

**Issue by q3cpma** [AOMediaCodec/libavif#65]
The title says it all, it'd be nice to have it in the library at least.

**Comment by joedrago** [comment]
I see a lot more buzz for this in general than I expected. To do it right, I'll want to rework the plane flags to have a Y and a UV which will be a breaking change so I'll have to bump the major library version, but it is probably not a huge code change under the hood. 

I might not get to it this week as I'm on vacation, but I'll add it soonish.

**Comment by q3cpma** [comment]
Thanks and nice reactivity. Makes AVIF experimentation easier.

**Comment by joedrago** [comment]
I started got most of the way implementing this today, and then found out that rav1e isn't there yet, WRT monochrome support. I've opened a bug with them, and I'm going to postpone support for libavif monochrome until they support it. Hopefully it won't be too long.

https://github.com/xiph/rav1e/issues/2190

**Comment by tdaede** [comment]
FWIW rav1e implemented monochrome support in our most recent prerelease, if you'd like to try it out.

**Comment by q3cpma** [comment]
Would it be possible for the JPEG/PNG reader to detect grayscale input? I
currently have to use ffmpeg as intermediary.

**Comment by joedrago** [comment]
You can demand that any image is forced to be made grayscale via `--yuv 400`, but I'd be fine with altering any avifenc input code to detect that the YUV format should be 400 "by default". I'm pretty sure there is a "gray" color space in PNG so that might be easy, but I don't know about JPEG. Is there a grayscale flag somewhere in JPEG? (I'll have to look.)

**Comment by q3cpma** [comment]
On Thu, Jul 09, 2020 at 01:03:13PM -0700, Joe Drago wrote:
> You can demand that any image is forced to be made grayscale via `--yuv 400`, but I'd be fine with altering any avifenc input code to detect that the YUV format should be 400 "by default". I'm pretty sure there is a "gray" color space in PNG so that might be easy, but I don't know about JPEG. Is there a grayscale flag somewhere in JPEG? (I'll have to look.)
>

Indeed, sorry for my lack of attention, should've noticed it.

**Comment by vigneshvg** [comment]
libavif now supports monochrome. `avifenc` also uses yuv400 as the yuv format when dealing with grayscale PNG images: https://github.com/AOMediaCodec/libavif/blob/e58d3e06a3b9a2391762d12e6e389927a999ec2c/apps/shared/avifpng.c#L321
