### ISSUE TITLE
Compilation error with the latest MSVC 2019 and `vcpkg` pipeline

### ISSUE THREAD

**Issue by HappySeaFox** [AOMediaCodec/libavif#657]
```
D:\buildtrees\libavif\src\v0.9.1-96c01d44fc.clean\src\read.c(875): error C2220: the following warning is treated as an error
D:\buildtrees\libavif\src\v0.9.1-96c01d44fc.clean\src\read.c(875): warning C4244: '=': conversion from 'uint64_t' to 'size_t', possible loss of data
```

Possible fix:

```diff
- offsetBuffer.size = idatBuffer->size - extent->offset;
+ offsetBuffer.size = (size_t)(idatBuffer->size - extent->offset);
```

**Comment by joedrago** [comment]
Just to clarify, this is something that manifested after installing a new MSVC/compiler, right? I only ask because I believe that particular line has been in there for ~8 months, and want to know if this is just a new check in the most recent compiler. (We should fix it either way, of course.)

**Comment by HappySeaFox** [comment]
Yes, I guess it's a recently introduced error in the updated compiler version, OR recently enabled error in the pipeline.

**Comment by wantehchang** [comment]
Hi HappySeaFox,

Thank you for the bug report and suggested fix. I would be better to just cast extent->offset to size_t, and we can do that safely after verifying that extent->offset is <= a size_t value. I have written a fix.

**Comment by wantehchang** [comment]
I can reproduce the compiler warning using Visual C++ 2019. The compiler version is:
`Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29915 for x86`

The first few lines of the cmake command are:
```
-- The C compiler identification is MSVC 19.28.29915.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x86/cl.exe - skipped
```

I verified that my pull request fixed the compiler warning.
