### ISSUE TITLE
calcGCD(a, b) is inefficient for the most common cases of b = 1 or 2

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#664]
The `calcGCD()` function apparently implements the Euclidean algorithm but performs division by repeated subtractions:

```
static int32_t calcGCD(int32_t a, int32_t b)
{
    if (a < 0) {
        a *= -1;
    }
    if (b < 0) {
        b *= -1;
    }
    while (a > 0) {
        if (a < b) {
            int32_t t = a;
            a = b;
            b = t;
        }
        a = a - b;
    }
    return b;
}
```

Since the only call to `calcGCD()` is `calcGCD(f->n, f->d)`, the `b` argument is the denominator of a fraction. The most common denominators in a 'clap' box are 1 and 2. If `b` is 1 or 2, `calcGCD(a, b)` is inefficient because the while loop will perform `a` or `a/2` subtractions. For example, consider `calcGCD(720, 1)` and `calcGCD(720, 2)`.

**Comment by joedrago** [comment]
We can switch this to the modulus-based implementation to avoid this.

**Comment by vrabaud** [comment]
That was fixed in https://github.com/AOMediaCodec/libavif/pull/1135
