### ISSUE TITLE
contrib/gdk-pixbuf/loader.c:211:28: error: ‘avifImageMirror’ has no member named ‘axis’

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#667]
We have a breaking change (axis replaced by mode).

Do I understand correctly that meaning is now inverted? Does it mean that https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles/Link-U testfiles must be updated?

Older apps using older libavif (reading `axis` value) may mirror incorrectly some of the new AVIF files?

**Comment by joedrago** [comment]
Yes, the explanation is here: https://github.com/AOMediaCodec/libavif/pull/665

Coincidentally, unless they were updated, I believe the Link-U files were one of the misinterpretations I hinted at in my PR, and those files are implemented wrong, which means they're right (now). I don't have an exhaustive list of which viewers interpret `imir`, but I do know that Chrome implemented `axis` correctly (to the standard) and must be updated (@wantehchang has already implemented it), and my viewer (Vantage) must be updated. I believe iPhones (HEIF), libheif, and ImageMagick all were implemented using what is now the `mode` interpretation, so if anything, they are _now correct_. 

It is a bizarre situation, but with the exception of iPhone front cameras and HEIF, I don't think `imir` is very widely used, so the actual impact is probably not too severe.

**Comment by novomesk** [comment]
I have impression that Link-U files are technically correct. I compared output from libheif too.
kimono.mirror-vertical.avif (which is upside down) has `imir (Mirror)        : Mode 0 (top-to-bottom)` and
kimono.mirror-horizontal.avif (west and east exchanged) has `imir (Mirror)        : Mode 1 (left-to-right)`

I understand that vertical+horizontal are confusing, because one person thinks about v/h axis and another about one v/h direction.

**Comment by joedrago** [comment]
Yes, "flip _horizontal_" vs "about a _horizontal_ axis" being opposites is definitely the source of confusion for the implementers. I think for most developers, if they read the original sentence directly or were asked verbally, it is quite unambiguous. However, if they are trying to hook up pre-existing mirroring code in their image pipeline and it has a function argument named `horizontal` (say), I could see how it'd be easy to skim the standard, miss the word "axis", and get it backwards.

I tried to mitigate this issue back in November by adding the terms `left-to-right` and `top-to-bottom` to `avif.h`, but the decision to switch the meaning of the bit is from HEIF (which AVIF is derived). My job now is simply to follow the new amendment.
