### ISSUE TITLE
How to remove or edit metadata from existing AVIF file without re-encoding of image(s)?

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#67]
Right now I can set metadata (using avifImageSetMetadataExif and/or avifImageSetMetadataXMP) before calling avifEncoderWrite.

Is there an easy way how to reconstruct the AVIF file with modified (added/removed/modified) metadata but leaving compressed images unchanged?

**Comment by joedrago** [comment]
libavif wasn't designed to work that way, unfortunately. However, behind the scenes, AVIF are just BMFF files (like an MP4), so if you just want to manipulate the boxes inside of one of them without re-encoding anything, You might be much happier with a tool like MP4Box or exiftool. MP4Box does exactly what you are looking for, for any BMFF-derived file.
