### ISSUE TITLE
Add tests based on the GoogleTest (gtest) C++ test framework

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#677]
Hi Joe,

A colleague of mine is planning to contribute tests to libavif. We are wondering if we can use the GoogleTest (gtest) C++ test framework when writing new tests. Has this been proposed before?

**Comment by joedrago** [comment]
Other than when someone opts into using libgav1 (unusual on platforms other than Android), libavif is entirely C, and I'd prefer if I could keep it that way for anything in the main codebase. Does gtest over a C API variant?

**Comment by wantehchang** [comment]
gtest can be used to test a C API, but the tests must be written in C++.

If you would like to avoid depending on a C++ test framework, I will ask my colleague to add the gtest-based tests to a subdirectory inside our internal copy of libavif. A downside is that other libavif users won't be able to run or improve those tests. But since we will be running those tests regularly, libavif will still benefit from our new tests.

**Comment by joedrago** [comment]
I think we can probably use gtest as long as it becomes something that you have to opt into when you build, and if you are not using libgav1, it only changes the linker language of the test suite executable. Also we need to agree on the coding style (I would want to retain any settings currently in the clang format, first though but would be willing to add some c++ specific settings to it).

**Comment by vrabaud** [comment]
The main goal of using gtest is to use sharding which helps run avitest a few times faster (1 minute vs the 10 minutes it takes right now).
We can totally make gtest and the corresponding optional, that is what we do for WebP.
