### ISSUE TITLE
Refactor/Redesign aviftest

### ISSUE THREAD

**Issue by joedrago** [AOMediaCodec/libavif#684]
`aviftest` and its JSON-based tests are unreliable, and due to an oversight in `aviftest` (487e3425ee59715afe0656a01e93c084ddc6e36a), I didn't realize it. It is time to rethink our automated/smoke tests in favor of something more reliable and comprehensive.

**Comment by vrabaud** [comment]
Fixed in https://github.com/AOMediaCodec/libavif/pull/811
