### ISSUE TITLE
Summer_in_Tomsk_720p_5x4_grid.avif

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#69]
This is known tricky testfile, libavif with libaom doesn't decode it yet, I get "No AV1 items found" error.
https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Microsoft/Summer_in_Tomsk_720p_5x4_grid.avif

**Comment by joedrago** [comment]
This is due to the usage of a primary item of type "image grid" (6.6.2.3.2 in the HEIF standard), which I don't support currently. It seems easy to parse the `grid` item, but implementing the grid layout itself might be a bit of a pain. I'll have to think about this one.

**Comment by novomesk** [comment]
![ms_paint](https://user-images.githubusercontent.com/52529860/75573624-80f1a580-5a5d-11ea-9eef-77c4ffc89b6a.png)
I was able to open it on Windows10 using MS Paint.

**Comment by joedrago** [comment]
Just a heads up -- I managed to refactor things and get this working today, locally. I'll probably do tons of sanity checks and re-reads and tests, and then check it in tomorrow.

**Comment by novomesk** [comment]
Thank you Joe, I understand this is not trivial and it takes time.

**Comment by joedrago** [comment]
This should be supported now. (bump in libavif version coming soon)

https://github.com/AOMediaCodec/libavif/commit/060d534faddcdff0442fd5fd83fba41ee9b9655b
