### ISSUE TITLE
How to judge avif format in java/kotlin?

### ISSUE THREAD

**Issue by cursem** [AOMediaCodec/libavif#696]
For jpeg, the raw data start with  (byte) 0xFF, (byte)0xD8, (byte)0xFF.
How about avif?

**Comment by joedrago** [comment]
`libavif` offers [a function](https://github.com/AOMediaCodec/libavif/blob/master/include/avif/avif.h#L1046) named `avifPeekCompatibleFileType()` which can take raw data and return `true` if the data looks like it might be an AVIF. This function is very inexpensive (no allocations, etc), but if you want to do it yourself, I've explained how to detect AVIF here:

https://github.com/php/php-src/pull/5127#issuecomment-800566448

`avifPeekCompatibleFileType()` effectively does what I explain in that link.

**Comment by cursem** [comment]
typedef struct avifROData
{
    const uint8_t * data;
    size_t size;
} avifROData;
avifPeekCompatibleFileType(const avifROData * input)

for the *data, Can I only pass in part of the data? 3 bytes，4 bytes，5bytes ..., if yes, how to determine the size.

**Comment by cursem** [comment]
@joedrago and how to judge avif animation from row data. Thanks very much.

**Comment by joedrago** [comment]
You can use the first 4 bytes as an unsigned integer as a hint of how much to give this function, or you can just choose a size that would cover most FileTypeBox sizes. I believe Chromium will feed around 144 bytes, which would allow for something like 32 compatible brands (many more than a normal file would have). You can probably give 100 bytes or less to this function and get the information you need, but the first four bytes would give you the exact answer.

AVIF image sequences use the brand `avis`. You can look for that to see if it is an image sequence.

**Comment by cursem** [comment]
@joedrago Thanks for your reply.
btw, how get width and height before decode avif ?
Thanks.

**Comment by vigneshvg** [comment]
Hi @cursem,

libavif now offers a [Java API](https://github.com/AOMediaCodec/libavif/tree/main/android_jni) ([hosted on maven](https://github.com/AOMediaCodec/libavif/tree/main/android_jni#maven-releases)). You can use the API to detect AVIF images and get information like width, height, etc without decoding the entire image.
