### ISSUE TITLE
The word "otherwise" is ambiguous in the comment for the spatialID member of avifDecodeSample.

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#697]
Joe,

In include/avif/internal., the comment for the `spatialID` member of the `avifDecodeSample` struct reads:

```
    uint8_t spatialID; // If set to a value other than AVIF_SPATIAL_ID_UNSET, the output frame's spatial_id must match
                       // this ID, otherwise output frames from this sample should be skipped until it does.
```

The word "otherwise" is ambiguous. It could be interpreted to mean the opposite of either

- "If set to a value other than AVIF_SPATIAL_ID_UNSET", or
- "the output frame's spatial_id must match this ID".

It actually means the opposite of the latter, i.e., if the output frame's spatial_id does not match this ID. But when I first read this comment, I thought it meant the opposite of the former, i.e., if set to AVIF_SPATIAL_ID_UNSET.

A simple fix would be to replace "otherwise" with "if the output frame's spatial_id does not match this ID":

```
    uint8_t spatialID; // If set to a value other than AVIF_SPATIAL_ID_UNSET, the output frame's spatial_id must match
                       // this ID. If the output frame's spatial_id does not match this ID, output frames from this
                       // sample should be skipped until it does.
```

Alternatively, we could rewrite the comment as follows, which is less verbose but potentially also less clear:

```
    uint8_t spatialID; // If set to a value other than AVIF_SPATIAL_ID_UNSET, output frames from this sample should be
                       // skipped until the output frame's spatial_id matches this ID.
```

Which one would you prefer?

**Comment by joedrago** [comment]
I think both of your rewrites are clear to me. I would accept either of them.
