### ISSUE TITLE
How to get meta data like width and height  before decode avif

### ISSUE THREAD

**Issue by cursem** [AOMediaCodec/libavif#717]
Hi, I want to get the width ,height and other meta data of the avif before decoding, what should i do?
Thanks.

**Comment by joedrago** [comment]
Calling `avifDecoderParse()` parses an AVIF container and gathers all information/metadata, but does not actually _decode_ the image. It is a very cheap and lightweight function. Please see the example here on what data is available after `avifDecoderParse()`:

https://github.com/AOMediaCodec/libavif/blob/master/examples/avif_example_decode_memory.c#L59
