### ISSUE TITLE
Add a libyuv-based implementation of avifImageRGBToYUV()

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#718]
While profiling avifenc, my colleague Fyodor Kyslov found that the time spent in `avifImageRGBToYUV()` is a significant portion of total encoding time when encoding smaller images. It would be good to add optimized implementations of `avifImageRGBToYUV()`, e.g., by dispatching to libyuv.

**Comment by vigneshvg** [comment]
This is now done. `libavif` supports use of `libyuv` for `avifImageRGBToYUV`.
