### ISSUE TITLE
dav1d took 360ms to decode image.

### ISSUE THREAD

**Issue by cursem** [AOMediaCodec/libavif#722]
url: https://raw.githubusercontent.com/AOMediaCodec/av1-avif/master/testFiles/Netflix/avif/hdr_cosmos01650_cicp9-16-0_lossless.avif
dimension: 2048 x 858

CPU: SDM865
Android Version: 11

How to optimize ?

**Comment by cursem** [comment]
Hello, It is normal ?

**Comment by BlueSwordM** [comment]
Yes, this seems to be normal indeed.

Lossless AV1 is a lot harder to decode than normal lossy AV1.

I would recommend using JPEG-XL instead for lossless coding.

**Comment by vigneshvg** [comment]
> url: https://raw.githubusercontent.com/AOMediaCodec/av1-avif/master/testFiles/Netflix/avif/hdr_cosmos01650_cicp9-16-0_lossless.avif dimension: 2048 x 858
> 
> CPU: SDM865 Android Version: 11
> 
> How to optimize ?

One possible way to speed up the decoding is to use tiling. You can re-encode the image with `avifenc` with `--auto-tiling` option and that will speed up the dav1d decoder when multi-threading is enabled.

Otherwise, there isn't anything actionable in this issue. So marking it as complete.
