### ISSUE TITLE
Make a `brew` package

### ISSUE THREAD

**Issue by HappySeaFox** [AOMediaCodec/libavif#724]
It would be great to make `libavif` available in `brew` on macOS (in the default brew repository, not as a third-party repository). AOM is already available in `brew`. https://github.com/HappySeaFox/homebrew-libavif may be a good starting point. I use it like that: `brew install happyseafox/libavif/libavif`. Making libavif available in the default brew repository will make it possible to just `brew install libavif`. See https://docs.brew.sh/Acceptable-Formulae as a good starting point.

**Comment by joedrago** [comment]
I agree. I do have an unofficial (but personally made) recipe on my personal repo for the two core tools here:

`brew install joedrago/repo/avifenc`

They're just static builds though and don't leverage library packages for things like libavif, aom, dav1d, etc. Perhaps we can find some brew experts out there that would take a shot at it. I imagine we'll need to make sure it all builds for M1 chips too.

**Comment by BirkhoffLee** [comment]
> I agree. I do have an unofficial (but personally made) recipe on my personal repo for the two core tools here:
> 
> `brew install joedrago/repo/avifenc`
> 
> They're just static builds though and don't leverage library packages for things like libavif, aom, dav1d, etc. Perhaps we can find some brew experts out there that would take a shot at it. I imagine we'll need to make sure it all builds for M1 chips too.

Hi - I just tried to install `joedrago/repo/avifenc` on an M1 Mac with Homebrew. Unfortunately it fails with the following log:

```
==> Installing joedrago/repo/avifenc
/opt/homebrew/Library/Taps/joedrago/homebrew-repo/Formula/avifenc.rb:16: warning: conflicting chdir during another chdir block
==> zsh aom.cmd
==> zsh libjpeg.cmd
==> zsh zlibpng.cmd
/opt/homebrew/Library/Taps/joedrago/homebrew-repo/Formula/avifenc.rb:20: warning: conflicting chdir during another chdir block
/opt/homebrew/Library/Taps/joedrago/homebrew-repo/Formula/avifenc.rb:22: warning: conflicting chdir during another chdir block
==> cmake -G Ninja -DBUILD_SHARED_LIBS=0 -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DAVIF_LOCAL_ZLIBPNG=1 -DAVIF_LOCAL_JPEG=1 -DAVIF_BUILD_APPS=1 ..
==> ninja
Last 15 lines from /Users/birkhoff/Library/Logs/Homebrew/avifenc/05.ninja:
               no_neon = !png_have_neon(pp);
                          ^
2 errors generated.
[111/135] Building C object ext/libpng/CMakeFiles/png_static.dir/pngwrite.c.o
[112/135] Building C object ext/libpng/CMakeFiles/png_static.dir/pngrtran.c.o
[113/135] Building ASM object ext/libpng/CMakeFiles/png_static.dir/arm/filter_neon.S.o
[114/135] Building C object ext/libpng/CMakeFiles/png_static.dir/pngwutil.c.o
[115/135] Building C object ext/libjpeg/CMakeFiles/jpeg.dir/jcapimin.c.o
[116/135] Building C object ext/libjpeg/CMakeFiles/jpeg.dir/jaricom.c.o
[117/135] Building C object ext/libjpeg/CMakeFiles/jpeg.dir/jcapistd.c.o
[118/135] Building C object ext/libjpeg/CMakeFiles/jpeg.dir/jccoefct.c.o
[119/135] Building C object ext/libjpeg/CMakeFiles/jpeg.dir/jcarith.c.o
[120/135] Building C object ext/libpng/CMakeFiles/png_static.dir/arm/filter_neon_intrinsics.c.o
[121/135] Building C object ext/libpng/CMakeFiles/png_static.dir/arm/palette_neon_intrinsics.c.o
ninja: build stopped: subcommand failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/joedrago/homebrew-repo/issues

These open issues may also help:
upgrade avifenc to 0.9.2 https://github.com/joedrago/homebrew-repo/issues/4
Installing joedrago/repo/avifenc has failed!
```

This might not be the best place to report this issue, but I searched and found this thread. Do you know if there's anything I can do to have it installed properly on arm64? Thank you.

**Comment by JWo1F** [comment]
@BirkhoffLee, I have the same issue :(

**Comment by HappySeaFox** [comment]
libavif is now available in brew.
