### ISSUE TITLE
Certain scale values can cause overflow in libyuv

### ISSUE THREAD

**Issue by FrankGalligan** [AOMediaCodec/libavif#734]
This bug was discovered by Google's internal fuzzing.

In parts of libyuv they convert values to fixed point (16.16) integers. Certain scale values can cause integer overflow. 

In one example the src width is 36681 and the dst width is 49. In the scaling code this will generate a max value of 2367705984, which is > 2^31 -1 and causes an integer overflow.

**Comment by joedrago** [comment]
Thanks for the report. I'll open a PR to try to mitigate this.

**Comment by FrankGalligan** [comment]
Hi @joedrago I put up a PR.

Kind of filed the bug and out up the PR, but you were too fast on the interrupt :)

**Comment by FrankGalligan** [comment]
But if you have something better in mind, that is fine.

**Comment by FrankGalligan** [comment]
I'm also going to see if more scale factors could be handled in libyuv.

**Comment by joedrago** [comment]
Heh, I replied quickly, but I hadn't started writing any code just yet (nobody is _that_ fast). I've left a few quick comments on your PR.
