### ISSUE TITLE
Versions required and related doc

### ISSUE THREAD

**Issue by pierrejoye** [AOMediaCodec/libavif#758]
Good morning,

While trying to get https://github.com/libgd/libgd/issues/770 fixed and get libavif running smooth in our CI/Dev/Etc I am struggling a bit to get it built correctly.

I tried so far the static build, but still get error about no codec present. Packaged version with ubuntu 21.04 shows the same issue (reported there too).

Would it be possible to use version and list them in each released tag?  I am happy to help to add more docs about this here as well based on the requirements.

That could help to install and create reproducible install. Mainly because Installing everything from latest git for codecs is not an option for many of our users (libgd is used by PHP, used by hosters, etc).

**Comment by joedrago** [comment]
I'm not exactly sure what your "version listing" request means here, but as it says in the Build Notes:

> No AV1 codecs are enabled by default. Enable them by enabling any of the following CMake options:
> 
> * `AVIF_CODEC_AOM` - requires CMake, NASM
> * `AVIF_CODEC_DAV1D` - requires Meson, Ninja, NASM
> * `AVIF_CODEC_LIBGAV1` - requires CMake, Ninja
> * `AVIF_CODEC_RAV1E` - requires cargo (Rust), NASM

`libavif` provides all of the machinery to encode/decode AVIF _except_ for the ability to encode/decode AV1 itself. For this, you need some combination of `libaom` (which provides both), or `libdav1d` (decode only), or `rav1e` (encode only), etc. If you've already made libaom available on the system (via a dependency), simply clueing in your `libavif` build during CMake time that you'd like to use it is sufficient:

When configuring libavif using CMake, this would look something like:

```
cmake -DAVIF_CODEC_AOM=1 ...
```

There exists a means to create a fully static build of `avifenc`/`avifdec` which is convenient for embedding libavif or making a one-off executable, but if your goal is to use `libavif` in a downstream library like libgd, I highly recommend depending on an AV1 shared library (such as `libaom`) and then letting libavif's cmake configuration process know to use it.

**Comment by joedrago** [comment]
Reading your original request again, I believe your "version listing" request is asking which AV1 codec versions we're using in each release? I think there is a disconnect here and I hope this explains it better.

The versions of libaom, libdav1d, etc that each libavif release "uses" is simply for CI and the automated executables generated for the release. The intent of libavif's codec layer is to be compatible with as many versions of each AV1 library as possible. For example, the most recent release of `libavif` (v0.9.2 as of this writing) should work with any of the past 15+ `dav1d` versions. There is very little restriction/requirement between a specific libavif version and a specific AV1 library version.

A good example would be Arch Linux's build of libavif:

https://archlinux.org/packages/community/x86_64/libavif/

Their [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/libavif/trunk/PKGBUILD) simply depends on `aom`, `dav1d`, `rav1e`, and `svt-av1`, and then enables each of those when configuring CMake. If the dav1d shared library is optimized/updated after the fact, this build should work fine with the updated dav1d shared library.

My recommendation (as hinted in my previous message) would be to mimic this decoupling of AV1 codec version and libavif version, and simply depend on the system-available version. Statically linking any of these into libavif isn't really the right direction for a system-wide library.

**Comment by pierrejoye** [comment]
Perfect! thank you @joedrago , exactly the answer I was looking for, very much appreciated :)

I will do the same and try to document this as well in our doc and if you like, I can add a little README here too to clarify it.
