### ISSUE TITLE
ffmpeg syntax and use-case available for mp4

### ISSUE THREAD

**Issue by dylannirvana** [AOMediaCodec/libavif#771]
Is there a way to convert an mp4 to an _animated_ AVIF(S) using libavif using ffmpeg or similar syntax? 
`libavif import.mp4 -options output.avif`

**Comment by dylannirvana** [comment]
Hi Joe,
I cloned your repo but am unfamiliar with how to set it up for processing the y4m with the avifenc command.

**Comment by BlueSwordM** [comment]
@wantehchang I was under the assumption that avifenc could only encode input streams in all-intra mode, but then I forgot that with a y4m input, it will encode using normal video coding features. The only way to get all intra is to force it with an advanced parameter.

**Comment by 1480c1** [comment]
@wantehchang can confirm your patch works properly and does not break previous cases.

**Comment by dylannirvana** [comment]
Hi @BlueSwordM  
I am able to get the _first part_, conversion to y4m. But the _second part_ fails because I do not have access to the `avifenc` command. 

I have cloned the repo, but am not sure how to utilize the library.

**Comment by dylannirvana** [comment]
> Hi Dylan,
> 
> You can build libavif on Linux as follows:
> 
> ```
> sudo apt-get install zlib1g-dev
> sudo apt-get install libpng-dev
> sudo apt-get install libjpeg-dev
> sudo apt-get install ninja-build
> 
> git clone https://github.com/AOMediaCodec/libavif.git
> cd libavif
> 
> cd ext
> ./aom.cmd
> ./libyuv.cmd
> cd ..
> mkdir build
> cd build
> cmake -G Ninja .. -DBUILD_SHARED_LIBS=OFF \
>     -DAVIF_CODEC_AOM=ON -DAVIF_LOCAL_AOM=ON -DAVIF_LOCAL_LIBYUV=ON \
>     -DAVIF_BUILD_EXAMPLES=ON -DAVIF_BUILD_APPS=ON -DAVIF_BUILD_TESTS=ON \
>     -DCMAKE_BUILD_TYPE=Release
> ninja
> ```
> 
> The `avifenc` program will be in the current directory.

Hi @wantehchang, I am on Mac and am only looking to run a simple installation with access to the _avifenc_ command. I am not sure what these are commands are there to do. 
Thanks for your help.
Dylan
