### ISSUE TITLE
How to build this lib to wasm?

### ISSUE THREAD

**Issue by ahaoboy** [AOMediaCodec/libavif#776]
I want use this lib in browser, but failed. 
![10DB4BA3](https://user-images.githubusercontent.com/19884146/138120815-5ed6abc2-0f03-44d5-af83-f275399ea415.png)

**Comment by wantehchang** [comment]
I believe Squoosh (https://squoosh.app/) also compiles libavif to WebAssembly. You can take a look at its source code (https://github.com/GoogleChromeLabs/squoosh) to see how it builds libavif.
