### ISSUE TITLE
Preserving transparency: MOV to AVIF?

### ISSUE THREAD

**Issue by dylannirvana** [AOMediaCodec/libavif#777]
I have an animation that I am rendering for web. Neither mp4 nor y4m support alpha channels, however. Is it possible to go from a Quicktime file directly to an AVIF, and thus preserve transparency. Or utilize some other tmp (intermediary format) to achieve the result?

For example, something like:
`ffmpeg -i src.mov tmp-that-supports-transparency.something`
`avifenc tmp-that-supports-transparency.something dst.avif` 

Not to complicate things, but it would be good if this could be addressed at the ffmpeg level, so that one could go from _mov to webp_ animation, for example.

**Comment by joedrago** [comment]
Very recent builds of ffmpeg (from the last few months? I can't remember when it was fixed) can emit `yuva444p`, which has alpha. When written to a `.y4m` file (or piped with `yuv4mpegpipe`), `avifenc` can see the alpha and it will be retained. There are some caveats here though for you (based on the environment I believe you have):

* You must have a very recent ffmpeg build
* You must have a very recent avifenc build (newer than any currently released version)

If these are true, this would work:

    ffmpeg -i your.source.file -strict -1 -pix_fmt yuva444p -f yuv4mpegpipe - | avifenc --stdin out.avif

or

    ffmpeg -i your.source.file -strict -1 -pix_fmt yuva444p tmp.y4m
    avifenc tmp.y4m out.avif

I believe @wantehchang is planning to make a new avifenc release soon (`v0.9.3`), which would have all of the latest bugfixes that would allow for this. When he releases that, I can make an effort to update my unofficial build so you can give it a shot.

**Comment by joedrago** [comment]
Alright, I've updated the unofficial homebrew recipe with `v0.9.3`, and I verified with a very recent ffmpeg (`N-104401-gcd38fbf4f7-tessus`) that this works. I generated an orange square image with an alpha gradient:

![orange](https://user-images.githubusercontent.com/332342/138185822-e71ee021-9724-4d87-8c5b-ea2e871e338e.png)

And then I ran:

    ffmpeg -i orange.png -strict -1 -pix_fmt yuva444p -f yuv4mpegpipe - | avifenc --stdin orange.avif

This created a valid `orange.avif` with the gradient intact.

Updating to the latest `avifenc` should be as simple as:

    brew update
    brew install joedrago/repo/avifenc

Updating to the latest ffmpeg is a bit trickier, as it appears homebrew's recipe is a bit old/stale. I happened to download a static build from here: https://www.ffmpeg.org/download.html#build-mac

Running a static build from an untrusted source on macOS requires going into Security and saying "Allow Anyway", etc, and I am not responsible for anything awful that may happen to your machine if you download a bad ffmpeg executable :smile:. Feel free to get a super fresh ffmpeg in whatever way works best for you. This should solve the avifenc side for you at least!

**Comment by salarx** [comment]
@dylannirvana 
can you try this command instead and see if there's change in results?
`ffmpeg -i input.mov -vf "format=yuva444p" -f yuv4mpegpipe -strict -1 - | avifenc --stdin output.avif`

**Comment by joedrago** [comment]
Are you sure your source MOV actually has transparency? Is there any way you could share an example small version of one of these files?

**Comment by dylannirvana** [comment]
The file is huge. Can I use ffmpeg to reduce dimensions to about 1080 while still keeping it an MOV (with transp)?

**Comment by joedrago** [comment]
Part of ffmpeg's magic is that it allows you to pass in _any_ format (including still image formats) and choose any output formats the heart of ffmpeg can happily "not care" and just work. I've already verified that passing in a PNG with transparency as the input to ffmpeg certainly works, which I've already said. This means that ffmpeg's internals maintain alpha and successfully emit them to the y4m, so I'm sure this works.

What I'm _not_ sure about is a MOV that contains transparency. If you have one and say it exists, I believe you, but I don't actually know how alpha is conveyed in BMFF-based video files; I've never seen it.

**Comment by dylannirvana** [comment]
I just did this one out of Photoshop. The quality is less than desirable but it proves that your algorithm works. I am not sure why the sizing one failed. Perhaps you have a more transparent syntax (no pun intended) to change size? 

And ffmpeg allows you to **trim** as well, right?

**Comment by joedrago** [comment]
I'm glad you successfully got a transparent AVIF. You can tune the quality of the resultant AVIF by adding some additional settings on the avifenc commandline, and use ffmpeg's video filters (such as resize) all in the same command as the one that emits the y4m. 

I'm going to close this issue as it sounds like everything is working now. How to do various ffmpeg filters should probably be discussed elsewhere.

**Comment by dylannirvana** [comment]
Thank you! One last question: in using filters like scale and crop, would you do them sequentially (I mean one at a time) or all at once? `ffmpeg -i input.mov -vf "format=yuva444p" scale=1200:675 "crop=1000" -f yuv4mpegpipe -strict -1 - | avifenc --stdin output.avif`
