### ISSUE TITLE
`avifdec in.avif out.png` adds alpha channel even when the input doesn’t have one

### ISSUE THREAD

**Issue by da2x** [AOMediaCodec/libavif#787]
`avifdec any-image.avif output.png` always adds an alpha channel in the output PNG regardless of whether it’s needed or not.

```
Version: 0.9.2 (dav1d [dec]:0.9.1, aom [enc/dec]:v3.1.2, rav1e [enc]:0.4.1 (UNKNOWN), svt [enc]:0.8.6)
libyuv : unavailable
```

**Comment by wantehchang** [comment]
@FrankGalligan I wrote a fix at https://github.com/AOMediaCodec/libavif/pull/1021.

@joedrago I found that PNG also has `PNG_COLOR_TYPE_GRAY` and `PNG_COLOR_TYPE_GRAY_ALPHA`, so AVIF monochrome (YUV 4:0:0) images could be encoded in those two PNG color types.
