### ISSUE TITLE
Gif to y4m to lossless avif: Wrong colours

### ISSUE THREAD

**Issue by utack** [AOMediaCodec/libavif#792]
Hi,

I am trying to convert a gif file, and somehow end up with wrong colours

```
wget -O in.gif https://i.redd.it/q185zgnnqn121.gif
ffmpeg  -i in.gif -pix_fmt yuv444p in.y4m
avifenc -l in.y4m out.avif
```

Hopefully you can reproduce this or tell me where I go wrong
Thank you very much!

Example composite of half gif colours and half output

![2](https://user-images.githubusercontent.com/8551234/140764054-da5c1a20-c426-4c8c-a9d5-52f1b22042fc.png)

**Comment by joedrago** [comment]
I believe this is a bug/oversight when using lossless mode alongside `.y4m` files, unfortunately. 

Lossless AVIFs can only be achieved by using very specific matrix coefficients (0=Identity), which is where we pack RGB data directly into YUV channels (in the order GBR). When using any other input file format, the source channels are RGB, so using `-l` or `--cicp` will cause `avifenc` to convert/pack the RGB pixels into YUV correctly.. However, when using `.y4m`, no conversion occurs as you already have YUV, so it relies on the source Y4M data to be correct. In this case, that would mean that the source Y4M data is already packed GBR. In order for avifenc to solve this, it would need to know that the incoming `.y4m` data doesn't match the CICP you're requesting, and it would have to convert YUV->RGB->YUV, which (ironically) would probably create loss. There's not a great solution for this, for lossless. 

As an aside, why the interest in lossless here? Despite it being supported by AVIF, I don't find lossless AVIF to be very competitive with other lossless formats (in file size), unfortunately. That said, creating an AVIF that is _near_ lossless is a huge win, even against GIF. Assuming we could fix the `.y4m` lossless import, the resultant file here would go from 707k to about 1MB. However, even with `avifenc`'s defaults, the resultant file is only 147k and looks the same to my eyes when viewing in a browser. With some `--min` and `--max` tuning (or some libaom advanced features), I bet you could get that 147k even lower without being able to notice in this GIF.

**Comment by joedrago** [comment]
I hit send too soon. I just realized that the actual issue here is simply that `-l` assumes the incoming data is RGB, as `-l` is really shorthand for `--min 0 --max 0 --cicp 1/13/0`. When importing YUV that you want to be lossless, you simply have to provide your `.y4m`'s correct CICP and it'll use that instead. If you do:

    avifenc --min 0 --max 0 --cicp 1/13/6 in.y4m out.avif

This will behave correctly and give you a lossless AVIF from your source data; no `avifenc` changes are necessary. The file will be quite large here, though. I recommend choosing something other than `0` for min and max here because even a tiny bit of quantization here will significantly shrink the file size and I doubt you'll be able to tell visually.

**Comment by joedrago** [comment]
I played around a bit just to see what the numbers/visuals would look like, so I ran the following on your `in.y4m`:

    avifenc --min 24 --max 26 --cicp 1/13/6 in.y4m min24max26.avif
    avifenc --min 24 --max 46 --cicp 1/13/6 in.y4m min24max46.avif
    avifenc --min 44 --max 63 --cicp 1/13/6 in.y4m min44max63.avif

I got 148k, 131k, and 65k (!). You can definitely see the loss on the smallest one (most notably in blur in the sky), but the largest one is only ~21% the size of the original GIF and looks the same to my eyes.

**Comment by imsys** [comment]
I tired to use the examples in an animated gif I have with a transparent background, but it loses the alpha channel in the process, how can I convert it? Apparently it loses the alpha in the ffmpeg step, as it says `Alpha : Absent`
```
Successfully loaded: SHIP.y4m
AVIF to be written: (Lossy)
 * Resolution     : 1920x1080
 * Bit Depth      : 8
 * Format         : YUV444
 * Alpha          : Absent
 * Range          : Limited
 * Color Primaries: 1
 * Transfer Char. : 13
 * Matrix Coeffs. : 6
 * ICC Profile    : Absent (0 bytes)
 * XMP Metadata   : Absent (0 bytes)
 * EXIF Metadata  : Absent (0 bytes)
 * Transformations: None
 * Progressive    : Unavailable
```

**Comment by joedrago** [comment]
(This comment seems unrelated to the original post and would have been better as its own issue, but I'll reply here.)

This thread has a long explanation of how to make transparent animated AVIFs: https://github.com/AOMediaCodec/libavif/issues/777

It requires a very recent `ffmpeg` and newest `avifenc`, but my early comments give concrete examples of how to do it:

https://github.com/AOMediaCodec/libavif/issues/777#issuecomment-948110662
