### ISSUE TITLE
Install Ubuntu 20.04.3?

### ISSUE THREAD

**Issue by ainsleyclark** [AOMediaCodec/libavif#795]
Hi there,

Apologies for the simple question but is there an `apt-get` for installing on Ubuntu?
I can't see any installation instructions for installing on Linux.

Thanks in advance.

**Comment by wantehchang** [comment]
Hi Ainsley,

I am sorry I missed your question. I am not familiar with Ubuntu. I just did a search for "libavif package ubuntu". This page seems relevant to your question:

https://packages.ubuntu.com/search?keywords=libavif-dev

Comparing with https://packages.ubuntu.com/search?keywords=libaom-dev, I would conclude that the oldest version of Ubuntu with a libavif package is 21.04. So it seems that there is no libavif-dev package for Ubuntu 20.04.3.

**Comment by ainsleyclark** [comment]
Thanks @wantehchang 

Have you seen this before? `ERROR: Failed to encode image: No codec available`

```
Encoding with AV1 codec '(null)' speed [6], color QP [0 (Lossless) <-> 63 (Worst)], alpha QP [0 (Lossless) <-> 0 (Lossless)], tileRowsLog2 [0], tileColsLog2 [0], 1 worker thread(s), please wait...
ERROR: Failed to encode image: No codec available
Successfully loaded: ../../uploads/2020/09/ollie_lounger_1-scaled-1-650x650.jpg
```

I've installed `libavif-dev` and `libavif-bin` on 21.10.

Thanks again.

**Comment by wantehchang** [comment]
Hi Ainsley,

I assume you are using the `avifenc` program. What is your `avifenc` command line?

What is the output of the `avifenc --version` command on your computer?

I built libavif from source code. This is the output of my `avifenc --version` command:

```
$ ./avifenc --version
Version: 0.9.3 (dav1d [dec]:0.9.2-0-g7b433e0, libgav1 [dec]:0.17.0, aom [enc/dec]:3.2.0, rav1e [enc]:0.5.1 (v0.5.1), svt [enc]:v0.9.0)
libyuv : available (1788)

```

**Comment by ainsleyclark** [comment]
My bad @wantehchang 
I was using the wrong permissions, thanks again.
