### ISSUE TITLE
Plan to support for custom encoder like rav1e instead of aom ?

### ISSUE THREAD

**Issue by dreampiggy** [AOMediaCodec/libavif#8]
Hi. I'm a user who previouslly use the libavif 0.1.x version.

Recently I found that this library supports two decoder codec, **aom** and **dav1d**, and the test performance of the dav1d is better than the aom.

Is there any plan to support another AVIF encoder implementation [rav1e](https://github.com/xiph/rav1e) ?

Just a little curious about the plan for the massive AV1 codec...

**Comment by joedrago** [comment]
I don't have any specific plans right now to add any codecs, but I'm certainly not against it.

The pattern I put in place when I added dav1d would translate well to an encoder-only codec; I would just make it so that enabling it would override the encoding role from libaom, and if enabled in conjunction with dav1d, would avoid aom entirely.

**Comment by joedrago** [comment]
I implemented basic rav1e support today. If you read/execute rav1e.cmd in ext/, you should be able to build with `-DAVIF_CODEX_RAV1E=1 -DAVIF_LOCAL_RAV1E=1` and it'll find the library and link against it.

I've only tested on windows-msvc (2017) and macOS Catalina.

**Comment by AurelC2G** [comment]
Thanks for working on this!

I noticed a small issue with how you pass quantizer values to rav1e:

```
    int minQuantizer = AVIF_CLAMP(encoder->minQuantizer, 0, 63);
    int maxQuantizer = AVIF_CLAMP(encoder->maxQuantizer, 0, 63);
    if (alpha) {
        minQuantizer = AVIF_QUANTIZER_LOSSLESS;
        maxQuantizer = AVIF_QUANTIZER_LOSSLESS;
    }
    if (rav1e_config_parse_int(rav1eConfig, "min_quantizer", minQuantizer) == -1) {
        goto cleanup;
    }
    if (rav1e_config_parse_int(rav1eConfig, "quantizer", maxQuantizer) == -1) {
        goto cleanup;
    }
```

Values for min/max quantizer in libavif are in the [0, 63] range, but in rav1e they are in [0, 255] (see https://github.com/xiph/rav1e/blob/master/src/capi.rs#L490), so clamping like you are here restricts the encoder to a small range of quantizer values.

**Comment by joedrago** [comment]
Excellent catch on the QP, I believe I've fixed it here:

https://github.com/AOMediaCodec/libavif/commit/0abf3b329db8bc05fac298a3856b5a516be81444

And yes, I was pleasantly surprised at rav1e's speed as well. If someone builds colorist (a tool of mine that uses libavif) with both rav1e and aom, I choose rav1e for encoding if aom isn't explicitly specified.
