### ISSUE TITLE
AVIF > Y4M > AVIF gives "Failed to read line"

### ISSUE THREAD

**Issue by y-guyon** [AOMediaCodec/libavif#801]
Starting image ![debug](https://user-images.githubusercontent.com/51164219/145604124-0353909c-e861-49e3-ba91-d15c6ce93364.png) (4 × 4 pixels) but a bigger one fails too (I also tried 1160 × 872 pixels).
```sh
avifenc 4x4px.png img.avif  # Not part of this bug report but I cannot attach an .avif directly

avifdec img.avif    avifdec.y4m   # Returns 0, no displayed error
avifenc avifdec.y4m avifenc.avif  # Error code 1, "Failed to read line"
```

The generated .y4m is likely faulty: it is 1989 bytes long.
```
YUV4MPEG2 W4 H4 F25:1 Ip A0:0 C444 XYSCSS=444 XCOLORRANGE=FULL
FRAME
06 4B 9B FC FE FE FE FE 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ...
```

I am investigating the issue.

**Comment by wantehchang** [comment]
@y-guyon fixed this issue with https://github.com/AOMediaCodec/libavif/pull/802.
