### ISSUE TITLE
Handle out-of-memory errors, such as avifAlloc() failures

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#820]
This issue tracks the work on handling out-of-memory errors, starting with avifAlloc() failures.

I will do this work in installments because this requires a lot of changes.

**Comment by y-guyon** [comment]
All `avifAlloc()` calls should be checked now.

**Comment by vrabaud** [comment]
I confirm all avifAlloc are checked.

**Comment by wantehchang** [comment]
Yannis: Thank you very much for all your work on this issue! This is an enormous amount of work and requires patience and perseverance.

I changed the assignee to you and removed myself. (The initial work I did is insignificant compared with what you have done.)

Does this mean we can remove the abort() call in avifAlloc() now?

**Comment by y-guyon** [comment]
Thanks.

> Does this mean we can remove the abort() call in avifAlloc() now?

Yes. I was wondering if adding a test or fuzz target to exercise `malloc()` failures would be worth it. Maybe it can be done after the change.

**Comment by y-guyon** [comment]
Once the changes above are merged, the `apps` and `src` folders are handled.

There are a few allocations in `third_party/libyuv` (a small portion of code copied from upstream [libyuv](https://chromium.googlesource.com/libyuv/libyuv/)). These are not checked.  
Unfortunately it also means using the whole libyuv library as a dependency is a liability. I filed https://bugs.chromium.org/p/libyuv/issues/detail?id=968.

I can imagine other dependencies such as libaom bringing the same risk. Should this bug be closed before all dependencies are safe?

**Comment by wantehchang** [comment]
I suggest closing this issue as completed and open a new issue about libyuv.

Unlike libyuv, libaom aims to handle memory allocation failures (see https://crbug.com/aomedia/3276), so it doesn't seem necessary to file a new issue about libaom.

**Comment by wantehchang** [comment]
Sorry, I forgot about the code in third_party/libyuv. In my previous comment, I was referring to the upstream libyuv.

We can probably also open a new issue about the code in third_party/libyuv. Or we can leave this issue open until that code is fixed.

**Comment by y-guyon** [comment]
> we can leave this issue open until that code is fixed.

I agree.

> Unlike libyuv, libaom aims to handle memory allocation failures (see https://crbug.com/aomedia/3276), so it doesn't seem necessary to file a new issue about libaom.

Great. What about other dependencies, especially dav1d? I think libsharpyuv is fine too, right @vrabaud?

**Comment by vrabaud** [comment]
Indeed, fr libsharpyuv, allocs are only done in one spot and they are checked: https://chromium.googlesource.com/webm/libwebp/+/refs/heads/main/sharpyuv/sharpyuv.c#331

**Comment by wantehchang** [comment]
Yannis: I randomly inspected a few calls to `dav1d_malloc()` and `dav1d_alloc_aligned()` in dav1d. It's clear that dav1d handles memory allocation failures.

**Comment by y-guyon** [comment]
> There are a few allocations in third_party/libyuv (a small portion of code copied from upstream [libyuv](https://chromium.googlesource.com/libyuv/libyuv/)). These are not checked.

Now that it is done, all core library places should be checked now.
