### ISSUE TITLE
avifImageYUVToRGBLibYUV() 10bpc Support

### ISSUE THREAD

**Issue by joedrago** [AOMediaCodec/libavif#822]
I believe @tongyuantongyu may have added proper 10bpc support to libyuv at some point in the past, but it doesn't look like we leverage it in `avifImageYUVToRGBLibYUV()`:

    if ((image->depth != 8) || (rgb->depth != 8)) {
        return AVIF_RESULT_NOT_IMPLEMENTED;
    }

We should allow for 10bpc to use libyuv if the version is sufficiently recent.

**Comment by wantehchang** [comment]
Joe: This is a good idea. Looking at the Chrome source code https://source.chromium.org/chromium/chromium/src/+/main:media/renderers/paint_canvas_video_renderer.cc, I think we can use I010ToARGBMatrix() for 10bpc YUV 4:2:0 and I210ToARGBMatrix() for 10bpc YUV 4:2:2.

Yuan Tong: Is there a libyuv function for 10bpc YUV 4:4:4?

**Comment by tongyuantongyu** [comment]
> Is there a libyuv function for 10bpc YUV 4:4:4?
In libyuv 1780 I introduced I410ToARGBMatrix for 10bpc YUV 4:4:4, and I[420]10AlphaToARGBMatrix for their alpha variant.
In libyuv 1781 Frank Barchard introduced I012ToARGBMatrix for 12bpc YUV 4:2:0.

**Comment by wantehchang** [comment]
> In libyuv 1780 I introduced I410ToARGBMatrix for 10bpc YUV 4:4:4, and I[420]10AlphaToARGBMatrix for their alpha variant.
> In libyuv 1781 Frank Barchard introduced I012ToARGBMatrix for 12bpc YUV 4:2:0.

@tongyuantongyu Thank you for the info. I found that these functions convert to 8bpc RGB. Are there libyuv functions that convert 10bpc YUV to 10bpc RGB?

**Comment by tongyuantongyu** [comment]
> convert 10bpc YUV to 10bpc RGB
I believe that libavif only support 8 and 16 bit for RGB?

Anyway, there's a 10bpc RGB format supported in libyuv called AR30. It packed 10bit RGB and 2bit A into a 32 bit word, but libavif doesn't support it.

libyuv currently doesn't support converting to 16 bit RGB (both integer and float). I may take a look on adding it, but libyuv works on 16 bit Y and 8 bit UV internally so precision may become a problem.

**Comment by wantehchang** [comment]
libavif supports the following bit depths for RGB: 8, 10, 12, and 16.

Before you start working on libyuv, it would be good for us to gather requirements. For example, in Chrome and Android we need to convert to half-float RGB. I think Joe is interested in converting to 16 bit integer (unorm) RGB.

**Comment by joedrago** [comment]
The current half float path converts to unorm16 first, so if you are going to support halfs, you get unorm16 too.

**Comment by tongyuantongyu** [comment]
> libavif supports the following bit depths for RGB: 8, 10, 12, and 16.

Oh I was assuming libavif not bother supporting 10 and 12 bit as almost nowhere use them. Probably libyuv won't support them unless there's demand to actually consuming these format.

> it would be good for us to gather requirements

Yes I did some work on this. Usually, when related to rendering or GPU, half float is used; otherwise integer (unorm) version is used.

libyuv internally converts to 16 bit unorm RGB first, so supporting unorm is quite easy.

For half float,converting unorm16 to half float with normalization is easy, but I vaguely remember that Chrome or Android (or maybe both?) expect linear RGB value instead of the gamma (PQ or HLG in HDR world) corrected value?

> The current half float path converts to unorm16 first

In libyuv we will probably do the conversion in one step, given its broad usage in HDR handling. unorm16 values will just temporarily live in register, instead of written to memory first and then converted.

**Comment by joedrago** [comment]
Linearizing HDR content in a half float isn't enough precision unless you apply a scale (use more than 0.0-1.0), and is not something I think libavif should offer, either way. If you want to add support for linearization in libyuv independent of libavif, go for it, but I think all YUV conversion offered by libavif should ignore the transfer function and leave it to downstream tools to do something with it.

**Comment by joedrago** [comment]
Err, I might be wrong about the loss of precision for normalized, That was the top of head. Either way, I think we should not get involved with transfer functions.

**Comment by wantehchang** [comment]
Just FYI: I addressed the Chromium version of this issue in https://crrev.com/c/3441635.
