### ISSUE TITLE
Add SVT-AV1 to the CI

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#830]
I just found that https://github.com/AOMediaCodec/libavif/blob/master/.github/workflows/ci.yml does not currently build SVT-AV1. We should add SVT-AV1 to our CI.

We should also add SVT-AV1 to tests/docker/build.sh.

@EwoutH I am wondering if you could take a stab at this. Thank you.

**Comment by EwoutH** [comment]
I looked shorty into it, but I'm not that up to speed anymore with the libavif built setup, and unfortunately I'm quite busy the coming weeks.
