### ISSUE TITLE
Decoder error for win32

### ISSUE THREAD

**Issue by Jamaika1** [AOMediaCodec/libavif#836]
avifenc.exe -c aom -l -d 8 -y 444 -r full -s 5 -j 4 image_21447_24bit.png image_21447_24bita.avif
```
Successfully loaded: image_21447_24bit.png
AVIF to be written: (Lossless)
 * Resolution     : 1563x1558
 * Bit Depth      : 8
 * Format         : YUV444
 * Alpha          : Not premultiplied
 * Range          : Full
 * Color Primaries: 1
 * Transfer Char. : 13
 * Matrix Coeffs. : 0
 * ICC Profile    : Absent (0 bytes)
 * XMP Metadata   : Absent (0 bytes)
 * EXIF Metadata  : Absent (0 bytes)
 * Transformations: None
 * Progressive    : Unavailable
Encoding with AV1 codec 'aom' speed [5], color QP [0 (Lossless) <-> 0 (Lossless)], alpha QP [0 (Lossless) <-> 0 (Lossless)], tileRowsLog2 [0], tileColsLog2 [0], 4 worker thread(s), please wait...
Encoded successfully.
 * Color AV1 total size: 3729446 bytes
 * Alpha AV1 total size: 0 bytes
Wrote AVIF: image_21447_24bita.avif
```
avifdec.exe -c dav1d -j 4 image_21447_24bita.avif 222.jpg
```
Decoding with AV1 codec 'dav1d' (4 worker threads), please wait...
ERROR: Failed to parse image: BMFF parsing failed
Diagnostics:
 * Box[iloc] has an invalid item ID [0]
```

**Comment by Jamaika1** [comment]
av1enc.exe -avif -q 100 -444 -size 1563x1558 -effort 5 -thread 4 image_21447_24bit.png -d image_21447_24bitw.avif
ERROR: Failed to decode: BMFF parsing failed
Error while computing the distortion.

**Comment by wantehchang** [comment]
Jamaika1: Thank you for the bug report. I am very sorry about the bug. I just merged the bug fix (https://github.com/AOMediaCodec/libavif/pull/835). Please update your libavif source tree to commit d9cffc5f46b62aeff46eebf51449726386d6c485.

**Comment by wantehchang** [comment]
> av1enc.exe -avif -q 100 -444 -size 1563x1558 -effort 5 -thread 4 image_21447_24bit.png -d image_21447_24bitw.avif

Jamaika1: What is av1enc.exe?

**Comment by Jamaika1** [comment]
Avif fix works. Thanks.
For those willing. Jamaika also makes mistakes. ;) I haven't checked for win64

av1enc.exe is libwebp2 with avif and aom

```
avifenc.exe -c svt -d 8 -y 420 -r limited -s 5 -j 4 image_21447_24bit.jpg image_21447_24bita.avif
Successfully loaded: image_21447_24bit.jpg
AVIF to be written: (Lossy)
 * Resolution     : 1563x1558
 * Bit Depth      : 8
 * Format         : YUV420
 * Chroma Sam. Pos: 0
 * Alpha          : Absent
 * Range          : Limited
 * Color Primaries: 1
 * Transfer Char. : 13
 * Matrix Coeffs. : 6
 * ICC Profile    : Absent (0 bytes)
 * XMP Metadata   : Absent (0 bytes)
 * EXIF Metadata  : Absent (0 bytes)
 * Transformations: None
 * Progressive    : Unavailable
Encoding with AV1 codec 'svt' speed [5], color QP [24 (Medium) <-> 26 (Medium)], alpha QP [0 (Lossless) <-> 0 (Lossless)], tileRowsLog2 [0], tileColsLog2 [0], 4 worker thread(s), please wait...
Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:       SVT-AV1 Encoder Lib 0.9.0-35180cc
Svt[info]: SVT [build]  :       GCC 12.0.0 20211203 (experimental)       32 bit
Svt[info]: LIB Build date: Jan 30 2022 08:45:09
Svt[info]: -------------------------------------------
Svt[info]: Number of logical cores available: 4
Svt[info]: Number of PPCS 41
Svt[info]: [asm level on system : up to c]
Svt[info]: [asm level selected : up to c]
Svt[info]: -------------------------------------------
Svt[info]: SVT [config]: Main Profile   Tier (auto)     Level (auto)
Svt[info]: SVT [config]: Preset                                                         : 5
Svt[info]: SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat  : 8 / 1 / 0
Svt[info]: SVT [config]: SourceWidth / SourceHeight                                     : 1568 / 1560
Svt[info]: SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType  : 60000 / 1000 / 129 / 2
Svt[info]: SVT [config]: HierarchicalLevels  / PredStructure                            : 4 / 2
Svt[info]: SVT [config]: BRC Mode / Rate Factor / SceneChange                           : CRF / 26 / 0
Svt[info]: -------------------------------------------
SvtMalloc[fatal]: allocate memory failed, at EbEncHandle.c, L2288
ERROR: Failed to encode image: Encoding of color planes failed
SvtMalloc[info]: you have no memory leak
```

**Comment by wantehchang** [comment]
Jamaika1: Thank you for testing the bug fix.

The new avifenc.exe command output has the following error messages:

> SvtMalloc[fatal]: allocate memory failed, at EbEncHandle.c, L2288
> ERROR: Failed to encode image: Encoding of color planes failed

Does this mean there is a bug?

I tested avifenc with SVT-AV1 v0.9.0 on Linux x64. It worked for me.

**Comment by Jamaika1** [comment]
I spent a lot of time testing.
I was asked why I put codecs under win64 and not win32 on the doom9 forum? Not professional creation.
So I'm trying to make codecs under win32.

Weird. The codec works only under WIN64.

**Comment by 1480c1** [comment]
Are you talking about SVT-AV1 working only under 64-bit systems?

https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/CMakeLists.txt#L37

https://gitlab.com/AOMediaCodec/SVT-AV1#system-requirements

We specifically list that we only support 64-bit systems, so it's not really weird, and there's a lot of code inside SVT-AV1 that specifically relies on assumptions made for 64-bit systems, such as the pointer size being 64-bit and not 32-bit.
