### ISSUE TITLE
Conan packaging

### ISSUE THREAD

**Issue by friendlyanon** [AOMediaCodec/libavif#837]
Hey there, just letting you know that I am in the process of packaging this library for Conan: https://github.com/conan-io/conan-center-index/pull/9225

The CMake scripts are workable of this project, however I had to add a patch to disable code that is only relevant for development. It would be nice if that code was opt-in by default.  
Another thing that seems flaky is the libyuv version detection. Conan Center Index ships version 1764 at the moment, which still passes the check for <1755, but the path intended for >=1774 is executed regardless, which results in an undefined reference to `ScalePlane_12` error when linking.

**Comment by joedrago** [comment]
The ScalePlane_12 build issue was fixed a few weeks ago, unfortunately after the v0.9.3 release. The next release eonn't have that problem.

**Comment by friendlyanon** [comment]
> Could you explain why you need to apply the patch 0001-disable-developer-only-codepaths.patch to CMakeLists.txt? The code removed by that patch seems harmless to me.

It makes assumptions for the user that are not necessary. An especially bad example:

https://github.com/AOMediaCodec/libavif/blob/d9cffc5f46b62aeff46eebf51449726386d6c485/CMakeLists.txt#L178-L180

There are far more compilers out there than just Clang, gcc and MSVC :)  
Let the user decide for themselves what flags they want to use as well. CMake provides many variables to control what additional things to pass to the compiler that can be set from the command-line, toolchain files or presets. Presets are especially nice, because you can set them up for CI and share the settings for development workflows, all while keeping the CML file clean like in this [example](https://github.com/friendlyanon/cmake-init-shared-static/blob/master/CMakePresets.json#L56-L69). If you check the CML for that example repo, you can see that there is absolutely no trace of anything on the default code path other than build requirements and usage requirements. Everything related to developers must be enabled, which can be done comfortably using presets as well. Check the HACKING document in the repo.

Regarding the target name: https://cmake.org/cmake/help/latest/command/target_link_libraries.html

> Items containing `::`, such as `Foo::Bar`, are assumed to be [IMPORTED](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#imported-targets) or [ALIAS](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#alias-targets) library target names and will cause an error if no such target exists.

**Comment by wantehchang** [comment]
Thanks for the reply.

You can apply https://github.com/AOMediaCodec/libavif/commit/ded15fb7b41b0513e138ba457034a2fb91c1f2c9 as a patch to libavif v0.9.3 to fix the ScalePlane_12 build issue.

**Comment by friendlyanon** [comment]
https://conan.io/center/libavif 🥳

**Comment by HappySeaFox** [comment]
Is `libavif::libavif` a correct name to use in my component's `requires`? Using `libavif::libavif` leads to linking errors: https://c3i.jfrog.io/c3i/misc/logs/pr/10364/48-linux-gcc/sail/0.9.0//cb507183b78f80a724b865c573bc22e9e5d25bc2-build.txt

```
[ 59%] Linking C shared library ../../../lib/libsail-codecs.so
sail/0.9.0: 

/usr/bin/ld: /home/conan/w/prod/BuildSingleReference/.conan/data/libavif/0.9.3/_/_/package/0b49fc3e6fe5dc28a13dde5d4bb7c2d2060f2adf/lib/libavif.a(reformat_libyuv.c.o): in function `avifImageYUVToRGBLibYUV':
reformat_libyuv.c:(.text+0x73): undefined reference to `kYvuI601Constants'
/usr/bin/ld: reformat_libyuv.c:(.text+0x7a): undefined reference to `kYuvI601Constants'
/usr/bin/ld: reformat_libyuv.c:(.text+0xd2): undefined reference to `kYvu2020Constants'

...

/usr/bin/ld: /home/conan/w/prod/BuildSingleReference/.conan/data/libavif/0.9.3/_/_/package/0b49fc3e6fe5dc28a13dde5d4bb7c2d2060f2adf/lib/libavif.a(reformat_libyuv.c.o): in function `avifImageYUVToRGBLibYUV':
reformat_libyuv.c:(.text+0x73): undefined reference to `kYvuI601Constants'
/usr/bin/ld: reformat_libyuv.c:(.text+0x7a): undefined reference to `kYuvI601Constants'
/usr/bin/ld: reformat_libyuv.c:(.text+0xd2): undefined reference to `kYvu2020Constants'
```

**Comment by y-guyon** [comment]
May it be because `kYvuI601Constants` is part of [libyuv](https://chromium.googlesource.com/libyuv/libyuv/+/d62ee21e6627888e84466b5a5ed15775582ac67b/include/libyuv/convert_argb.h#33) and not libavif? I am not knowledgeable about Conan but libyuv might be needed too.

**Comment by friendlyanon** [comment]
libavif is built, tested and provided as a static library in Conan Center Index. Here are the last build logs from the PR that added the recipe: https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/9225/6/summary.json  
Note the `False` rows for the `shared` column.

You can also see in the recipe that dependencies are propagated:

https://github.com/friendlyanon/conan-center-index/blob/a2fb8771d6b55f6a4ff57001b5c4d5a1d15f2728/recipes/libavif/all/conanfile.py#L98-L101

Also a snippet from the generated CMake files:

```cmake
set(avif_LIBRARIES_TARGETS_RELEASE "${avif_LIBRARIES_TARGETS_RELEASE};libyuv::libyuv;libaom-av1::libaom-av1;dav1d::dav1d")
```

The above is added as a usage requirement to the `avif` target created by the `libavif` CMake package. See the recipe's test code in action:

https://github.com/friendlyanon/conan-center-index/blob/a2fb8771d6b55f6a4ff57001b5c4d5a1d15f2728/recipes/libavif/all/test_package/CMakeLists.txt#L7-L10

**Comment by HappySeaFox** [comment]
@friendlyanon Thanks for the response. Yes, libavif can be built by conan by obviously there is a problem using it.

What's the correct name to specify in my component's `requires`? When I specify `avif`, conan complains that the libavif dependency is unused. The only (partially) working combination is `libavif::libavif`. It links against `avif`, but eventually fails in the linking phase.

**Comment by friendlyanon** [comment]
Ah, I see this is for https://github.com/conan-io/conan-center-index/pull/10364

I see that SpaceIm has started reviewing the PR and suggesting changes.

**Comment by HappySeaFox** [comment]
Yeah, SpaceIm pointed out that there is a potential issue in my code. Thanks for the recipe, I'll try to fix the issue on my side.
