### ISSUE TITLE
Synchronize the placement of AV1 key frames when encoding an animated AVIF file with alpha

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#841]
We discovered this issue while investigating [Chrome bug 1274200](https://crbug.com/1274200). When encoding an animated AVIF file with alpha, the libavif encoder creates two AV1 encoders to encode the color planes and the alpha plane separately. This issue stems from the fact that by default, we let these two AV1 encoders pick their own key frames. So it is possible that for a particular frame, the color planes are encoded as an AV1 key frame but the alpha plane is not.

If `avifDecoderIsKeyframe()` only checks the `sync` flag of the color planes (which is the case before commit https://github.com/AOMediaCodec/libavif/commit/91bc33a6bd761f70013d7f0f041262626e1d5cad), then we may seek to a frame in which the color planes are an AV1 key frame but the alpha plane isn't an AV1 key frame, which will cause an alpha plane decode failure.

The following is the solution outlined by Joe Drago:

We can avoid this problem by detecting when we have just encoded a color frame that happens to be a key frame,
 and forcing all other tiles/planes for that specific frame to also be a key frame. There's a point where we walk all tiles in src/write.c and encode all of them. The fix would simply be to check if the first tile we encoded is a key frame,
 and if so, force it on all other tiles for this frame
 using the flag `AVIF_ADD_IMAGE_FLAG_FORCE_KEYFRAME`.

**Comment by TroyKomodo** [comment]
👍 Thank you <3

**Comment by vigneshvg** [comment]
This issue is now fixed when using libaom.

rav1e and SVT-AV1 do not support disabled lagged encoding, so they may not sync the keyframes between the color and the alpha planes.
