### ISSUE TITLE
Mark the input images of an image grid as hidden image items

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#851]
Yannis Guyon found that when using GIMP to view an AVIF grid image encoded by avifenc, GIMP asked the user to select an image to display from a list of not only the image grid item but also its input images (i.e., tiles). Leo Barnes pointed out that this is because the input images were not marked as hidden image items.

The libavif encoder should mark the input images of an image grid as hidden image items.

**Comment by y-guyon** [comment]
GIMP prompt example of an AVIF image encoded with `avifenc --grid1x5`:
![image8](https://user-images.githubusercontent.com/51164219/154445289-bc44633b-1abe-4923-9b2c-a8bc8d9d2419.png)
