### ISSUE TITLE
Test libavif with libwebp2 for depth>8

### ISSUE THREAD

**Issue by Jamaika1** [AOMediaCodec/libavif#869]
The topic has surpassed me, but maybe someday I will come back to it.
Why is aom planes[0] or avifImageCreate() only 8bit?
https://github.com/Jamaika1/libavif/tree/patch-15

**Comment by y-guyon** [comment]
You can create a 10-bit `avifImage` with the following:
```c++
avifImage * image = avifImageCreate(width, height, 10, AVIF_PIXEL_FORMAT_YUV420);
avifImageAllocatePlanes(image, AVIF_PLANES_YUV);
```
And then access the 10-bit pixels with the following:
```c++
uint16_t * luma_pixels = (uint16_t *)image->yuvPlanes[0];
```
The pixels are stored into 16-bit unsigned integers and referenced by a `uint8_t*` pointer for easier row-by-row browsing, as the 
`yuvRowBytes` stride is expressed in bytes. See [this example](https://github.com/AOMediaCodec/libavif/blob/ccde367c896798bf7f4535eb563cb268be30ca83/src/scale.c#L108) of how `yuvPlanes` is accessed depending on `depth`.

I do not see how your question relates to libwebp2 nor aom though.

**Comment by Jamaika1** [comment]
I can't deal with kDepth in aom_utils.cc. 
```
  constexpr int kDepth = 8;
  const avifPixelFormat format = is_monochrome       ? AVIF_PIXEL_FORMAT_YUV400
                                 : params.use_yuv444 ? AVIF_PIXEL_FORMAT_YUV444
                                                     : AVIF_PIXEL_FORMAT_YUV420;
  avifImage* const image = avifImageCreate(w, h, kDepth, format);
```

**Comment by y-guyon** [comment]
> av1enc.exe -avif -depth 10 -q 100 -420 -size 1563x1558 -effort 5 -tune ssim -thread 4 image_21448_24bit(s)_YCbCr.jxt -d av1enc_30bit_ssim.avif

`av1enc` has currently no `-depth` flag because `aom_utils.cc` only handles 8-bit images currently. May I ask why you prefer libwebp2's `av1enc` over libavif's `avifenc` or other tools?
