### ISSUE TITLE
New release tag v0.9.4 ?

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#891]
Hello,

some time passed since 0.9.3 version.

New svt-av1no longer works with 0.9.3, so new release would be useful. Lot of other things were implemented too.

Can we have a new release in the near future?

**Comment by wantehchang** [comment]
Hello Daniel,

Thank you for the suggestion. I can create a new release tag. It will be v0.10.0 because there is a breaking change (a new field in the avifDecoder struct) but it is still a pre-release. I estimate the new release tag will be done in two or three weeks.

**Comment by novomesk** [comment]
Thanks, that's fine for me.

**Comment by wantehchang** [comment]
Fixed. The v0.10.0 release tag has been published.
