### ISSUE TITLE
Recent upgrade to gnome-42 breaks heif/avif gdk-pixbuf loader

### ISSUE THREAD

**Issue by ikelos** [AOMediaCodec/libavif#901]
I recently upgraded to gnome-42, and now can't use the gdk-pixbuf loader.  This happens both with a vala program, and is reproducible using python gobject introspection.  Here's my example that fails:

```
>>> import gi
>>> gi.require_version('GdkPixbuf', '2.0')
>>> from gi.repository.GdkPixbuf import Pixbuf
>>> 
>>> imageFile = Pixbuf.new_from_file('<valid.avif file>')

** (process:1942245): WARNING **: 20:34:30.158: Decoder plugin generated an error: Unspecified

(process:1942245): GdkPixbuf-WARNING **: 20:34:30.159: Bug! gdk-pixbuf loader 'heif/avif' didn't set an error on failure.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Failed to load image “<valid.avif file>”: reason not known, probably a corrupt image file (5)
```
I tried downgrading from gdk-pixbuf 2.42.8 down to 2.42.6, no improvement.  I've tried libavif-0.93 and the latest git commit, they all failed with the same error.  Something's changed after a recent update to gnome-42 but I haven't been able to identify what yet.

It appears as though creation works just fine (the image is successfully created and valid):

```
>>> import gi
>>> gi.require_version('GdkPixbuf', '2.0')
>>> from gi.repository.GdkPixbuf import Pixbuf
>>> 
>>> imageFile = Pixbuf.new_from_file('<valid png file>')
>>> imageFile.savev('new.avif', 'avif', [], [])
True
>>> 
```

I'm happy to run tests or provide more information if you let me know what you need.  If this bug actually belongs with gdk-pixbuf, let me know and I'll go file it with them (although loading a jpg or png file using the same snippet works fine).

**Comment by wantehchang** [comment]
@novomesk Daniel, could you take a look at this issue? Thanks.

**Comment by novomesk** [comment]
I suspect that heif/avif plug-in is another plug-in from libheif:
https://github.com/strukturag/libheif/blob/5a7b2f4ec49c3788460db698cb68223d537ea4c5/gdk-pixbuf/pixbufloader-heif.c#L206

If that is the case, I am curious what happens if the libheif's plug-in is uninstalled.

**Comment by ikelos** [comment]
Thanks!  You were absolutely right, removing libheif completely restored loading functionality.  Sorry for the noise!  I don't know if there's a way of indicating to the user that there are two competing handlers, but I guess that's a problem for gdk-pixbuf?  Happy to have this closed if there's not a great deal to be done for it...

**Comment by novomesk** [comment]
I suggest to try how it works when only plug-in from libheif is installed.

Maybe two loaders is not the root of the problem.

**Comment by ikelos** [comment]
You're right, it does appear to be the libheif gdk-pixbuf implementation that's at fault..
