### ISSUE TITLE
Lossy/Lossless field in the avifImage struct?

### ISSUE THREAD

**Issue by alfiedotwtf** [AOMediaCodec/libavif#931]
Is there any way of adding a new field to query if an `avifImage` is lossy/lossless? I tried adding one, but AFAICS the only place that's known in `libavif` is within the Encoder.

I also tried finding the AVIF spec to see what was needed, but I can't find an actual link to the spec.

**Comment by joedrago** [comment]
There isn't such a thing in the file format, sorry. You could make assumptions I'd you happened to see Identity as the MC, but there are no guarantees.
