### ISSUE TITLE
how to crop image using libavif api

### ISSUE THREAD

**Issue by NarayanBissoyi** [AOMediaCodec/libavif#938]
how to crop an image using libavif api. There is a struct named `avifCropRect` . But there is no example available .

**Comment by joedrago** [comment]
The AVIF standard offers a handful of ways to signal transformations in the container that aren't actually a part of the encoded image itself. These are surfaced in `avifImage`'s `transformFlags` and its associated structures (such as `avifCleanApertureBox`). These transformations are surfaced along with the unaltered image data from the file for the caller to leverage (outside of the scope of libavif).

The existence of the struct `avifCropRect` is simply to facilitate making sense (bidirectionally) of the `avifCleanApertureBox` ("clap") box inside of the AVIF container, as it isn't obvious how to interpret it. It is up to the caller to interpret all `transformFlags` during their usage of the decoded data (render, etc).

**Comment by NarayanBissoyi** [comment]
thank for your answer.
Can i crop a image using the struct 
during decoding?

**Comment by y-guyon** [comment]
The following snippet will decode `path/to/img.avif` and extract a window of 3 by 4 pixels located at coordinates 1,2:
```c
avifDecoder * decoder = avifDecoderCreate();
avifImage * image = avifImageCreateEmpty();
avifDecoderReadFile(decoder, image, "path/to/img.avif");
avifDecoderDestroy(decoder);

avifImage * crop = avifImageCreateEmpty();
avifCropRect rect = {1, 2, 3, 4};
avifImageSetViewRect(crop, image, &rect);
// Use crop->yuvPlanes

avifImageDestroy(image);
avifImageDestroy(crop);
```

**Comment by NarayanBissoyi** [comment]
thank you so much y-guyon
