### ISSUE TITLE
How to subsample or scale an image ?

### ISSUE THREAD

**Issue by NarayanBissoyi** [AOMediaCodec/libavif#951]
libwebp allow scaling images .
But i dont know how to scale or subsample an image in libavif .
Is there any support available or not in libavif?

**Comment by y-guyon** [comment]
There is [`avifImageScale()`](https://github.com/AOMediaCodec/libavif/blob/44b086a31433e63f84d9a4e6cca49e311d7c9833/include/avif/internal.h#L165) in `internal.h` but unfortunately it is not exposed through the public API. See related https://github.com/AOMediaCodec/libavif/pull/937.

There is no direct subsampling function even internally. You can see how it is done when reading RGB samples into YUV 4:2:0 [here](https://github.com/AOMediaCodec/libavif/blob/44b086a31433e63f84d9a4e6cca49e311d7c9833/src/reformat.c#L328).

**Comment by NarayanBissoyi** [comment]
> You may also want to take a look at [libyuv](https://chromium.googlesource.com/libyuv/libyuv/+/refs/heads/main/include/libyuv/scale.h), which is used by libavif.

I will look into it

**Comment by yufengvac** [comment]
> > You may also want to take a look at [libyuv](https://chromium.googlesource.com/libyuv/libyuv/+/refs/heads/main/include/libyuv/scale.h), which is used by libavif.
> 
> I will look into it

How did you solve it in the end？I also encountered this problem

**Comment by NarayanBissoyi** [comment]
I am  working on it . you can scale
with libyuv but not with desired sample size as in android api.
