### ISSUE TITLE
Reformat failed with correct images

### ISSUE THREAD

**Issue by NarayanBissoyi** [AOMediaCodec/libavif#958]
images are displaying correctly in chrome and firefox . but when i 
converting the image to YUV to RGB 
; its showing the error reformat failed.
the same image are decoded correctly with the library . but when i trying to convert it to rgb its showing the error. below is the source of my program ----
--************
/*
 *clang avif-decode.c -o avif-decode -lavif  -laom -lm -lpthread -lyuv
 *
 */

#include <avif/avif.h>

#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*******************************************/ 
 	int main(int argc , char* argv[]) {
 	         
const char *inputfilename = argv[1];
const char * outputfilename = NULL;
int requestedDepth = 0;
int jobs = 2;

avifCodecChoice codecChoice = AVIF_CODEC_CHOICE_AUTO;
avifChromaUpsampling chromaUpsampling = AVIF_CHROMA_UPSAMPLING_AUTOMATIC;
avifStrictFlags strictFlags = AVIF_STRICT_DISABLED;
avifBool allowProgressive = AVIF_FALSE;
uint32_t imageSizeLimit = AVIF_DEFAULT_IMAGE_SIZE_LIMIT;
 avifRGBImage rgb;
    memset(&rgb, 0, sizeof(avifRGBImage));

      avifDecoder * decoder = avifDecoderCreate();
      	decoder->maxThreads = jobs;
      	decoder->codecChoice = codecChoice;
      	decoder->imageSizeLimit = imageSizeLimit;
      	decoder->strictFlags = strictFlags;
      	decoder->allowProgressive = allowProgressive;
      	
   avifResult result = avifDecoderSetIOFile(decoder,inputfilename);
   if(result != AVIF_RESULT_OK) {
        fprintf(stderr,"cannot open file:%s\n",inputfilename);
        avifDecoderDestroy(decoder);                                     
        return 1;
        }
   
  avifResult  result_8 = avifDecoderParse(decoder);
   if(result_8 == AVIF_RESULT_OK){
        printf(" %s\n",avifResultToString(result_8));
        }

 avifRGBImageSetDefaults(&rgb, decoder->image);
    rgb.depth = 8;
    rgb.format=AVIF_RGB_FORMAT_RGBA;
    rgb.chromaUpsampling = chromaUpsampling;
    avifRGBImageAllocatePixels(&rgb);
    avifResult result_r = avifImageYUVToRGB(decoder->image, &rgb);
    if (result_r != AVIF_RESULT_OK) {
        printf( "%s\n", avifResultToString(result_r));}
   

 avifDecoderDestroy(decoder);
  return 0;
                  }

**Comment by vigneshvg** [comment]
Hi @NarayanBissoyi

Thanks for sharing the code snippet. It seems like you are missing the call to `avifDecoderNextImage()` before converting it to RGB.

The order in which the functions should be called is as follows:

```C
avifDecoderSetIOFile(...);
avifDecoderParse(...);
avifDecoderNextImage(...);  // this call is currently missing.
avifImageYUVToRGB(...);
```

Hope that helps. Please feel free to re-open the issue if you have any further questions. Thanks!
