### ISSUE TITLE
how to build libaom for arm-v7 android

### ISSUE THREAD

**Issue by NarayanBissoyi** [AOMediaCodec/libavif#967]
When I was  building  libaom using the android ndk and cmake-gui , it showing the error cpu-feature.h not found during ninja build .
How can I compile libaom for android to encode bitmaps

**Comment by jzern** [comment]
Thanks for the report. It seems this path is untested and would need some work to fix the link. Android made NEON a default requirement starting from M I believe, so you can set -DCONFIG_RUNTIME_CPU_DETECT=0 or use the toolchain file [1] if you don't need to support very old versions of the platform. Note, though, that support for non-NEON builds will be removed in future NDKs [2].

Also, https://bugs.chromium.org/p/aomedia is a better location for libaom specific bugs.

[1] https://aomedia.googlesource.com/aom/+/89f6a5a47816b5e7ce24add48b161cbfb2b98bd5/build/cmake/toolchains/android.cmake
[2] https://github.com/android/ndk/wiki/Changelog-r23
