### ISSUE TITLE
Encoding of big png silently fails

### ISSUE THREAD

**Issue by danielniccoli** [AOMediaCodec/libavif#992]
I have a png file with the size of 37120 x 73984 pixels (W x H). Encoding it with `.\avifenc.exe  .\output_world.png .\output_world.avif` (on Windows) silently fails and there is no output file.

Upon further inspection, I could find an exit code: 0xc0000409

Version: 0.10.1 (dav1d [dec]:1.0.0-0-g99172b1, aom [enc/dec]:3.3.0, rav1e [enc]:0.5.1 (v0.5.1), svt [enc]:v1.1.0)

**Comment by danielniccoli** [comment]
How do I get a stack trace?

Link to image: https://1drv.ms/u/s!AmQg3eUYceo2pA7sKgtRKjsILT0U?e=XyeVrs

**Comment by jzern** [comment]
Thanks for uploading the image.

For the stacktrace I was hoping a debug build might give some more information in any failure pop-up or you could try running the binary under Visual Studio, for instance.

How are you building libavif and the dependent libs?

**Comment by joedrago** [comment]
On my build this is abort()ing in `malloc()` as this line of code in `avifImageAllocatePlanes()` is overflowing:

```
int fullSize = fullRowBytes * image->height;
```
`36864 * 73728 = 2717908992`, which overflows the signed i32 here, so it attempts to allocate `-1577058304` bytes, which comes through as `18,446,744,072,132,493,312` bytes in `avifAlloc()`. 

We need overflow checks here, and probably should honor `AVIF_DEFAULT_IMAGE_SIZE_LIMIT` too.

**Comment by danielniccoli** [comment]
I was not building from code, but using a Windows build from https://ci.appveyor.com/project/louquillio/libavif/builds/43929886/artifacts
