### ISSUE TITLE
AppVeyor build step timeout

### ISSUE THREAD

**Issue by y-guyon** [AOMediaCodec/libavif#998]
It appears the AppVeyor build step in libavif's GitHub Continuous Integration testing process has been timeouting for more than a month now. It seemingly began with the commit titled "ext: Checkout libaom v3.4.0" ([first failure log](https://ci.appveyor.com/project/louquillio/libavif/builds/43931672/messages)).

@louquillio Do you have any insight on this? Should we increase the AppVeyor plan to avoid the timeout, figure out a way to speed up the build, or even get rid of the AppVeyor setup?

For platform coverage, we may build on Windows directly as a GitHub action.
For binary releases, maybe we can restrict AppVeyor builds to main branch changes, or even to libavif major/minor version updates.
This is all configured on the AppVeyor side, right? The [appveyor.yml](https://github.com/AOMediaCodec/libavif/blob/main/appveyor.yml) file only contain build and deployment instructions, not triggering events.

I briefly tried to bump the AppVeyor Visual Studio version to 2022 in https://github.com/AOMediaCodec/libavif/pull/997 in case it solved the issue but I encountered annoying errors such as [meson's "Could not find Windows resource compiler"](https://ci.appveyor.com/project/louquillio/libavif/builds/44295792) or [dav1d's "Cannot open include file: windows.h"](https://ci.appveyor.com/project/louquillio/libavif-93od3/builds/44297619). Do you think it is worth spending more time trying to make it work?

**Comment by wantehchang** [comment]
Another problem is that our AppVeyor build is queued for a long time (several hours) before it gets to start.

**Comment by wantehchang** [comment]
We can consider this as fixed by https://github.com/AOMediaCodec/libavif/pull/1000. However, the long queuing time (in the order of hours) is still a serious problem.

**Comment by tongyuantongyu** [comment]
Would like to mention that Github CI can also release binary by uploading artifact: https://github.com/actions/upload-artifact .

**Comment by wantehchang** [comment]
Yannis: I think you removed the AppVeyor build. If so, please close this issue as obsolete. Thanks.

**Comment by y-guyon** [comment]
AppVeyor was not removed but limited to the v1.0.x branch in https://github.com/AOMediaCodec/libavif/pull/1921.  
It is planned to be replaced by GitHub release artifacts anyway.
